#ifndef LIBRARIES_KEYFRAME_H
#define LIBRARIES_KEYFRAME_H

enum 
{
	INTERPOLATE_HOLD,
	INTERPOLATE_LINEAR,
	INTERPOLATE_COSINE,
	INTERPOLATE_CATMULLROM
};

enum
{
	KEYFRAME_VALUE,
	KEYFRAME_POSITION
};

enum
{
	KEYFRAMEHANDLE_MIN,
	KEYFRAMEHANDLE_MAX,
	KEYFRAMEHANDLE_BEGIN,
	KEYFRAMEHANDLE_END,
	KEYFRAMEHANDLE_INTERPOLATION_MODE
};

#define EVENT_KEYFRAME_SET			(1UL << 0)
#define EVENT_KEYFRAME_CREATE		(1UL << 1)
#define EVENT_KEYFRAME_DELETE		(1UL << 2)
#define EVENT_KEYFRAMEHANDLE_SET	(1UL << 3)
#define EVENT_KEYFRAME_ALL 			(EVENT_KEYFRAME_SET | EVENT_KEYFRAME_CREATE | EVENT_KEYFRAME_DELETE | EVENT_KEYFRAMEHANDLE_SET)

#endif /* LIBRARIES_KEYFRAME_H */

