/*
** This file was automatically generated by fdtrans.
** Do not edit it by hand. Instead, edit the sfd file
** that was used to generate this file
*/

#ifdef __USE_INLINE__
#undef __USE_INLINE__
#endif
#ifndef __NOGLOBALIFACE__
#define __NOGLOBALIFACE__
#endif

#include <exec/interfaces.h>
#include <exec/libraries.h>
#include <exec/emulation.h>
#include <interfaces/exec.h>
#include <internal/interfaces/language.h>
#include <internal/proto/language.h>



STATIC ULONG stub_OpenPPC(ULONG *regarray)
{
	struct Library *Base = (struct Library *) regarray[REG68K_A6/4];
	struct ExtendedLibrary *ExtLib = (struct ExtendedLibrary *) ((ULONG)Base + Base->lib_PosSize);
	struct LibraryManagerInterface *Self = (struct LibraryManagerInterface *) ExtLib->ILibrary;

	return (ULONG) Self->Open(0);
}
STATIC CONST struct EmuTrap stub_Open = { TRAPINST, TRAPTYPE, stub_OpenPPC };

STATIC ULONG stub_ClosePPC(ULONG *regarray)
{
	struct Library *Base = (struct Library *) regarray[REG68K_A6/4];
	struct ExtendedLibrary *ExtLib = (struct ExtendedLibrary *) ((ULONG)Base + Base->lib_PosSize);
	struct LibraryManagerInterface *Self = (struct LibraryManagerInterface *) ExtLib->ILibrary;

	return (ULONG) Self->Close();
}
STATIC CONST struct EmuTrap stub_Close = { TRAPINST, TRAPTYPE, stub_ClosePPC };

STATIC ULONG stub_ExpungePPC(ULONG *regarray)
{
	return 0UL;
}
STATIC CONST struct EmuTrap stub_Expunge = { TRAPINST, TRAPTYPE, stub_ExpungePPC };

STATIC ULONG stub_ReservedPPC(ULONG *regarray)
{
	return 0UL;
}
STATIC CONST struct EmuTrap stub_Reserved = { TRAPINST, TRAPTYPE, stub_ReservedPPC };

static ULONG stub_LG_GetDriverInfoPPC(ULONG *regarray)
{
	struct Library *Base = (struct Library *) regarray[REG68K_A6/4];
	struct ExtendedLibrary *ExtLib = (struct ExtendedLibrary *) ((ULONG)Base + Base->lib_PosSize);
	struct LanguageIFace *Self = (struct LanguageIFace *) ExtLib->MainIFace;

	return Self->LG_GetDriverInfo(
	);
}
STATIC CONST struct EmuTrap stub_LG_GetDriverInfo = { TRAPINST, TRAPTYPE, (ULONG (*)(ULONG *))stub_LG_GetDriverInfoPPC };

static ULONG stub_LG_ConvToLowerPPC(ULONG *regarray)
{
	struct Library *Base = (struct Library *) regarray[REG68K_A6/4];
	struct ExtendedLibrary *ExtLib = (struct ExtendedLibrary *) ((ULONG)Base + Base->lib_PosSize);
	struct LanguageIFace *Self = (struct LanguageIFace *) ExtLib->MainIFace;

	return Self->LG_ConvToLower(
		(ULONG)regarray[0]
	);
}
STATIC CONST struct EmuTrap stub_LG_ConvToLower = { TRAPINST, TRAPTYPE, (ULONG (*)(ULONG *))stub_LG_ConvToLowerPPC };

static ULONG stub_LG_ConvToUpperPPC(ULONG *regarray)
{
	struct Library *Base = (struct Library *) regarray[REG68K_A6/4];
	struct ExtendedLibrary *ExtLib = (struct ExtendedLibrary *) ((ULONG)Base + Base->lib_PosSize);
	struct LanguageIFace *Self = (struct LanguageIFace *) ExtLib->MainIFace;

	return Self->LG_ConvToUpper(
		(ULONG)regarray[0]
	);
}
STATIC CONST struct EmuTrap stub_LG_ConvToUpper = { TRAPINST, TRAPTYPE, (ULONG (*)(ULONG *))stub_LG_ConvToUpperPPC };

static ULONG stub_LG_GetCodeSetPPC(ULONG *regarray)
{
	struct Library *Base = (struct Library *) regarray[REG68K_A6/4];
	struct ExtendedLibrary *ExtLib = (struct ExtendedLibrary *) ((ULONG)Base + Base->lib_PosSize);
	struct LanguageIFace *Self = (struct LanguageIFace *) ExtLib->MainIFace;

	return Self->LG_GetCodeSet(
	);
}
STATIC CONST struct EmuTrap stub_LG_GetCodeSet = { TRAPINST, TRAPTYPE, (ULONG (*)(ULONG *))stub_LG_GetCodeSetPPC };

static CONST_STRPTR stub_LG_GetLocaleStrPPC(ULONG *regarray)
{
	struct Library *Base = (struct Library *) regarray[REG68K_A6/4];
	struct ExtendedLibrary *ExtLib = (struct ExtendedLibrary *) ((ULONG)Base + Base->lib_PosSize);
	struct LanguageIFace *Self = (struct LanguageIFace *) ExtLib->MainIFace;

	return Self->LG_GetLocaleStr(
		(ULONG)regarray[0]
	);
}
STATIC CONST struct EmuTrap stub_LG_GetLocaleStr = { TRAPINST, TRAPTYPE, (ULONG (*)(ULONG *))stub_LG_GetLocaleStrPPC };

static LONG stub_LG_IsAlNumPPC(ULONG *regarray)
{
	struct Library *Base = (struct Library *) regarray[REG68K_A6/4];
	struct ExtendedLibrary *ExtLib = (struct ExtendedLibrary *) ((ULONG)Base + Base->lib_PosSize);
	struct LanguageIFace *Self = (struct LanguageIFace *) ExtLib->MainIFace;

	return Self->LG_IsAlNum(
		(ULONG)regarray[0]
	);
}
STATIC CONST struct EmuTrap stub_LG_IsAlNum = { TRAPINST, TRAPTYPE, (ULONG (*)(ULONG *))stub_LG_IsAlNumPPC };

static LONG stub_LG_IsAlphaPPC(ULONG *regarray)
{
	struct Library *Base = (struct Library *) regarray[REG68K_A6/4];
	struct ExtendedLibrary *ExtLib = (struct ExtendedLibrary *) ((ULONG)Base + Base->lib_PosSize);
	struct LanguageIFace *Self = (struct LanguageIFace *) ExtLib->MainIFace;

	return Self->LG_IsAlpha(
		(ULONG)regarray[0]
	);
}
STATIC CONST struct EmuTrap stub_LG_IsAlpha = { TRAPINST, TRAPTYPE, (ULONG (*)(ULONG *))stub_LG_IsAlphaPPC };

static LONG stub_LG_IsCntrlPPC(ULONG *regarray)
{
	struct Library *Base = (struct Library *) regarray[REG68K_A6/4];
	struct ExtendedLibrary *ExtLib = (struct ExtendedLibrary *) ((ULONG)Base + Base->lib_PosSize);
	struct LanguageIFace *Self = (struct LanguageIFace *) ExtLib->MainIFace;

	return Self->LG_IsCntrl(
		(ULONG)regarray[0]
	);
}
STATIC CONST struct EmuTrap stub_LG_IsCntrl = { TRAPINST, TRAPTYPE, (ULONG (*)(ULONG *))stub_LG_IsCntrlPPC };

static LONG stub_LG_IsDigitPPC(ULONG *regarray)
{
	struct Library *Base = (struct Library *) regarray[REG68K_A6/4];
	struct ExtendedLibrary *ExtLib = (struct ExtendedLibrary *) ((ULONG)Base + Base->lib_PosSize);
	struct LanguageIFace *Self = (struct LanguageIFace *) ExtLib->MainIFace;

	return Self->LG_IsDigit(
		(ULONG)regarray[0]
	);
}
STATIC CONST struct EmuTrap stub_LG_IsDigit = { TRAPINST, TRAPTYPE, (ULONG (*)(ULONG *))stub_LG_IsDigitPPC };

static LONG stub_LG_IsGraphPPC(ULONG *regarray)
{
	struct Library *Base = (struct Library *) regarray[REG68K_A6/4];
	struct ExtendedLibrary *ExtLib = (struct ExtendedLibrary *) ((ULONG)Base + Base->lib_PosSize);
	struct LanguageIFace *Self = (struct LanguageIFace *) ExtLib->MainIFace;

	return Self->LG_IsGraph(
		(ULONG)regarray[0]
	);
}
STATIC CONST struct EmuTrap stub_LG_IsGraph = { TRAPINST, TRAPTYPE, (ULONG (*)(ULONG *))stub_LG_IsGraphPPC };

static LONG stub_LG_IsLowerPPC(ULONG *regarray)
{
	struct Library *Base = (struct Library *) regarray[REG68K_A6/4];
	struct ExtendedLibrary *ExtLib = (struct ExtendedLibrary *) ((ULONG)Base + Base->lib_PosSize);
	struct LanguageIFace *Self = (struct LanguageIFace *) ExtLib->MainIFace;

	return Self->LG_IsLower(
		(ULONG)regarray[0]
	);
}
STATIC CONST struct EmuTrap stub_LG_IsLower = { TRAPINST, TRAPTYPE, (ULONG (*)(ULONG *))stub_LG_IsLowerPPC };

static LONG stub_LG_IsPrintPPC(ULONG *regarray)
{
	struct Library *Base = (struct Library *) regarray[REG68K_A6/4];
	struct ExtendedLibrary *ExtLib = (struct ExtendedLibrary *) ((ULONG)Base + Base->lib_PosSize);
	struct LanguageIFace *Self = (struct LanguageIFace *) ExtLib->MainIFace;

	return Self->LG_IsPrint(
		(ULONG)regarray[0]
	);
}
STATIC CONST struct EmuTrap stub_LG_IsPrint = { TRAPINST, TRAPTYPE, (ULONG (*)(ULONG *))stub_LG_IsPrintPPC };

static LONG stub_LG_IsPunctPPC(ULONG *regarray)
{
	struct Library *Base = (struct Library *) regarray[REG68K_A6/4];
	struct ExtendedLibrary *ExtLib = (struct ExtendedLibrary *) ((ULONG)Base + Base->lib_PosSize);
	struct LanguageIFace *Self = (struct LanguageIFace *) ExtLib->MainIFace;

	return Self->LG_IsPunct(
		(ULONG)regarray[0]
	);
}
STATIC CONST struct EmuTrap stub_LG_IsPunct = { TRAPINST, TRAPTYPE, (ULONG (*)(ULONG *))stub_LG_IsPunctPPC };

static LONG stub_LG_IsSpacePPC(ULONG *regarray)
{
	struct Library *Base = (struct Library *) regarray[REG68K_A6/4];
	struct ExtendedLibrary *ExtLib = (struct ExtendedLibrary *) ((ULONG)Base + Base->lib_PosSize);
	struct LanguageIFace *Self = (struct LanguageIFace *) ExtLib->MainIFace;

	return Self->LG_IsSpace(
		(ULONG)regarray[0]
	);
}
STATIC CONST struct EmuTrap stub_LG_IsSpace = { TRAPINST, TRAPTYPE, (ULONG (*)(ULONG *))stub_LG_IsSpacePPC };

static LONG stub_LG_IsUpperPPC(ULONG *regarray)
{
	struct Library *Base = (struct Library *) regarray[REG68K_A6/4];
	struct ExtendedLibrary *ExtLib = (struct ExtendedLibrary *) ((ULONG)Base + Base->lib_PosSize);
	struct LanguageIFace *Self = (struct LanguageIFace *) ExtLib->MainIFace;

	return Self->LG_IsUpper(
		(ULONG)regarray[0]
	);
}
STATIC CONST struct EmuTrap stub_LG_IsUpper = { TRAPINST, TRAPTYPE, (ULONG (*)(ULONG *))stub_LG_IsUpperPPC };

static LONG stub_LG_IsXDigitPPC(ULONG *regarray)
{
	struct Library *Base = (struct Library *) regarray[REG68K_A6/4];
	struct ExtendedLibrary *ExtLib = (struct ExtendedLibrary *) ((ULONG)Base + Base->lib_PosSize);
	struct LanguageIFace *Self = (struct LanguageIFace *) ExtLib->MainIFace;

	return Self->LG_IsXDigit(
		(ULONG)regarray[0]
	);
}
STATIC CONST struct EmuTrap stub_LG_IsXDigit = { TRAPINST, TRAPTYPE, (ULONG (*)(ULONG *))stub_LG_IsXDigitPPC };

static ULONG stub_LG_StrConvertPPC(ULONG *regarray)
{
	struct Library *Base = (struct Library *) regarray[REG68K_A6/4];
	struct ExtendedLibrary *ExtLib = (struct ExtendedLibrary *) ((ULONG)Base + Base->lib_PosSize);
	struct LanguageIFace *Self = (struct LanguageIFace *) ExtLib->MainIFace;

	return Self->LG_StrConvert(
		(CONST_STRPTR)regarray[9],
		(APTR)regarray[10],
		(ULONG)regarray[0],
		(ULONG)regarray[1]
	);
}
STATIC CONST struct EmuTrap stub_LG_StrConvert = { TRAPINST, TRAPTYPE, (ULONG (*)(ULONG *))stub_LG_StrConvertPPC };

static LONG stub_LG_StrnCmpPPC(ULONG *regarray)
{
	struct Library *Base = (struct Library *) regarray[REG68K_A6/4];
	struct ExtendedLibrary *ExtLib = (struct ExtendedLibrary *) ((ULONG)Base + Base->lib_PosSize);
	struct LanguageIFace *Self = (struct LanguageIFace *) ExtLib->MainIFace;

	return Self->LG_StrnCmp(
		(CONST_STRPTR)regarray[9],
		(CONST_STRPTR)regarray[10],
		(LONG)regarray[0],
		(ULONG)regarray[1]
	);
}
STATIC CONST struct EmuTrap stub_LG_StrnCmp = { TRAPINST, TRAPTYPE, (ULONG (*)(ULONG *))stub_LG_StrnCmpPPC };

static LONG stub_LG_IsBlankPPC(ULONG *regarray)
{
	struct Library *Base = (struct Library *) regarray[REG68K_A6/4];
	struct ExtendedLibrary *ExtLib = (struct ExtendedLibrary *) ((ULONG)Base + Base->lib_PosSize);
	struct LanguageIFace *Self = (struct LanguageIFace *) ExtLib->MainIFace;

	return Self->LG_IsBlank(
		(ULONG)regarray[0]
	);
}
STATIC CONST struct EmuTrap stub_LG_IsBlank = { TRAPINST, TRAPTYPE, (ULONG (*)(ULONG *))stub_LG_IsBlankPPC };

APTR VecTable68K[] =
{
	&stub_Open,
	&stub_Close,
	&stub_Expunge,
	&stub_Reserved,
	&stub_LG_GetDriverInfo,
	&stub_LG_ConvToLower,
	&stub_LG_ConvToUpper,
	&stub_LG_GetCodeSet,
	&stub_LG_GetLocaleStr,
	&stub_LG_IsAlNum,
	&stub_LG_IsAlpha,
	&stub_LG_IsCntrl,
	&stub_LG_IsDigit,
	&stub_LG_IsGraph,
	&stub_LG_IsLower,
	&stub_LG_IsPrint,
	&stub_LG_IsPunct,
	&stub_LG_IsSpace,
	&stub_LG_IsUpper,
	&stub_LG_IsXDigit,
	&stub_LG_StrConvert,
	&stub_LG_StrnCmp,
	&stub_LG_IsBlank,
	(APTR)-1
};
