#ifndef POWERUP_PPCLIB_SEMAPHORE_H
#define POWERUP_PPCLIB_SEMAPHORE_H

#include <utility/tagitem.h>

#define	PPCSEMAPHORETAG_BASE	(TAG_USER + 0x25000)

/* Sets the Name for the Semaphore and automaticly adds the Semaphore to
   the public List
 */
#define	PPCSEMAPHORETAG_NAME	(PPCSEMAPHORETAG_BASE+0)


#define	PPCSEMAPHORETAG_ERROR	(PPCSEMAPHORETAG_BASE+1)

#define	PPCSEMAPHOREERROR_OK		0
#define	PPCSEMAPHOREERROR_MEMORY	1
#define	PPCSEMAPHOREERROR_ALREDYEXISTS	2
#define	PPCSEMAPHOREERROR_NOTFOUND	3
#define	PPCSEMAPHOREERROR_OBTAINED	4
#define	PPCSEMAPHOREERROR_NONAME	5

#endif
