#ifndef INLINE4_AHI_H
#define INLINE4_AHI_H

/*
** This file was auto generated by idltool 53.7.
**
** It provides compatibility to OS3 style library
** calls by substituting functions.
**
** Do not edit manually.
*/ 

#ifndef EXEC_TYPES_H
#include <exec/types.h>
#endif
#ifndef EXEC_EXEC_H
#include <exec/exec.h>
#endif
#ifndef EXEC_INTERFACES_H
#include <exec/interfaces.h>
#endif

#ifndef EXEC_DEVICES_H
#include <exec/devices.h>
#endif
#ifndef UTILITY_TAGITEM_H
#include <utility/tagitem.h>
#endif
#ifndef DEVICES_AHI_H
#include <devices/ahi.h>
#endif
#include <interfaces/ahi.h>

/* Inline macros for Interface "main" */
#define AHI_AllocAudioA(tagList) IAHI->AHI_AllocAudioA((tagList)) 
#if (defined(__STDC_VERSION__) && __STDC_VERSION__ >= 199901L) || (__GNUC__ >= 3)
#define AHI_AllocAudio(...) IAHI->AHI_AllocAudio(__VA_ARGS__) 
#elif (__GNUC__ == 2 && __GNUC_MINOR__ >= 95)
#define AHI_AllocAudio(...) IAHI->AHI_AllocAudio(## vargs) 
#endif
#define AHI_FreeAudio(AudioCtrl) IAHI->AHI_FreeAudio((AudioCtrl)) 
#define AHI_KillAudio() IAHI->AHI_KillAudio() 
#define AHI_ControlAudioA(AudioCtrl, tagList) IAHI->AHI_ControlAudioA((AudioCtrl), (tagList)) 
#if (defined(__STDC_VERSION__) && __STDC_VERSION__ >= 199901L) || (__GNUC__ >= 3)
#define AHI_ControlAudio(...) IAHI->AHI_ControlAudio(__VA_ARGS__) 
#elif (__GNUC__ == 2 && __GNUC_MINOR__ >= 95)
#define AHI_ControlAudio(vargs...) IAHI->AHI_ControlAudio(## vargs) 
#endif
#define AHI_SetVol(Channel, Volume, Pan, AudioCtrl, Flags) IAHI->AHI_SetVol((Channel), (Volume), (Pan), (AudioCtrl), (Flags)) 
#define AHI_SetFreq(Channel, Freq, AudioCtrl, Flags) IAHI->AHI_SetFreq((Channel), (Freq), (AudioCtrl), (Flags)) 
#define AHI_SetSound(Channel, Sound, Offset, Length, AudioCtrl, Flags) IAHI->AHI_SetSound((Channel), (Sound), (Offset), (Length), (AudioCtrl), (Flags)) 
#define AHI_SetEffect(Effect, AudioCtrl) IAHI->AHI_SetEffect((Effect), (AudioCtrl)) 
#define AHI_LoadSound(Sound, Type, Info, AudioCtrl) IAHI->AHI_LoadSound((Sound), (Type), (Info), (AudioCtrl)) 
#define AHI_UnloadSound(Sound, Audioctrl) IAHI->AHI_UnloadSound((Sound), (Audioctrl)) 
#define AHI_NextAudioID(Last_ID) IAHI->AHI_NextAudioID((Last_ID)) 
#define AHI_GetAudioAttrsA(ID, Audioctrl, tagList) IAHI->AHI_GetAudioAttrsA((ID), (Audioctrl), (tagList)) 
#if (defined(__STDC_VERSION__) && __STDC_VERSION__ >= 199901L) || (__GNUC__ >= 3)
#define AHI_GetAudioAttrs(ID, ...) IAHI->AHI_GetAudioAttrs((ID), __VA_ARGS__) 
#elif (__GNUC__ == 2 && __GNUC_MINOR__ >= 95)
#define AHI_GetAudioAttrs(ID, vargs...) IAHI->AHI_GetAudioAttrs(ID, ## vargs) 
#endif
#define AHI_BestAudioIDA(tagList) IAHI->AHI_BestAudioIDA((tagList)) 
#if (defined(__STDC_VERSION__) && __STDC_VERSION__ >= 199901L) || (__GNUC__ >= 3)
#define AHI_BestAudioID(...) IAHI->AHI_BestAudioID(__VA_ARGS__) 
#elif (__GNUC__ == 2 && __GNUC_MINOR__ >= 95)
#define AHI_BestAudioID(...) IAHI->AHI_BestAudioID(## vargs) 
#endif
#define AHI_AllocAudioRequestA(tagList) IAHI->AHI_AllocAudioRequestA((tagList)) 
#if (defined(__STDC_VERSION__) && __STDC_VERSION__ >= 199901L) || (__GNUC__ >= 3)
#define AHI_AllocAudioRequest(...) IAHI->AHI_AllocAudioRequest(__VA_ARGS__) 
#elif (__GNUC__ == 2 && __GNUC_MINOR__ >= 95)
#define AHI_AllocAudioRequest(...) IAHI->AHI_AllocAudioRequest(## vargs) 
#endif
#define AHI_AudioRequestA(Requester, tagList) IAHI->AHI_AudioRequestA((Requester), (tagList)) 
#if (defined(__STDC_VERSION__) && __STDC_VERSION__ >= 199901L) || (__GNUC__ >= 3)
#define AHI_AudioRequest(...) IAHI->AHI_AudioRequest(__VA_ARGS__) 
#elif (__GNUC__ == 2 && __GNUC_MINOR__ >= 95)
#define AHI_AudioRequest(vargs...) IAHI->AHI_AudioRequest(## vargs) 
#endif
#define AHI_FreeAudioRequest(Requester) IAHI->AHI_FreeAudioRequest((Requester)) 
#define AHI_PlayA(Audioctrl, tagList) IAHI->AHI_PlayA((Audioctrl), (tagList)) 
#if (defined(__STDC_VERSION__) && __STDC_VERSION__ >= 199901L) || (__GNUC__ >= 3)
#define AHI_Play(...) IAHI->AHI_Play(__VA_ARGS__) 
#elif (__GNUC__ == 2 && __GNUC_MINOR__ >= 95)
#define AHI_Play(vargs...) IAHI->AHI_Play(## vargs) 
#endif
#define AHI_SampleFrameSize(SampleType) IAHI->AHI_SampleFrameSize((SampleType)) 
#define AHI_AddAudioMode(AHIPrivate) IAHI->AHI_AddAudioMode((AHIPrivate)) 
#define AHI_RemoveAudioMode(AHIPrivate) IAHI->AHI_RemoveAudioMode((AHIPrivate)) 
#define AHI_LoadModeFile(AHIPrivate) IAHI->AHI_LoadModeFile((AHIPrivate)) 

#endif /* INLINE4_AHI_H */
