#ifndef INLINE4_BOOTSD_H
#define INLINE4_BOOTSD_H

/*
** This file was auto generated by idltool 53.6.
**
** It provides compatibility to OS3 style library
** calls by substituting functions.
**
** Do not edit manually.
*/ 

#ifndef EXEC_TYPES_H
#include <exec/types.h>
#endif
#ifndef EXEC_EXEC_H
#include <exec/exec.h>
#endif
#ifndef EXEC_INTERFACES_H
#include <exec/interfaces.h>
#endif

#include <interfaces/bootsd.h>

/* Inline macros for Interface "main" */
#define AllocResource(error) IBootSD->AllocResource((error)) 
#define FreeResource(unit) IBootSD->FreeResource((unit)) 
#define GetGeometry(unit, error, geom) IBootSD->GetGeometry((unit), (error), (geom)) 
#define ReadSDCard(unit, error, buffer, startBlock, numBlocks) IBootSD->ReadSDCard((unit), (error), (buffer), (startBlock), (numBlocks)) 
#define WriteSDCard(unit, error, buffer, startBlock, numBlocks) IBootSD->WriteSDCard((unit), (error), (buffer), (startBlock), (numBlocks)) 

#endif /* INLINE4_BOOTSD_H */
