#ifndef INLINE4_CAMDDRIVER_H
#define INLINE4_CAMDDRIVER_H

/*
** This file was auto generated by idltool 50.13.
**
** It provides compatibility to OS3 style library
** calls by substituting functions.
**
** Do not edit manually.
*/ 

#ifndef EXEC_TYPES_H
#include <exec/types.h>
#endif
#ifndef EXEC_EXEC_H
#include <exec/exec.h>
#endif
#ifndef EXEC_INTERFACES_H
#include <exec/interfaces.h>
#endif


/* Inline macros for Interface "main" */
#define GetMidiDeviceData() ICamdDriver->GetMidiDeviceData() 
#define OpenPort(data, portnum, transmitfunc, receivefunc, userdata) ICamdDriver->OpenPort(data, portnum, transmitfunc, receivefunc, userdata) 
#define ClosePort(data, portnum) ICamdDriver->ClosePort(data, portnum) 
#define ActivateXmit(userdata, portnum) ICamdDriver->ActivateXmit(userdata, portnum) 

#endif /* INLINE4_CAMDDRIVER_H */
