#ifndef INLINE4_CARDRES_H
#define INLINE4_CARDRES_H

/*
** This file was auto generated by idltool 51.8.
**
** It provides compatibility to OS3 style library
** calls by substituting functions.
**
** Do not edit manually.
*/ 

#ifndef EXEC_TYPES_H
#include <exec/types.h>
#endif
#ifndef EXEC_EXEC_H
#include <exec/exec.h>
#endif
#ifndef EXEC_INTERFACES_H
#include <exec/interfaces.h>
#endif

#ifndef EXEC_RESIDENT_H
#include <exec/resident.h>
#endif
#ifndef RESOURCES_CARD_H
#include <resources/card.h>
#endif

/* Inline macros for Interface "main" */
#define OwnCard(handle) ICard->OwnCard(handle) 
#define ReleaseCard(handle, flags) ICard->ReleaseCard(handle, flags) 
#define GetCardMap() ICard->GetCardMap() 
#define BeginCardAccess(handle) ICard->BeginCardAccess(handle) 
#define EndCardAccess(handle) ICard->EndCardAccess(handle) 
#define ReadCardStatus() ICard->ReadCardStatus() 
#define CardResetRemove(handle, flag) ICard->CardResetRemove(handle, flag) 
#define CardMiscControl(handle, control_bits) ICard->CardMiscControl(handle, control_bits) 
#define CardAccessSpeed(handle, nanoseconds) ICard->CardAccessSpeed(handle, nanoseconds) 
#define CardProgramVoltage(handle, voltage) ICard->CardProgramVoltage(handle, voltage) 
#define CardResetCard(handle) ICard->CardResetCard(handle) 
#define CopyTuple(handle, buffer, tuplecode, size) ICard->CopyTuple(handle, buffer, tuplecode, size) 
#define DeviceTuple(tuple_data, storage) ICard->DeviceTuple(tuple_data, storage) 
#define IfAmigaXIP(handle) ICard->IfAmigaXIP(handle) 
#define CardForceChange() ICard->CardForceChange() 
#define CardChangeCount() ICard->CardChangeCount() 
#define CardInterface() ICard->CardInterface() 

#endif /* INLINE4_CARDRES_H */
