#ifndef INLINE4_CLICKTAB_H
#define INLINE4_CLICKTAB_H

/*
** This file was auto generated by idltool 52.7.
**
** It provides compatibility to OS3 style library
** calls by substituting functions.
**
** Do not edit manually.
*/ 

#ifndef EXEC_TYPES_H
#include <exec/types.h>
#endif
#ifndef EXEC_EXEC_H
#include <exec/exec.h>
#endif
#ifndef EXEC_INTERFACES_H
#include <exec/interfaces.h>
#endif

#ifndef INTUITION_INTUITION_H
#include <intuition/intuition.h>
#endif
#ifndef INTUITION_CLASSES_H
#include <intuition/classes.h>
#endif
#include <interfaces/clicktab.h>

/* Inline macros for Interface "main" */
#define CLICKTAB_GetClass() IClickTab->CLICKTAB_GetClass() 
#define AllocClickTabNodeA(tags) IClickTab->AllocClickTabNodeA((tags)) 
#if (defined(__STDC_VERSION__) && __STDC_VERSION__ >= 199901L) || (__GNUC__ >= 3)
#define AllocClickTabNode(...) IClickTab->AllocClickTabNode(__VA_ARGS__) 
#elif (__GNUC__ == 2 && __GNUC_MINOR__ >= 95)
#define AllocClickTabNode(...) IClickTab->AllocClickTabNode(## vargs) 
#endif
#define FreeClickTabNode(node) IClickTab->FreeClickTabNode((node)) 
#define SetClickTabNodeAttrsA(node, tags) IClickTab->SetClickTabNodeAttrsA((node), (tags)) 
#if (defined(__STDC_VERSION__) && __STDC_VERSION__ >= 199901L) || (__GNUC__ >= 3)
#define SetClickTabNodeAttrs(...) IClickTab->SetClickTabNodeAttrs(__VA_ARGS__) 
#elif (__GNUC__ == 2 && __GNUC_MINOR__ >= 95)
#define SetClickTabNodeAttrs(vargs...) IClickTab->SetClickTabNodeAttrs(## vargs) 
#endif
#define GetClickTabNodeAttrsA(node, tags) IClickTab->GetClickTabNodeAttrsA((node), (tags)) 
#if (defined(__STDC_VERSION__) && __STDC_VERSION__ >= 199901L) || (__GNUC__ >= 3)
#define GetClickTabNodeAttrs(...) IClickTab->GetClickTabNodeAttrs(__VA_ARGS__) 
#elif (__GNUC__ == 2 && __GNUC_MINOR__ >= 95)
#define GetClickTabNodeAttrs(vargs...) IClickTab->GetClickTabNodeAttrs(## vargs) 
#endif
#define FreeClickTabList(list) IClickTab->FreeClickTabList((list)) 

#endif /* INLINE4_CLICKTAB_H */
