#ifndef INLINE4_COLORWHEEL_H
#define INLINE4_COLORWHEEL_H

/*
** This file was auto generated by idltool 51.8.
**
** It provides compatibility to OS3 style library
** calls by substituting functions.
**
** Do not edit manually.
*/ 

#ifndef EXEC_TYPES_H
#include <exec/types.h>
#endif
#ifndef EXEC_EXEC_H
#include <exec/exec.h>
#endif
#ifndef EXEC_INTERFACES_H
#include <exec/interfaces.h>
#endif

#ifndef GADGETS_COLORWHEEL_H
#include <gadgets/colorwheel.h>
#endif

/* Inline macros for Interface "main" */
#define ConvertHSBToRGB(hsb, rgb) IColorWheel->ConvertHSBToRGB(hsb, rgb) 
#define ConvertRGBToHSB(rgb, hsb) IColorWheel->ConvertRGBToHSB(rgb, hsb) 

#endif /* INLINE4_COLORWHEEL_H */
