#ifndef INLINE4_DATEBROWSER_H
#define INLINE4_DATEBROWSER_H

/*
** This file was auto generated by idltool 51.8.
**
** It provides compatibility to OS3 style library
** calls by substituting functions.
**
** Do not edit manually.
*/ 

#ifndef EXEC_TYPES_H
#include <exec/types.h>
#endif
#ifndef EXEC_EXEC_H
#include <exec/exec.h>
#endif
#ifndef EXEC_INTERFACES_H
#include <exec/interfaces.h>
#endif

#ifndef INTUITION_INTUITION_H
#include <intuition/intuition.h>
#endif
#ifndef INTUITION_CLASSES_H
#include <intuition/classes.h>
#endif

/* Inline macros for Interface "main" */
#define DATEBROWSER_GetClass() IDateBrowser->DATEBROWSER_GetClass() 
#define JulianWeekDay(day, month, year) IDateBrowser->JulianWeekDay(day, month, year) 
#define JulianMonthDays(month, year) IDateBrowser->JulianMonthDays(month, year) 
#define JulianLeapYear(year) IDateBrowser->JulianLeapYear(year) 

#endif /* INLINE4_DATEBROWSER_H */
