#ifndef INLINE4_DIFFVIEW_H
#define INLINE4_DIFFVIEW_H

/*
** This file was auto generated by idltool 53.6.
**
** It provides compatibility to OS3 style library
** calls by substituting functions.
**
** Do not edit manually.
*/ 

#ifndef EXEC_TYPES_H
#include <exec/types.h>
#endif
#ifndef EXEC_EXEC_H
#include <exec/exec.h>
#endif
#ifndef EXEC_INTERFACES_H
#include <exec/interfaces.h>
#endif

#ifndef INTUITION_INTUITION_H
#include <intuition/intuition.h>
#endif
#ifndef INTUITION_CLASSES_H
#include <intuition/classes.h>
#endif
#ifndef GADGETS_DIFFVIEW_H
#include <gadgets/diffview.h>
#endif
#include <interfaces/diffview.h>

/* Inline macros for Interface "main" */
#define CreateDiffObject(Tags) IDiffView->CreateDiffObject((Tags)) 
#if (defined(__STDC_VERSION__) && __STDC_VERSION__ >= 199901L) || (__GNUC__ >= 3)
#define CreateDiffObjectTags(...) IDiffView->CreateDiffObjectTags(__VA_ARGS__) 
#elif (__GNUC__ == 2 && __GNUC_MINOR__ >= 95)
#define CreateDiffObjectTags(...) IDiffView->CreateDiffObjectTags(## vargs) 
#endif
#define FreeDiffObject(DiffObj) IDiffView->FreeDiffObject((DiffObj)) 
#define GetDiffObjectAttr(DiffObj, Attr, Storage) IDiffView->GetDiffObjectAttr((DiffObj), (Attr), (Storage)) 

#endif /* INLINE4_DIFFVIEW_H */
