#ifndef INLINE4_DISKFONT_H
#define INLINE4_DISKFONT_H

/*
** This file was auto generated by idltool 51.8.
**
** It provides compatibility to OS3 style library
** calls by substituting functions.
**
** Do not edit manually.
*/ 

#ifndef EXEC_TYPES_H
#include <exec/types.h>
#endif
#ifndef EXEC_EXEC_H
#include <exec/exec.h>
#endif
#ifndef EXEC_INTERFACES_H
#include <exec/interfaces.h>
#endif

#ifndef DOS_DOS_H
#include <dos/dos.h>
#endif
#ifndef LIBRARIES_DISKFONT_H
#include <libraries/diskfont.h>
#endif
#ifndef UTILITY_TAGITEM_H
#include <utility/tagitem.h>
#endif
#ifndef GRAPHICS_RASTPORT_H
#include <graphics/rastport.h>
#endif

/* Inline macros for Interface "main" */
#define OpenDiskFont(textAttr) IDiskfont->OpenDiskFont(textAttr) 
#define AvailFonts(buffer, bufBytes, flags) IDiskfont->AvailFonts(buffer, bufBytes, flags) 
#define NewFontContents(fontsLock, fontName) IDiskfont->NewFontContents(fontsLock, fontName) 
#define DisposeFontContents(fontContentsHeader) IDiskfont->DisposeFontContents(fontContentsHeader) 
#define NewScaledDiskFont(sourceFont, destTextAttr) IDiskfont->NewScaledDiskFont(sourceFont, destTextAttr) 
#define GetDiskFontCtrl(tagid) IDiskfont->GetDiskFontCtrl(tagid) 
#define SetDiskFontCtrlA(taglist) IDiskfont->SetDiskFontCtrlA(taglist) 
#if (defined(__STDC_VERSION__) && __STDC_VERSION__ >= 199901L) || (__GNUC__ >= 3)
#define SetDiskFontCtrl(...) IDiskfont->SetDiskFontCtrl(__VA_ARGS__) 
#elif (__GNUC__ == 2 && __GNUC_MINOR__ >= 95)
#define SetDiskFontCtrl(...) IDiskfont->SetDiskFontCtrl(## vargs) 
#endif
#define EOpenEngine(EEngine) IDiskfont->EOpenEngine(EEngine) 
#define ECloseEngine(EEngine) IDiskfont->ECloseEngine(EEngine) 
#define ESetInfoA(EEngine, taglist) IDiskfont->ESetInfoA(EEngine, taglist) 
#if (defined(__STDC_VERSION__) && __STDC_VERSION__ >= 199901L) || (__GNUC__ >= 3)
#define ESetInfo(...) IDiskfont->ESetInfo(__VA_ARGS__) 
#elif (__GNUC__ == 2 && __GNUC_MINOR__ >= 95)
#define ESetInfo(vargs...) IDiskfont->ESetInfo(## vargs) 
#endif
#define EObtainInfoA(EEngine, taglist) IDiskfont->EObtainInfoA(EEngine, taglist) 
#if (defined(__STDC_VERSION__) && __STDC_VERSION__ >= 199901L) || (__GNUC__ >= 3)
#define EObtainInfo(...) IDiskfont->EObtainInfo(__VA_ARGS__) 
#elif (__GNUC__ == 2 && __GNUC_MINOR__ >= 95)
#define EObtainInfo(vargs...) IDiskfont->EObtainInfo(## vargs) 
#endif
#define EReleaseInfoA(EEngine, taglist) IDiskfont->EReleaseInfoA(EEngine, taglist) 
#if (defined(__STDC_VERSION__) && __STDC_VERSION__ >= 199901L) || (__GNUC__ >= 3)
#define EReleaseInfo(...) IDiskfont->EReleaseInfo(__VA_ARGS__) 
#elif (__GNUC__ == 2 && __GNUC_MINOR__ >= 95)
#define EReleaseInfo(vargs...) IDiskfont->EReleaseInfo(## vargs) 
#endif
#define OpenOutlineFont(name, list, flags) IDiskfont->OpenOutlineFont(name, list, flags) 
#define CloseOutlineFont(olf, list) IDiskfont->CloseOutlineFont(olf, list) 
#define WriteFontContents(fontsLock, fontName, fontContentsHeader) IDiskfont->WriteFontContents(fontsLock, fontName, fontContentsHeader) 
#define WriteDiskFontHeaderA(font, fileName, taglist) IDiskfont->WriteDiskFontHeaderA(font, fileName, taglist) 
#if (defined(__STDC_VERSION__) && __STDC_VERSION__ >= 199901L) || (__GNUC__ >= 3)
#define WriteDiskFontHeader(font, ...) IDiskfont->WriteDiskFontHeader(font, __VA_ARGS__) 
#elif (__GNUC__ == 2 && __GNUC_MINOR__ >= 95)
#define WriteDiskFontHeader(font, vargs...) IDiskfont->WriteDiskFontHeader(font, ## vargs) 
#endif
#define ObtainCharsetInfo(knownTag, knownValue, wantedTag) IDiskfont->ObtainCharsetInfo(knownTag, knownValue, wantedTag) 
#define ObtainTTextAttr(textFont) IDiskfont->ObtainTTextAttr(textFont) 
#define FreeTTextAttr(tta) IDiskfont->FreeTTextAttr(tta) 

#endif /* INLINE4_DISKFONT_H */
