#ifndef INLINE4_GADTOOLS_H
#define INLINE4_GADTOOLS_H

/*
** This file was auto generated by idltool 51.8.
**
** It provides compatibility to OS3 style library
** calls by substituting functions.
**
** Do not edit manually.
*/ 

#ifndef EXEC_TYPES_H
#include <exec/types.h>
#endif
#ifndef EXEC_EXEC_H
#include <exec/exec.h>
#endif
#ifndef EXEC_INTERFACES_H
#include <exec/interfaces.h>
#endif

#ifndef EXEC_LIBRARIES_H
#include <exec/libraries.h>
#endif
#ifndef INTUITION_INTUITION_H
#include <intuition/intuition.h>
#endif
#ifndef UTILITY_TAGITEM_H
#include <utility/tagitem.h>
#endif
#ifndef LIBRARIES_GADTOOLS_H
#include <libraries/gadtools.h>
#endif

/* Inline macros for Interface "main" */
#define CreateGadgetA(kind, gad, ng, taglist) IGadTools->CreateGadgetA(kind, gad, ng, taglist) 
#if (defined(__STDC_VERSION__) && __STDC_VERSION__ >= 199901L) || (__GNUC__ >= 3)
#define CreateGadget(kind, gad, ...) IGadTools->CreateGadget(kind, gad, __VA_ARGS__) 
#elif (__GNUC__ == 2 && __GNUC_MINOR__ >= 95)
#define CreateGadget(kind, gad, vargs...) IGadTools->CreateGadget(kind, gad, ## vargs) 
#endif
#define FreeGadgets(gad) IGadTools->FreeGadgets(gad) 
#define GT_SetGadgetAttrsA(gad, win, req, taglist) IGadTools->GT_SetGadgetAttrsA(gad, win, req, taglist) 
#if (defined(__STDC_VERSION__) && __STDC_VERSION__ >= 199901L) || (__GNUC__ >= 3)
#define GT_SetGadgetAttrs(gad, win, ...) IGadTools->GT_SetGadgetAttrs(gad, win, __VA_ARGS__) 
#elif (__GNUC__ == 2 && __GNUC_MINOR__ >= 95)
#define GT_SetGadgetAttrs(gad, win, vargs...) IGadTools->GT_SetGadgetAttrs(gad, win, ## vargs) 
#endif
#define CreateMenusA(newmenu, taglist) IGadTools->CreateMenusA(newmenu, taglist) 
#if (defined(__STDC_VERSION__) && __STDC_VERSION__ >= 199901L) || (__GNUC__ >= 3)
#define CreateMenus(...) IGadTools->CreateMenus(__VA_ARGS__) 
#elif (__GNUC__ == 2 && __GNUC_MINOR__ >= 95)
#define CreateMenus(vargs...) IGadTools->CreateMenus(## vargs) 
#endif
#define FreeMenus(menu) IGadTools->FreeMenus(menu) 
#define LayoutMenuItemsA(firstitem, vi, taglist) IGadTools->LayoutMenuItemsA(firstitem, vi, taglist) 
#if (defined(__STDC_VERSION__) && __STDC_VERSION__ >= 199901L) || (__GNUC__ >= 3)
#define LayoutMenuItems(firstitem, ...) IGadTools->LayoutMenuItems(firstitem, __VA_ARGS__) 
#elif (__GNUC__ == 2 && __GNUC_MINOR__ >= 95)
#define LayoutMenuItems(firstitem, vargs...) IGadTools->LayoutMenuItems(firstitem, ## vargs) 
#endif
#define LayoutMenusA(firstmenu, vi, taglist) IGadTools->LayoutMenusA(firstmenu, vi, taglist) 
#if (defined(__STDC_VERSION__) && __STDC_VERSION__ >= 199901L) || (__GNUC__ >= 3)
#define LayoutMenus(firstmenu, ...) IGadTools->LayoutMenus(firstmenu, __VA_ARGS__) 
#elif (__GNUC__ == 2 && __GNUC_MINOR__ >= 95)
#define LayoutMenus(firstmenu, vargs...) IGadTools->LayoutMenus(firstmenu, ## vargs) 
#endif
#define GT_GetIMsg(iport) IGadTools->GT_GetIMsg(iport) 
#define GT_ReplyIMsg(imsg) IGadTools->GT_ReplyIMsg(imsg) 
#define GT_RefreshWindow(win, req) IGadTools->GT_RefreshWindow(win, req) 
#define GT_BeginRefresh(win) IGadTools->GT_BeginRefresh(win) 
#define GT_EndRefresh(win, complete) IGadTools->GT_EndRefresh(win, complete) 
#define GT_FilterIMsg(imsg) IGadTools->GT_FilterIMsg(imsg) 
#define GT_PostFilterIMsg(imsg) IGadTools->GT_PostFilterIMsg(imsg) 
#define CreateContext(glistptr) IGadTools->CreateContext(glistptr) 
#define DrawBevelBoxA(rport, left, top, width, height, taglist) IGadTools->DrawBevelBoxA(rport, left, top, width, height, taglist) 
#if (defined(__STDC_VERSION__) && __STDC_VERSION__ >= 199901L) || (__GNUC__ >= 3)
#define DrawBevelBox(rport, left, top, width, ...) IGadTools->DrawBevelBox(rport, left, top, width, __VA_ARGS__) 
#elif (__GNUC__ == 2 && __GNUC_MINOR__ >= 95)
#define DrawBevelBox(rport, left, top, width, vargs...) IGadTools->DrawBevelBox(rport, left, top, width, ## vargs) 
#endif
#define GetVisualInfoA(screen, taglist) IGadTools->GetVisualInfoA(screen, taglist) 
#if (defined(__STDC_VERSION__) && __STDC_VERSION__ >= 199901L) || (__GNUC__ >= 3)
#define GetVisualInfo(...) IGadTools->GetVisualInfo(__VA_ARGS__) 
#elif (__GNUC__ == 2 && __GNUC_MINOR__ >= 95)
#define GetVisualInfo(vargs...) IGadTools->GetVisualInfo(## vargs) 
#endif
#define FreeVisualInfo(vi) IGadTools->FreeVisualInfo(vi) 
#define GT_GetGadgetAttrsA(gad, win, req, taglist) IGadTools->GT_GetGadgetAttrsA(gad, win, req, taglist) 
#if (defined(__STDC_VERSION__) && __STDC_VERSION__ >= 199901L) || (__GNUC__ >= 3)
#define GT_GetGadgetAttrs(gad, win, ...) IGadTools->GT_GetGadgetAttrs(gad, win, __VA_ARGS__) 
#elif (__GNUC__ == 2 && __GNUC_MINOR__ >= 95)
#define GT_GetGadgetAttrs(gad, win, vargs...) IGadTools->GT_GetGadgetAttrs(gad, win, ## vargs) 
#endif

#endif /* INLINE4_GADTOOLS_H */
