#ifndef INLINE4_HUNK_H
#define INLINE4_HUNK_H

/*
** This file was auto generated by idltool 51.8.
**
** It provides compatibility to OS3 style library
** calls by substituting functions.
**
** Do not edit manually.
*/ 

#ifndef EXEC_TYPES_H
#include <exec/types.h>
#endif
#ifndef EXEC_EXEC_H
#include <exec/exec.h>
#endif
#ifndef EXEC_INTERFACES_H
#include <exec/interfaces.h>
#endif

#ifndef UTILITY_TAGITEM_H
#include <utility/tagitem.h>
#endif
#ifndef LIBRARIES_HUNK_H
#include <libraries/hunk.h>
#endif
#ifndef DOS_DOS_H
#include <dos/dos.h>
#endif
#ifndef INTERFACES_HUNK_H
#include <interfaces/hunk.h>
#endif

/* Inline macros for Interface "main" */
#define LoadHunk(tags) IHunk->LoadHunk(tags) 
#if (defined(__STDC_VERSION__) && __STDC_VERSION__ >= 199901L) || (__GNUC__ >= 3)
#define LoadHunkTags(...) IHunk->LoadHunkTags(__VA_ARGS__) 
#elif (__GNUC__ == 2 && __GNUC_MINOR__ >= 95)
#define LoadHunkTags(...) IHunk->LoadHunkTags(## vargs) 
#endif
#define UnLoadHunk(tags) IHunk->UnLoadHunk(tags) 
#if (defined(__STDC_VERSION__) && __STDC_VERSION__ >= 199901L) || (__GNUC__ >= 3)
#define UnLoadHunkTags(...) IHunk->UnLoadHunkTags(__VA_ARGS__) 
#elif (__GNUC__ == 2 && __GNUC_MINOR__ >= 95)
#define UnLoadHunkTags(...) IHunk->UnLoadHunkTags(## vargs) 
#endif

#endif /* INLINE4_HUNK_H */
