#ifndef INLINE4_ICONMODULE_H
#define INLINE4_ICONMODULE_H

/*
** This file was auto generated by idltool 51.8.
**
** It provides compatibility to OS3 style library
** calls by substituting functions.
**
** Do not edit manually.
*/

#ifndef EXEC_TYPES_H
#include <exec/types.h>
#endif
#ifndef EXEC_EXEC_H
#include <exec/exec.h>
#endif
#ifndef EXEC_INTERFACES_H
#include <exec/interfaces.h>
#endif

#ifndef WORKBENCH_WORKBENCH_H
#include <workbench/workbench.h>
#endif
#ifndef WORKBENCH_ICON_H
#include <workbench/icon.h>
#endif
#ifndef WORKBENCH_ICONMODULE_H
#include <workbench/iconmodule.h>
#endif

/* Inline macros for Interface "main" */
#define ModuleControlA(object, taglist) IIconModule->ModuleControlA(object, taglist)
#if (defined(__STDC_VERSION__) && __STDC_VERSION__ >= 199901L) || (__GNUC__ >= 3)
#define ModuleControl(...) IIconModule->ModuleControl(__VA_ARGS__)
#elif (__GNUC__ == 2 && __GNUC_MINOR__ >= 95)
#define ModuleControl(vargs...) IIconModule->ModuleControl(## vargs)
#endif
#define LoadIconA(name, icon, taglist) IIconModule->LoadIconA(name, icon, taglist)
#if (defined(__STDC_VERSION__) && __STDC_VERSION__ >= 199901L) || (__GNUC__ >= 3)
#define LoadIcon(name, ...) IIconModule->LoadIcon(name, __VA_ARGS__)
#elif (__GNUC__ == 2 && __GNUC_MINOR__ >= 95)
#define LoadIcon(name, vargs...) IIconModule->LoadIcon(name, ## vargs)
#endif
#define SaveIconA(name, icon, taglist) IIconModule->SaveIconA(name, icon, taglist)
#if (defined(__STDC_VERSION__) && __STDC_VERSION__ >= 199901L) || (__GNUC__ >= 3)
#define SaveIcon(name, ...) IIconModule->SaveIcon(name, __VA_ARGS__)
#elif (__GNUC__ == 2 && __GNUC_MINOR__ >= 95)
#define SaveIcon(name, vargs...) IIconModule->SaveIcon(name, ## vargs)
#endif
#define AllocIconDataA(icon, taglist) IIconModule->AllocIconDataA(icon, taglist)
#if (defined(__STDC_VERSION__) && __STDC_VERSION__ >= 199901L) || (__GNUC__ >= 3)
#define AllocIconData(...) IIconModule->AllocIconData(__VA_ARGS__)
#elif (__GNUC__ == 2 && __GNUC_MINOR__ >= 95)
#define AllocIconData(vargs...) IIconModule->AllocIconData(## vargs)
#endif
#define FreeIconDataA(icon, taglist) IIconModule->FreeIconDataA(icon, taglist)
#if (defined(__STDC_VERSION__) && __STDC_VERSION__ >= 199901L) || (__GNUC__ >= 3)
#define FreeIconData(...) IIconModule->FreeIconData(__VA_ARGS__)
#elif (__GNUC__ == 2 && __GNUC_MINOR__ >= 95)
#define FreeIconData(vargs...) IIconModule->FreeIconData(## vargs)
#endif
#define DupIconDataA(icon, taglist) IIconModule->DupIconDataA(icon, taglist)
#if (defined(__STDC_VERSION__) && __STDC_VERSION__ >= 199901L) || (__GNUC__ >= 3)
#define DupIconData(...) IIconModule->DupIconData(__VA_ARGS__)
#elif (__GNUC__ == 2 && __GNUC_MINOR__ >= 95)
#define DupIconData(vargs...) IIconModule->DupIconData(## vargs)
#endif
#define ScaleIconA(icon, isr, taglist) IIconModule->ScaleIconA(icon, isr, taglist)
#if (defined(__STDC_VERSION__) && __STDC_VERSION__ >= 199901L) || (__GNUC__ >= 3)
#define ScaleIcon(...) IIconModule->ScaleIcon(__VA_ARGS__)
#elif (__GNUC__ == 2 && __GNUC_MINOR__ >= 95)
#define ScaleIcon(vargs...) IIconModule->ScaleIcon(## vargs)
#endif

#endif /* INLINE4_ICONMODULE_H */
