#ifndef INLINE4_KEYMAP_H
#define INLINE4_KEYMAP_H

/*
** This file was auto generated by idltool 53.6.
**
** It provides compatibility to OS3 style library
** calls by substituting functions.
**
** Do not edit manually.
*/ 

#ifndef EXEC_TYPES_H
#include <exec/types.h>
#endif
#ifndef EXEC_EXEC_H
#include <exec/exec.h>
#endif
#ifndef EXEC_INTERFACES_H
#include <exec/interfaces.h>
#endif

#ifndef DEVICES_INPUTEVENT_H
#include <devices/inputevent.h>
#endif
#ifndef LIBRARIES_KEYMAP_H
#include <libraries/keymap.h>
#endif
#include <interfaces/keymap.h>

/* Inline macros for Interface "main" */
#define SetKeyMapDefault(keyMap) IKeymap->SetKeyMapDefault((keyMap)) 
#define AskKeyMapDefault() IKeymap->AskKeyMapDefault() 
#define MapRawKey(event, buffer, length, keyMap) IKeymap->MapRawKey((event), (buffer), (length), (keyMap)) 
#define MapANSI(string, count, buffer, length, keyMap) IKeymap->MapANSI((string), (count), (buffer), (length), (keyMap)) 
#define OpenKeyMapHandleA(filename, taglist) IKeymap->OpenKeyMapHandleA((filename), (taglist)) 
#if (defined(__STDC_VERSION__) && __STDC_VERSION__ >= 199901L) || (__GNUC__ >= 3)
#define OpenKeyMapHandle(...) IKeymap->OpenKeyMapHandle(__VA_ARGS__) 
#elif (__GNUC__ == 2 && __GNUC_MINOR__ >= 95)
#define OpenKeyMapHandle(vargs...) IKeymap->OpenKeyMapHandle(## vargs) 
#endif
#define CloseKeyMapHandle(handle) IKeymap->CloseKeyMapHandle((handle)) 
#define ObtainKeyMapInfoA(handle, taglist) IKeymap->ObtainKeyMapInfoA((handle), (taglist)) 
#if (defined(__STDC_VERSION__) && __STDC_VERSION__ >= 199901L) || (__GNUC__ >= 3)
#define ObtainKeyMapInfo(...) IKeymap->ObtainKeyMapInfo(__VA_ARGS__) 
#elif (__GNUC__ == 2 && __GNUC_MINOR__ >= 95)
#define ObtainKeyMapInfo(vargs...) IKeymap->ObtainKeyMapInfo(## vargs) 
#endif
#define ReleaseKeyMapInfoA(handle, taglist) IKeymap->ReleaseKeyMapInfoA((handle), (taglist)) 
#if (defined(__STDC_VERSION__) && __STDC_VERSION__ >= 199901L) || (__GNUC__ >= 3)
#define ReleaseKeyMapInfo(...) IKeymap->ReleaseKeyMapInfo(__VA_ARGS__) 
#elif (__GNUC__ == 2 && __GNUC_MINOR__ >= 95)
#define ReleaseKeyMapInfo(vargs...) IKeymap->ReleaseKeyMapInfo(## vargs) 
#endif
#define ObtainRawKeyInfoA(taglist) IKeymap->ObtainRawKeyInfoA((taglist)) 
#if (defined(__STDC_VERSION__) && __STDC_VERSION__ >= 199901L) || (__GNUC__ >= 3)
#define ObtainRawKeyInfo(...) IKeymap->ObtainRawKeyInfo(__VA_ARGS__) 
#elif (__GNUC__ == 2 && __GNUC_MINOR__ >= 95)
#define ObtainRawKeyInfo(...) IKeymap->ObtainRawKeyInfo(## vargs) 
#endif
#define KeyMapControlTagList(tags) IKeymap->KeyMapControlTagList((tags)) 
#if (defined(__STDC_VERSION__) && __STDC_VERSION__ >= 199901L) || (__GNUC__ >= 3)
#define KeyMapControlTags(...) IKeymap->KeyMapControlTags(__VA_ARGS__) 
#elif (__GNUC__ == 2 && __GNUC_MINOR__ >= 95)
#define KeyMapControlTags(...) IKeymap->KeyMapControlTags(## vargs) 
#endif

#endif /* INLINE4_KEYMAP_H */
