#ifndef INLINE4_LOWLEVEL_H
#define INLINE4_LOWLEVEL_H

/*
** This file was auto generated by idltool 51.8.
**
** It provides compatibility to OS3 style library
** calls by substituting functions.
**
** Do not edit manually.
*/ 

#ifndef EXEC_TYPES_H
#include <exec/types.h>
#endif
#ifndef EXEC_EXEC_H
#include <exec/exec.h>
#endif
#ifndef EXEC_INTERFACES_H
#include <exec/interfaces.h>
#endif

#ifndef EXEC_INTERRUPTS_H
#include <exec/interrupts.h>
#endif
#ifndef UTILITY_TAGITEM_H
#include <utility/tagitem.h>
#endif
#ifndef DEVICES_TIMER_H
#include <devices/timer.h>
#endif
#ifndef LIBRARIES_LOWLEVEL_H
#include <libraries/lowlevel.h>
#endif

/* Inline macros for Interface "main" */
#define ReadJoyPort(port) ILowLevel->ReadJoyPort(port) 
#define GetLanguageSelection() ILowLevel->GetLanguageSelection() 
#define GetKey() ILowLevel->GetKey() 
#define QueryKeys(queryArray, arraySize) ILowLevel->QueryKeys(queryArray, arraySize) 
#define AddKBInt(intRoutine, intData) ILowLevel->AddKBInt(intRoutine, intData) 
#define RemKBInt(intHandle) ILowLevel->RemKBInt(intHandle) 
#define SystemControlA(tagList) ILowLevel->SystemControlA(tagList) 
#if (defined(__STDC_VERSION__) && __STDC_VERSION__ >= 199901L) || (__GNUC__ >= 3)
#define SystemControl(...) ILowLevel->SystemControl(__VA_ARGS__) 
#elif (__GNUC__ == 2 && __GNUC_MINOR__ >= 95)
#define SystemControl(...) ILowLevel->SystemControl(## vargs) 
#endif
#define AddTimerInt(intRoutine, intData) ILowLevel->AddTimerInt(intRoutine, intData) 
#define RemTimerInt(intHandle) ILowLevel->RemTimerInt(intHandle) 
#define StopTimerInt(intHandle) ILowLevel->StopTimerInt(intHandle) 
#define StartTimerInt(intHandle, timeInterval, continuous) ILowLevel->StartTimerInt(intHandle, timeInterval, continuous) 
#define ElapsedTime(context) ILowLevel->ElapsedTime(context) 
#define AddVBlankInt(intRoutine, intData) ILowLevel->AddVBlankInt(intRoutine, intData) 
#define RemVBlankInt(intHandle) ILowLevel->RemVBlankInt(intHandle) 
#define SetJoyPortAttrsA(portNumber, tagList) ILowLevel->SetJoyPortAttrsA(portNumber, tagList) 
#if (defined(__STDC_VERSION__) && __STDC_VERSION__ >= 199901L) || (__GNUC__ >= 3)
#define SetJoyPortAttrs(...) ILowLevel->SetJoyPortAttrs(__VA_ARGS__) 
#elif (__GNUC__ == 2 && __GNUC_MINOR__ >= 95)
#define SetJoyPortAttrs(vargs...) ILowLevel->SetJoyPortAttrs(## vargs) 
#endif

#endif /* INLINE4_LOWLEVEL_H */
