#ifndef INLINE4_PARTITION_H
#define INLINE4_PARTITION_H

/*
** This file was auto generated by idltool 51.8.
**
** It provides compatibility to OS3 style library
** calls by substituting functions.
**
** Do not edit manually.
*/ 

#ifndef EXEC_TYPES_H
#include <exec/types.h>
#endif
#ifndef EXEC_EXEC_H
#include <exec/exec.h>
#endif
#ifndef EXEC_INTERFACES_H
#include <exec/interfaces.h>
#endif

#ifndef INTUITION_CLASSES_H
#include <intuition/classes.h>
#endif

/* Inline macros for Interface "main" */
#define PARTITION_GetClass() IPartition->PARTITION_GetClass() 
#define AllocPartitionNodeA(last) IPartition->AllocPartitionNodeA(last) 
#if (defined(__STDC_VERSION__) && __STDC_VERSION__ >= 199901L) || (__GNUC__ >= 3)
#define AllocPartitionNode(...) IPartition->AllocPartitionNode(__VA_ARGS__) 
#elif (__GNUC__ == 2 && __GNUC_MINOR__ >= 95)
#define AllocPartitionNode(...) IPartition->AllocPartitionNode(## vargs) 
#endif
#define FreePartitionNode(last) IPartition->FreePartitionNode(last) 
#define SetPartitionNodeAttrsA(par1, last) IPartition->SetPartitionNodeAttrsA(par1, last) 
#if (defined(__STDC_VERSION__) && __STDC_VERSION__ >= 199901L) || (__GNUC__ >= 3)
#define SetPartitionNodeAttrs(...) IPartition->SetPartitionNodeAttrs(__VA_ARGS__) 
#elif (__GNUC__ == 2 && __GNUC_MINOR__ >= 95)
#define SetPartitionNodeAttrs(vargs...) IPartition->SetPartitionNodeAttrs(## vargs) 
#endif
#define GetPartitionNodeAttrsA(par1, last) IPartition->GetPartitionNodeAttrsA(par1, last) 
#if (defined(__STDC_VERSION__) && __STDC_VERSION__ >= 199901L) || (__GNUC__ >= 3)
#define GetPartitionNodeAttrs(...) IPartition->GetPartitionNodeAttrs(__VA_ARGS__) 
#elif (__GNUC__ == 2 && __GNUC_MINOR__ >= 95)
#define GetPartitionNodeAttrs(vargs...) IPartition->GetPartitionNodeAttrs(## vargs) 
#endif

#endif /* INLINE4_PARTITION_H */
