#ifndef INLINE4_POTGO_H
#define INLINE4_POTGO_H

/*
** This file was auto generated by idltool 51.8.
**
** It provides compatibility to OS3 style library
** calls by substituting functions.
**
** Do not edit manually.
*/ 

#ifndef EXEC_TYPES_H
#include <exec/types.h>
#endif
#ifndef EXEC_EXEC_H
#include <exec/exec.h>
#endif
#ifndef EXEC_INTERFACES_H
#include <exec/interfaces.h>
#endif


/* Inline macros for Interface "main" */
#define AllocPotBits(bits) IPotgo->AllocPotBits(bits) 
#define FreePotBits(bits) IPotgo->FreePotBits(bits) 
#define WritePotgo(word, mask) IPotgo->WritePotgo(word, mask) 

#endif /* INLINE4_POTGO_H */
