#ifndef INLINE4_RADIOBUTTON_H
#define INLINE4_RADIOBUTTON_H

/*
** This file was auto generated by idltool 51.8.
**
** It provides compatibility to OS3 style library
** calls by substituting functions.
**
** Do not edit manually.
*/ 

#ifndef EXEC_TYPES_H
#include <exec/types.h>
#endif
#ifndef EXEC_EXEC_H
#include <exec/exec.h>
#endif
#ifndef EXEC_INTERFACES_H
#include <exec/interfaces.h>
#endif

#ifndef INTUITION_INTUITION_H
#include <intuition/intuition.h>
#endif
#ifndef INTUITION_CLASSES_H
#include <intuition/classes.h>
#endif

/* Inline macros for Interface "main" */
#define RADIOBUTTON_GetClass() IRadioButton->RADIOBUTTON_GetClass() 
#define AllocRadioButtonNodeA(columns, tags) IRadioButton->AllocRadioButtonNodeA(columns, tags) 
#if (defined(__STDC_VERSION__) && __STDC_VERSION__ >= 199901L) || (__GNUC__ >= 3)
#define AllocRadioButtonNode(...) IRadioButton->AllocRadioButtonNode(__VA_ARGS__) 
#elif (__GNUC__ == 2 && __GNUC_MINOR__ >= 95)
#define AllocRadioButtonNode(vargs...) IRadioButton->AllocRadioButtonNode(## vargs) 
#endif
#define FreeRadioButtonNode(node) IRadioButton->FreeRadioButtonNode(node) 
#define SetRadioButtonNodeAttrsA(node, tags) IRadioButton->SetRadioButtonNodeAttrsA(node, tags) 
#if (defined(__STDC_VERSION__) && __STDC_VERSION__ >= 199901L) || (__GNUC__ >= 3)
#define SetRadioButtonNodeAttrs(...) IRadioButton->SetRadioButtonNodeAttrs(__VA_ARGS__) 
#elif (__GNUC__ == 2 && __GNUC_MINOR__ >= 95)
#define SetRadioButtonNodeAttrs(vargs...) IRadioButton->SetRadioButtonNodeAttrs(## vargs) 
#endif
#define GetRadioButtonNodeAttrsA(node, tags) IRadioButton->GetRadioButtonNodeAttrsA(node, tags) 
#if (defined(__STDC_VERSION__) && __STDC_VERSION__ >= 199901L) || (__GNUC__ >= 3)
#define GetRadioButtonNodeAttrs(...) IRadioButton->GetRadioButtonNodeAttrs(__VA_ARGS__) 
#elif (__GNUC__ == 2 && __GNUC_MINOR__ >= 95)
#define GetRadioButtonNodeAttrs(vargs...) IRadioButton->GetRadioButtonNodeAttrs(## vargs) 
#endif

#endif /* INLINE4_RADIOBUTTON_H */
