#ifndef INLINE4_TIMEZONE_H
#define INLINE4_TIMEZONE_H

/*
** This file was auto generated by idltool 52.6.
**
** It provides compatibility to OS3 style library
** calls by substituting functions.
**
** Do not edit manually.
*/ 

#ifndef EXEC_TYPES_H
#include <exec/types.h>
#endif
#ifndef EXEC_EXEC_H
#include <exec/exec.h>
#endif
#ifndef EXEC_INTERFACES_H
#include <exec/interfaces.h>
#endif

#ifndef LIBRARIES_TIMEZONE_H
#include <libraries/timezone.h>
#endif
#include <interfaces/timezone.h>

/* Inline macros for Interface "main" */
#define GetTimezoneAttrsA(unused, taglist) ITimezone->GetTimezoneAttrsA((unused), (taglist)) 
#if (defined(__STDC_VERSION__) && __STDC_VERSION__ >= 199901L) || (__GNUC__ >= 3)
#define GetTimezoneAttrs(...) ITimezone->GetTimezoneAttrs(__VA_ARGS__) 
#elif (__GNUC__ == 2 && __GNUC_MINOR__ >= 95)
#define GetTimezoneAttrs(vargs...) ITimezone->GetTimezoneAttrs(## vargs) 
#endif
#define ParseZone(zone) ITimezone->ParseZone((zone)) 
#define GetUTCTime(dest) ITimezone->GetUTCTime((dest)) 
#define SetTimezoneAttrsA(unused, taglist) ITimezone->SetTimezoneAttrsA((unused), (taglist)) 
#if (defined(__STDC_VERSION__) && __STDC_VERSION__ >= 199901L) || (__GNUC__ >= 3)
#define SetTimezoneAttrs(...) ITimezone->SetTimezoneAttrs(__VA_ARGS__) 
#elif (__GNUC__ == 2 && __GNUC_MINOR__ >= 95)
#define SetTimezoneAttrs(vargs...) ITimezone->SetTimezoneAttrs(## vargs) 
#endif

#endif /* INLINE4_TIMEZONE_H */
