#ifndef INLINE4_TRANSLATOR_H
#define INLINE4_TRANSLATOR_H

/*
** This file was auto generated by idltool 53.35.
**
** It provides compatibility to OS3 style library
** calls by substituting functions.
**
** Do not edit manually.
*/ 

#ifndef EXEC_TYPES_H
#include <exec/types.h>
#endif
#ifndef EXEC_EXEC_H
#include <exec/exec.h>
#endif
#ifndef EXEC_INTERFACES_H
#include <exec/interfaces.h>
#endif

#include <interfaces/translator.h>

/* No inline4 macros are defined here. */

#define Translate(inputString, inputLength, outputBuffer, bufferSize) ITranslator->Translate(inputString, inputLength, outputBuffer, bufferSize)

#endif /* INLINE4_TRANSLATOR_H */
