#ifndef INLINE4_USBFD_H
#define INLINE4_USBFD_H

/*
** This file was auto generated by idltool 53.6.
**
** It provides compatibility to OS3 style library
** calls by substituting functions.
**
** Do not edit manually.
*/ 

#ifndef EXEC_TYPES_H
#include <exec/types.h>
#endif
#ifndef EXEC_EXEC_H
#include <exec/exec.h>
#endif
#ifndef EXEC_INTERFACES_H
#include <exec/interfaces.h>
#endif

#include <interfaces/usbfd.h>

/* Inline macros for Interface "main" */
#define USBFDGetAttrsA(taglist) IUSBFD->USBFDGetAttrsA((taglist)) 
#if (defined(__STDC_VERSION__) && __STDC_VERSION__ >= 199901L) || (__GNUC__ >= 3)
#define USBFDGetAttrs(...) IUSBFD->USBFDGetAttrs(__VA_ARGS__) 
#elif (__GNUC__ == 2 && __GNUC_MINOR__ >= 95)
#define USBFDGetAttrs(...) IUSBFD->USBFDGetAttrs(## vargs) 
#endif
#define USBFDRunFunction(startmsg) IUSBFD->USBFDRunFunction((startmsg)) 
#define USBFDRunInterface(startmsg) IUSBFD->USBFDRunInterface((startmsg)) 

#endif /* INLINE4_USBFD_H */
