#ifndef RAWIMAGE_MCC_H
#define RAWIMAGE_MCC_H

#ifndef LIBRARIES_IFFPARSE_H
#include <libraries/iffparse.h>
#endif

#define MUIC_Rawimage	"Rawimage.mcc"
#define RawimageObject	MUI_NewObject(MUIC_Rawimage

struct MUI_RawimageData
{
	ULONG ri_Width;
	ULONG ri_Height;
	ULONG ri_Format;
	ULONG ri_Size;

	#if (__STDC_VERSION__ >= 199901L)
	ULONG ri_Data[];
	#elif (defined(__GNUC__))
	ULONG ri_Data[0];
	#else
	#error COmpiler needs to support 0-length arrays
	#endif
};

#define RAWIMAGE_PIXELFORMAT_ARGB 0
#define RAWIMAGE_PIXELFORMAT_RGB  1
#define RAWIMAGE_PIXELFORMAT_RGBA 2

#define RAWIMAGE_COMPRESSOR_RAW   0                          
#define RAWIMAGE_COMPRESSOR_BZ2   MAKE_ID('B','Z','2',0x0)
#define RAWIMAGE_COMPRESSOR_Z     MAKE_ID('Z',0x0,0x0,0x0)
#define RAWIMAGE_COMPRESSOR_RLE   MAKE_ID('R','L','E',0x0)
#define RAWIMAGE_COMPRESSOR_LZMA  MAKE_ID('L','Z','M',0x0)

#define RAWIMAGE_FORMAT(_cmpr,_pxf) (RAWIMAGE_COMPRESSOR_##_cmpr|RAWIMAGE_PIXELFORMAT_##_pxf)

#define RAWIMAGE_FORMAT_RAW_ARGB_ID   RAWIMAGE_FORMAT(RAW, ARGB)
#define RAWIMAGE_FORMAT_RAW_RGB_ID    RAWIMAGE_FORMAT(RAW, RGB)
#define RAWIMAGE_FORMAT_RAW_RGBA_ID   RAWIMAGE_FORMAT(RAW, RGBA)

#define RAWIMAGE_FORMAT_BZ2_ARGB_ID   RAWIMAGE_FORMAT(BZ2, ARGB)
#define RAWIMAGE_FORMAT_BZ2_RGB_ID    RAWIMAGE_FORMAT(BZ2, RGB)
#define RAWIMAGE_FORMAT_BZ2_RGBA_ID   RAWIMAGE_FORMAT(BZ2, RGBA)

#define RAWIMAGE_FORMAT_Z_ARGB_ID     RAWIMAGE_FORMAT(Z, ARGB)
#define RAWIMAGE_FORMAT_Z_RGB_ID      RAWIMAGE_FORMAT(Z, RGB)
#define RAWIMAGE_FORMAT_Z_RGBA_ID     RAWIMAGE_FORMAT(Z, RGBA)

#define RAWIMAGE_FORMAT_RLE_ARGB_ID   RAWIMAGE_FORMAT(RLE, ARGB)
#define RAWIMAGE_FORMAT_RLE_RGB_ID    RAWIMAGE_FORMAT(RLE, RGB)
#define RAWIMAGE_FORMAT_RLE_RGBA_ID   RAWIMAGE_FORMAT(RLE, RGBA)

#define RAWIMAGE_FORMAT_LZMA_ARGB_ID  RAWIMAGE_FORMAT(LZMA, ARGB)
#define RAWIMAGE_FORMAT_LZMA_RGB_ID   RAWIMAGE_FORMAT(LZMA, RGB)
#define RAWIMAGE_FORMAT_LZMA_RGBA_ID  RAWIMAGE_FORMAT(LZMA, RGBA)

#define MUIA_Rawimage_Data 0xfed10014 // ISG, struct MUI_RawimageData *

#endif /* RAWIMAGE_MCC_H */
