# Docker Image for PPC AmigaOS 4 cross compiler

FROM amigadev/crosstools:ppc-amigaos

COPY ./amigaos4/sdk/ /tools/

RUN ln -s /tools/ /opt/amiga

WORKDIR /work

CMD exec /bin/bash -c "trap : TERM INT; sleep infinity & wait"