# Docker Image for PPC AmigaOS 4 cross compiler

FROM amigadev/crosstools:ppc-amigaos

COPY ./ppc-amigaos /tools/ppc-amigaos

RUN rm -dr /tools/ppc-amigaos/SDK/Documentation
RUN rm -dr /tools/ppc-amigaos/SDK/Examples
RUN rm -dr /tools/ppc-amigaos/SDK/Tools
RUN rm -dr /tools/ppc-amigaos/SDK/*.pdf*

WORKDIR /work

CMD exec /bin/bash -c "trap : TERM INT; sleep infinity & wait"