# Docker Image for PPC MorphOS cross compiler

FROM amigadev/crosstools:ppc-morphos

COPY ./ppc-morphos /tools/ppc-morphos

# RUN rm -dr /tools/ppc-morphos/SDK/Documentation
# RUN rm -dr /tools/ppc-morphos/SDK/Examples
# RUN rm -dr /tools/ppc-morphos/SDK/Tools
# RUN rm -dr /tools/ppc-morphos/SDK/*.pdf*
RUN ln -s /tools/ /opt/amiga

WORKDIR /work

CMD exec /bin/bash -c "trap : TERM INT; sleep infinity & wait"