# Docker Image for m68k AmigaOS 3.2 cross compiler

FROM amigadev/crosstools:m68k-amigaos

COPY ./m68k-amigaos /tools/m68k-amigaos

RUN rm -dr /tools/m68k-amigaos/Autodocs
RUN rm -dr /tools/m68k-amigaos/doc
RUN rm -dr /tools/m68k-amigaos/guide

WORKDIR /work

CMD exec /bin/bash -c "trap : TERM INT; sleep infinity & wait"