# Docker Image for PPC AmigaOS 4 cross compiler

FROM walkero/amigagccondocker:os4-gcc11

COPY ./amigaos4/sdk/ /opt/

RUN ln -s /opt/ /opt/amiga

WORKDIR /work

CMD exec /bin/bash -c "trap : TERM INT; sleep infinity & wait"