# Docker Image for m68k AmigaOS 3.2 cross compiler

FROM amigadev/crosstools:m68k-amigaos

COPY ./amigaos3/sdk/ /tools/

RUN ln -s /tools/ /opt/amiga

# Remove the original NDK translator includes as we are using the updated one
RUN rm /tools/m68k-amigaos/ndk-include/inline/translator.h
RUN rm /tools/m68k-amigaos/ndk-include/clib/translator_protos.h

WORKDIR /work

CMD exec /bin/bash -c "trap : TERM INT; sleep infinity & wait"