# Docker Image for PPC MorphOS cross compiler

FROM amigadev/crosstools:ppc-morphos

COPY ./morphos/sdk/ /tools/

RUN ln -s /tools/ /opt/amiga

WORKDIR /work

CMD exec /bin/bash -c "trap : TERM INT; sleep infinity & wait"