#ifndef RESOURCES_BATTMEMBITSSHARED_H
#define RESOURCES_BATTMEMBITSSHARED_H

/*
	battmem shared bits

	Copyright © 2002 The MorphOS Development Team, All Rights Reserved.
*/


#define BATTMEM_SHARED_AMNESIA_ADDR   64
#define BATTMEM_SHARED_AMNESIA_LEN    1

#define BATTMEM_SCSI_HOST_ID_ADDR     65
#define BATTMEM_SCSI_HOST_ID_LEN      3

#define BATTMEM_SCSI_SYNC_XFER_ADDR   68
#define BATTMEM_SCSI_SYNC_XFER_LEN    1

#define BATTMEM_SCSI_FAST_SYNC_ADDR   69
#define BATTMEM_SCSI_FAST_SYNC_LEN    1

#define BATTMEM_SCSI_TAG_QUEUES_ADDR  70
#define BATTMEM_SCSI_TAG_QUEUES_LEN   1


#endif /* RESOURCES_BATTMEMBITSSHARED_H */
