#ifndef INLINE4_AHI_SUB_H
#define INLINE4_AHI_SUB_H

/*
** This file was auto generated by idltool 53.7.
**
** It provides compatibility to OS3 style library
** calls by substituting functions.
**
** Do not edit manually.
*/ 

#ifndef EXEC_TYPES_H
#include <exec/types.h>
#endif
#ifndef EXEC_EXEC_H
#include <exec/exec.h>
#endif
#ifndef EXEC_INTERFACES_H
#include <exec/interfaces.h>
#endif

#ifndef EXEC_LIBRARIES_H
#include <exec/libraries.h>
#endif
#ifndef UTILITY_TAGITEM_H
#include <utility/tagitem.h>
#endif
#ifndef LIBRARIES_AHI_SUB_H
#include <libraries/ahi_sub.h>
#endif
#include <interfaces/ahi_sub.h>

/* Inline macros for Interface "main" */
#define AHIsub_AllocAudio(tagList, AudioCtrl) IAHIsub->AHIsub_AllocAudio((tagList), (AudioCtrl)) 
#define AHIsub_FreeAudio(AudioCtrl) IAHIsub->AHIsub_FreeAudio((AudioCtrl)) 
#define AHIsub_Disable(AudioCtrl) IAHIsub->AHIsub_Disable((AudioCtrl)) 
#define AHIsub_Enable(AudioCtrl) IAHIsub->AHIsub_Enable((AudioCtrl)) 
#define AHIsub_Start(Flags, AudioCtrl) IAHIsub->AHIsub_Start((Flags), (AudioCtrl)) 
#define AHIsub_Update(Flags, AudioCtrl) IAHIsub->AHIsub_Update((Flags), (AudioCtrl)) 
#define AHIsub_Stop(Flags, AudioCtrl) IAHIsub->AHIsub_Stop((Flags), (AudioCtrl)) 
#define AHIsub_SetVol(Channel, Volume, Pan, AudioCtrl, Flags) IAHIsub->AHIsub_SetVol((Channel), (Volume), (Pan), (AudioCtrl), (Flags)) 
#define AHIsub_SetFreq(Channel, Freq, AudioCtrl, Flags) IAHIsub->AHIsub_SetFreq((Channel), (Freq), (AudioCtrl), (Flags)) 
#define AHIsub_SetSound(Channel, Sound, Offset, Length, AudioCtrl, Flags) IAHIsub->AHIsub_SetSound((Channel), (Sound), (Offset), (Length), (AudioCtrl), (Flags)) 
#define AHIsub_SetEffect(Effect, AudioCtrl) IAHIsub->AHIsub_SetEffect((Effect), (AudioCtrl)) 
#define AHIsub_LoadSound(Sound, Type, Info, AudioCtrl) IAHIsub->AHIsub_LoadSound((Sound), (Type), (Info), (AudioCtrl)) 
#define AHIsub_UnloadSound(Sound, Audioctrl) IAHIsub->AHIsub_UnloadSound((Sound), (Audioctrl)) 
#define AHIsub_GetAttr(Attribute, Argument, DefValue, tagList, AudioCtrl) IAHIsub->AHIsub_GetAttr((Attribute), (Argument), (DefValue), (tagList), (AudioCtrl)) 
#define AHIsub_HardwareControl(Attribute, Argument, AudioCtrl) IAHIsub->AHIsub_HardwareControl((Attribute), (Argument), (AudioCtrl)) 

#endif /* INLINE4_AHI_SUB_H */
