#ifndef INLINE4_APPLICATION_H
#define INLINE4_APPLICATION_H

/*
** This file was auto generated by idltool 51.8.
**
** It provides compatibility to OS3 style library
** calls by substituting functions.
**
** Do not edit manually.
*/ 

#ifndef EXEC_TYPES_H
#include <exec/types.h>
#endif
#ifndef EXEC_EXEC_H
#include <exec/exec.h>
#endif
#ifndef EXEC_INTERFACES_H
#include <exec/interfaces.h>
#endif

#ifndef EXEC_LIBRARIES_H
#include <exec/libraries.h>
#endif
#ifndef LIBRARIES_APPLICATION_H
#include <libraries/application.h>
#endif

/* Inline macros for Interface "application" */
#define NotifyA(appID, tags) IApplication->NotifyA(appID, tags)
#if (defined(__STDC_VERSION__) && __STDC_VERSION__ >= 199901L) || (__GNUC__ >= 3)
#define Notify(...) IApplication->Notify(__VA_ARGS__)
#elif (__GNUC__ == 2 && __GNUC_MINOR__ >= 95)
#define Notify(vargs...) IApplication->Notify(## vargs)
#endif
#define SetAppLibAttrsA(tags) IApplication->SetAppLibAttrsA(tags) 
#if (defined(__STDC_VERSION__) && __STDC_VERSION__ >= 199901L) || (__GNUC__ >= 3)
#define SetAppLibAttrs(...) IApplication->SetAppLibAttrs(__VA_ARGS__) 
#elif (__GNUC__ == 2 && __GNUC_MINOR__ >= 95)
#define SetAppLibAttrs(...) IApplication->SetAppLibAttrs(## vargs) 
#endif
#define GetAppLibAttrsA(tags) IApplication->GetAppLibAttrsA(tags) 
#if (defined(__STDC_VERSION__) && __STDC_VERSION__ >= 199901L) || (__GNUC__ >= 3)
#define GetAppLibAttrs(...) IApplication->GetAppLibAttrs(__VA_ARGS__) 
#elif (__GNUC__ == 2 && __GNUC_MINOR__ >= 95)
#define GetAppLibAttrs(...) IApplication->GetAppLibAttrs(## vargs) 
#endif
#define RegisterApplicationA(appName, tags) IApplication->RegisterApplicationA(appName, tags) 
#if (defined(__STDC_VERSION__) && __STDC_VERSION__ >= 199901L) || (__GNUC__ >= 3)
#define RegisterApplication(...) IApplication->RegisterApplication(__VA_ARGS__) 
#elif (__GNUC__ == 2 && __GNUC_MINOR__ >= 95)
#define RegisterApplication(vargs...) IApplication->RegisterApplication(## vargs) 
#endif
#define UnregisterApplicationA(appID, tags) IApplication->UnregisterApplicationA(appID, tags) 
#if (defined(__STDC_VERSION__) && __STDC_VERSION__ >= 199901L) || (__GNUC__ >= 3)
#define UnregisterApplication(...) IApplication->UnregisterApplication(__VA_ARGS__) 
#elif (__GNUC__ == 2 && __GNUC_MINOR__ >= 95)
#define UnregisterApplication(vargs...) IApplication->UnregisterApplication(## vargs) 
#endif
#define SetApplicationAttrsA(appID, tags) IApplication->SetApplicationAttrsA(appID, tags) 
#if (defined(__STDC_VERSION__) && __STDC_VERSION__ >= 199901L) || (__GNUC__ >= 3)
#define SetApplicationAttrs(...) IApplication->SetApplicationAttrs(__VA_ARGS__) 
#elif (__GNUC__ == 2 && __GNUC_MINOR__ >= 95)
#define SetApplicationAttrs(vargs...) IApplication->SetApplicationAttrs(## vargs) 
#endif
#define GetApplicationAttrsA(appID, tags) IApplication->GetApplicationAttrsA(appID, tags) 
#if (defined(__STDC_VERSION__) && __STDC_VERSION__ >= 199901L) || (__GNUC__ >= 3)
#define GetApplicationAttrs(...) IApplication->GetApplicationAttrs(__VA_ARGS__) 
#elif (__GNUC__ == 2 && __GNUC_MINOR__ >= 95)
#define GetApplicationAttrs(vargs...) IApplication->GetApplicationAttrs(## vargs) 
#endif
#define FindApplicationA(tags) IApplication->FindApplicationA(tags) 
#if (defined(__STDC_VERSION__) && __STDC_VERSION__ >= 199901L) || (__GNUC__ >= 3)
#define FindApplication(...) IApplication->FindApplication(__VA_ARGS__) 
#elif (__GNUC__ == 2 && __GNUC_MINOR__ >= 95)
#define FindApplication(...) IApplication->FindApplication(## vargs) 
#endif
#define LockApplicationIcon(appID) IApplication->LockApplicationIcon(appID) 
#define UnlockApplicationIcon(appID) IApplication->UnlockApplicationIcon(appID) 
#define GetApplicationList() IApplication->GetApplicationList() 
#define FreeApplicationList(list) IApplication->FreeApplicationList(list) 
#define SendApplicationMsg(senderAppID, receiverAppID, msg, msgType) IApplication->SendApplicationMsg(senderAppID, receiverAppID, msg, msgType) 
/* Inline macros for Interface "prefsobjects" */
#define BeginDeserialization(info) IPrefsObjects->BeginDeserialization(info) 
#define PrefsBaseObjectA(obj, error, tags) IPrefsObjects->PrefsBaseObjectA(obj, error, tags) 
#if (defined(__STDC_VERSION__) && __STDC_VERSION__ >= 199901L) || (__GNUC__ >= 3)
#define PrefsBaseObject(obj, ...) IPrefsObjects->PrefsBaseObject(obj, __VA_ARGS__) 
#elif (__GNUC__ == 2 && __GNUC_MINOR__ >= 95)
#define PrefsBaseObject(obj, vargs...) IPrefsObjects->PrefsBaseObject(obj, ## vargs) 
#endif
#define PrefsStringA(obj, error, tags) IPrefsObjects->PrefsStringA(obj, error, tags) 
#if (defined(__STDC_VERSION__) && __STDC_VERSION__ >= 199901L) || (__GNUC__ >= 3)
#define PrefsString(obj, ...) IPrefsObjects->PrefsString(obj, __VA_ARGS__) 
#elif (__GNUC__ == 2 && __GNUC_MINOR__ >= 95)
#define PrefsString(obj, vargs...) IPrefsObjects->PrefsString(obj, ## vargs) 
#endif
#define PrefsNumberA(obj, error, tags) IPrefsObjects->PrefsNumberA(obj, error, tags) 
#if (defined(__STDC_VERSION__) && __STDC_VERSION__ >= 199901L) || (__GNUC__ >= 3)
#define PrefsNumber(obj, ...) IPrefsObjects->PrefsNumber(obj, __VA_ARGS__) 
#elif (__GNUC__ == 2 && __GNUC_MINOR__ >= 95)
#define PrefsNumber(obj, vargs...) IPrefsObjects->PrefsNumber(obj, ## vargs) 
#endif
#define PrefsDateA(obj, error, tags) IPrefsObjects->PrefsDateA(obj, error, tags) 
#if (defined(__STDC_VERSION__) && __STDC_VERSION__ >= 199901L) || (__GNUC__ >= 3)
#define PrefsDate(obj, ...) IPrefsObjects->PrefsDate(obj, __VA_ARGS__) 
#elif (__GNUC__ == 2 && __GNUC_MINOR__ >= 95)
#define PrefsDate(obj, vargs...) IPrefsObjects->PrefsDate(obj, ## vargs) 
#endif
#define PrefsBinaryA(obj, error, tags) IPrefsObjects->PrefsBinaryA(obj, error, tags) 
#if (defined(__STDC_VERSION__) && __STDC_VERSION__ >= 199901L) || (__GNUC__ >= 3)
#define PrefsBinary(obj, ...) IPrefsObjects->PrefsBinary(obj, __VA_ARGS__) 
#elif (__GNUC__ == 2 && __GNUC_MINOR__ >= 95)
#define PrefsBinary(obj, vargs...) IPrefsObjects->PrefsBinary(obj, ## vargs) 
#endif
#define PrefsDictionaryA(obj, error, tags) IPrefsObjects->PrefsDictionaryA(obj, error, tags) 
#if (defined(__STDC_VERSION__) && __STDC_VERSION__ >= 199901L) || (__GNUC__ >= 3)
#define PrefsDictionary(obj, ...) IPrefsObjects->PrefsDictionary(obj, __VA_ARGS__) 
#elif (__GNUC__ == 2 && __GNUC_MINOR__ >= 95)
#define PrefsDictionary(obj, vargs...) IPrefsObjects->PrefsDictionary(obj, ## vargs) 
#endif
#define PrefsArrayA(obj, error, tags) IPrefsObjects->PrefsArrayA(obj, error, tags) 
#if (defined(__STDC_VERSION__) && __STDC_VERSION__ >= 199901L) || (__GNUC__ >= 3)
#define PrefsArray(obj, ...) IPrefsObjects->PrefsArray(obj, __VA_ARGS__) 
#elif (__GNUC__ == 2 && __GNUC_MINOR__ >= 95)
#define PrefsArray(obj, vargs...) IPrefsObjects->PrefsArray(obj, ## vargs) 
#endif
#define DictSetObjectForKey(dict, obj, key) IPrefsObjects->DictSetObjectForKey(dict, obj, key) 
#define DictGetObjectForKey(dict, key) IPrefsObjects->DictGetObjectForKey(dict, key) 
#define DictGetStringForKey(dict, key, defStr) IPrefsObjects->DictGetStringForKey(dict, key, defStr) 
#define DictGetIntegerForKey(dict, key, defInt) IPrefsObjects->DictGetIntegerForKey(dict, key, defInt) 
#define DictGetBoolForKey(dict, key, defBool) IPrefsObjects->DictGetBoolForKey(dict, key, defBool) 
#define DictGetOptionForKey(dict, key, optionsTable, defaultOption) IPrefsObjects->DictGetOptionForKey(dict, key, optionsTable, defaultOption) 
#define ReadPrefsA(dict, tags) IPrefsObjects->ReadPrefsA(dict, tags) 
#if (defined(__STDC_VERSION__) && __STDC_VERSION__ >= 199901L) || (__GNUC__ >= 3)
#define ReadPrefs(...) IPrefsObjects->ReadPrefs(__VA_ARGS__) 
#elif (__GNUC__ == 2 && __GNUC_MINOR__ >= 95)
#define ReadPrefs(vargs...) IPrefsObjects->ReadPrefs(## vargs) 
#endif
#define WritePrefsA(dict, tags) IPrefsObjects->WritePrefsA(dict, tags) 
#if (defined(__STDC_VERSION__) && __STDC_VERSION__ >= 199901L) || (__GNUC__ >= 3)
#define WritePrefs(...) IPrefsObjects->WritePrefs(__VA_ARGS__) 
#elif (__GNUC__ == 2 && __GNUC_MINOR__ >= 95)
#define WritePrefs(vargs...) IPrefsObjects->WritePrefs(## vargs) 
#endif

#endif /* INLINE4_APPLICATION_H */
