#ifndef INLINE4_CONSOLE_H
#define INLINE4_CONSOLE_H

/*
** This file was auto generated by idltool 51.8.
**
** It provides compatibility to OS3 style library
** calls by substituting functions.
**
** Do not edit manually.
*/ 

#ifndef EXEC_TYPES_H
#include <exec/types.h>
#endif
#ifndef EXEC_EXEC_H
#include <exec/exec.h>
#endif
#ifndef EXEC_INTERFACES_H
#include <exec/interfaces.h>
#endif

#ifndef EXEC_LIBRARIES_H
#include <exec/libraries.h>
#endif
#ifndef DEVICES_INPUTEVENT_H
#include <devices/inputevent.h>
#endif
#ifndef DEVICES_KEYMAP_H
#include <devices/keymap.h>
#endif

/* Inline macros for Interface "main" */
#define CDInputHandler(events, consoleDevice) IConsole->CDInputHandler(events, consoleDevice) 
#define RawKeyConvert(events, buffer, length, keyMap) IConsole->RawKeyConvert(events, buffer, length, keyMap) 

#endif /* INLINE4_CONSOLE_H */
