#ifndef INLINE4_CYBERGRAPHICS_H
#define INLINE4_CYBERGRAPHICS_H

/*
** This file was auto generated by idltool 53.1.
**
** It provides compatibility to OS3 style library
** calls by substituting functions.
**
** Do not edit manually.
*/ 

#ifndef EXEC_TYPES_H
#include <exec/types.h>
#endif
#ifndef EXEC_EXEC_H
#include <exec/exec.h>
#endif
#ifndef EXEC_INTERFACES_H
#include <exec/interfaces.h>
#endif

#ifndef EXEC_LISTS_H
#include <exec/lists.h>
#endif
#ifndef GRAPHICS_RASTPORT_H
#include <graphics/rastport.h>
#endif
#ifndef GRAPHICS_VIEW_H
#include <graphics/view.h>
#endif
#ifndef UTILITY_TAGITEM_H
#include <utility/tagitem.h>
#endif
#ifndef UTILITY_HOOKS_H
#include <utility/hooks.h>
#endif
#include <interfaces/cybergraphics.h>

/* Inline macros for Interface "main" */
#define IsCyberModeID(displayID) ICyberGfx->IsCyberModeID((displayID)) 
#define BestCModeIDTagList(BestModeIDTags) ICyberGfx->BestCModeIDTagList((BestModeIDTags)) 
#if (defined(__STDC_VERSION__) && __STDC_VERSION__ >= 199901L) || (__GNUC__ >= 3)
#define BestCModeIDTags(...) ICyberGfx->BestCModeIDTags(__VA_ARGS__) 
#elif (__GNUC__ == 2 && __GNUC_MINOR__ >= 95)
#define BestCModeIDTags(...) ICyberGfx->BestCModeIDTags(## vargs) 
#endif
#define CModeRequestTagList(ModeRequest, ModeRequestTags) ICyberGfx->CModeRequestTagList((ModeRequest), (ModeRequestTags)) 
#if (defined(__STDC_VERSION__) && __STDC_VERSION__ >= 199901L) || (__GNUC__ >= 3)
#define CModeRequestTags(...) ICyberGfx->CModeRequestTags(__VA_ARGS__) 
#elif (__GNUC__ == 2 && __GNUC_MINOR__ >= 95)
#define CModeRequestTags(vargs...) ICyberGfx->CModeRequestTags(## vargs) 
#endif
#define AllocCModeListTagList(ModeListTags) ICyberGfx->AllocCModeListTagList((ModeListTags)) 
#if (defined(__STDC_VERSION__) && __STDC_VERSION__ >= 199901L) || (__GNUC__ >= 3)
#define AllocCModeListTags(...) ICyberGfx->AllocCModeListTags(__VA_ARGS__) 
#elif (__GNUC__ == 2 && __GNUC_MINOR__ >= 95)
#define AllocCModeListTags(...) ICyberGfx->AllocCModeListTags(## vargs) 
#endif
#define FreeCModeList(ModeList) ICyberGfx->FreeCModeList((ModeList)) 
#define ScalePixelArray(srcRect, SrcW, SrcH, SrcMod, RastPort, DestX, DestY, DestW, DestH, SrcFormat) ICyberGfx->ScalePixelArray((srcRect), (SrcW), (SrcH), (SrcMod), (RastPort), (DestX), (DestY), (DestW), (DestH), (SrcFormat)) 
#define GetCyberMapAttr(CyberGfxBitmap, CyberAttrTag) ICyberGfx->GetCyberMapAttr((CyberGfxBitmap), (CyberAttrTag)) 
#define GetCyberIDAttr(CyberIDAttr, CyberDisplayModeID) ICyberGfx->GetCyberIDAttr((CyberIDAttr), (CyberDisplayModeID)) 
#define ReadRGBPixel(RastPort, x, y) ICyberGfx->ReadRGBPixel((RastPort), (x), (y)) 
#define WriteRGBPixel(RastPort, x, y, argb) ICyberGfx->WriteRGBPixel((RastPort), (x), (y), (argb)) 
#define ReadPixelArray(destRect, destX, destY, destMod, RastPort, SrcX, SrcY, SizeX, SizeY, DestFormat) ICyberGfx->ReadPixelArray((destRect), (destX), (destY), (destMod), (RastPort), (SrcX), (SrcY), (SizeX), (SizeY), (DestFormat)) 
#define WritePixelArray(srcRect, SrcX, SrcY, SrcMod, RastPort, DestX, DestY, SizeX, SizeY, SrcFormat) ICyberGfx->WritePixelArray((srcRect), (SrcX), (SrcY), (SrcMod), (RastPort), (DestX), (DestY), (SizeX), (SizeY), (SrcFormat)) 
#define MovePixelArray(SrcX, SrcY, RastPort, DestX, DestY, SizeX, SizeY) ICyberGfx->MovePixelArray((SrcX), (SrcY), (RastPort), (DestX), (DestY), (SizeX), (SizeY)) 
#define InvertPixelArray(RastPort, DestX, DestY, SizeX, SizeY) ICyberGfx->InvertPixelArray((RastPort), (DestX), (DestY), (SizeX), (SizeY)) 
#define FillPixelArray(RastPort, DestX, DestY, SizeX, SizeY, argb) ICyberGfx->FillPixelArray((RastPort), (DestX), (DestY), (SizeX), (SizeY), (argb)) 
#define DoCDrawMethodTagList(hook, RastPort, TagList) ICyberGfx->DoCDrawMethodTagList((hook), (RastPort), (TagList)) 
#if (defined(__STDC_VERSION__) && __STDC_VERSION__ >= 199901L) || (__GNUC__ >= 3)
#define DoCDrawMethodTags(hook, ...) ICyberGfx->DoCDrawMethodTags((hook), __VA_ARGS__) 
#elif (__GNUC__ == 2 && __GNUC_MINOR__ >= 95)
#define DoCDrawMethodTags(hook, vargs...) ICyberGfx->DoCDrawMethodTags(hook, ## vargs) 
#endif
#define CVideoCtrlTagList(ViewPort, TagList) ICyberGfx->CVideoCtrlTagList((ViewPort), (TagList)) 
#if (defined(__STDC_VERSION__) && __STDC_VERSION__ >= 199901L) || (__GNUC__ >= 3)
#define CVideoCtrlTags(...) ICyberGfx->CVideoCtrlTags(__VA_ARGS__) 
#elif (__GNUC__ == 2 && __GNUC_MINOR__ >= 95)
#define CVideoCtrlTags(vargs...) ICyberGfx->CVideoCtrlTags(## vargs) 
#endif
#define LockBitMapTagList(BitMap, TagList) ICyberGfx->LockBitMapTagList((BitMap), (TagList)) 
#if (defined(__STDC_VERSION__) && __STDC_VERSION__ >= 199901L) || (__GNUC__ >= 3)
#define LockBitMapTags(...) ICyberGfx->LockBitMapTags(__VA_ARGS__) 
#elif (__GNUC__ == 2 && __GNUC_MINOR__ >= 95)
#define LockBitMapTags(vargs...) ICyberGfx->LockBitMapTags(## vargs) 
#endif
#define UnLockBitMap(Handle) ICyberGfx->UnLockBitMap((Handle)) 
#define UnLockBitMapTagList(Handle, TagList) ICyberGfx->UnLockBitMapTagList((Handle), (TagList)) 
#if (defined(__STDC_VERSION__) && __STDC_VERSION__ >= 199901L) || (__GNUC__ >= 3)
#define UnLockBitMapTags(...) ICyberGfx->UnLockBitMapTags(__VA_ARGS__) 
#elif (__GNUC__ == 2 && __GNUC_MINOR__ >= 95)
#define UnLockBitMapTags(vargs...) ICyberGfx->UnLockBitMapTags(## vargs) 
#endif
#define ExtractColor(RastPort, BitMap, Colour, SrcX, SrcY, Width, Height) ICyberGfx->ExtractColor((RastPort), (BitMap), (Colour), (SrcX), (SrcY), (Width), (Height)) 
#define WriteLUTPixelArray(srcRect, SrcX, SrcY, SrcMod, RastPort, ColorTab, DestX, DestY, SizeX, SizeY, CTFormat) ICyberGfx->WriteLUTPixelArray((srcRect), (SrcX), (SrcY), (SrcMod), (RastPort), (ColorTab), (DestX), (DestY), (SizeX), (SizeY), (CTFormat)) 
#define WritePixelArrayAlpha(srcRect, SrcX, SrcY, SrcMod, RastPort, DestX, DestY, SizeX, SizeY, globalAlpha) ICyberGfx->WritePixelArrayAlpha((srcRect), (SrcX), (SrcY), (SrcMod), (RastPort), (DestX), (DestY), (SizeX), (SizeY), (globalAlpha)) 
#define BltTemplateAlpha(srcTemplate, SrcX, SrcY, RastPort, DestX, DestY, SizeX, SizeY) ICyberGfx->BltTemplateAlpha((srcTemplate), (SrcX), (SrcY), (RastPort), (DestX), (DestY), (SizeX), (SizeY)) 

#endif /* INLINE4_CYBERGRAPHICS_H */
