#ifndef INLINE4_DATATYPES_H
#define INLINE4_DATATYPES_H

/*
** This file was auto generated by idltool 51.8.
**
** It provides compatibility to OS3 style library
** calls by substituting functions.
**
** Do not edit manually.
*/ 

#ifndef EXEC_TYPES_H
#include <exec/types.h>
#endif
#ifndef EXEC_EXEC_H
#include <exec/exec.h>
#endif
#ifndef EXEC_INTERFACES_H
#include <exec/interfaces.h>
#endif

#ifndef EXEC_LISTS_H
#include <exec/lists.h>
#endif
#ifndef INTUITION_INTUITION_H
#include <intuition/intuition.h>
#endif
#ifndef INTUITION_CLASSES_H
#include <intuition/classes.h>
#endif
#ifndef INTUITION_CLASSUSR_H
#include <intuition/classusr.h>
#endif
#ifndef INTUITION_GADGETCLASS_H
#include <intuition/gadgetclass.h>
#endif
#ifndef UTILITY_TAGITEM_H
#include <utility/tagitem.h>
#endif
#ifndef DATATYPES_DATATYPESCLASS_H
#include <datatypes/datatypesclass.h>
#endif
#ifndef DATATYPES_DATATYPES_H
#include <datatypes/datatypes.h>
#endif
#ifndef REXX_STORAGE_H
#include <rexx/storage.h>
#endif

/* Inline macros for Interface "main" */
#define RLDispatch(rmsg, result) IDataTypes->RLDispatch(rmsg, result) 
#define ObtainDataTypeA(type, handle, attrs) IDataTypes->ObtainDataTypeA(type, handle, attrs) 
#if (defined(__STDC_VERSION__) && __STDC_VERSION__ >= 199901L) || (__GNUC__ >= 3)
#define ObtainDataType(type, ...) IDataTypes->ObtainDataType(type, __VA_ARGS__) 
#elif (__GNUC__ == 2 && __GNUC_MINOR__ >= 95)
#define ObtainDataType(type, vargs...) IDataTypes->ObtainDataType(type, ## vargs) 
#endif
#define ReleaseDataType(dt) IDataTypes->ReleaseDataType(dt) 
#define NewDTObjectA(name, attrs) IDataTypes->NewDTObjectA(name, attrs) 
#if (defined(__STDC_VERSION__) && __STDC_VERSION__ >= 199901L) || (__GNUC__ >= 3)
#define NewDTObject(...) IDataTypes->NewDTObject(__VA_ARGS__) 
#elif (__GNUC__ == 2 && __GNUC_MINOR__ >= 95)
#define NewDTObject(vargs...) IDataTypes->NewDTObject(## vargs) 
#endif
#define DisposeDTObject(o) IDataTypes->DisposeDTObject(o) 
#define SetDTAttrsA(o, win, req, attrs) IDataTypes->SetDTAttrsA(o, win, req, attrs) 
#if (defined(__STDC_VERSION__) && __STDC_VERSION__ >= 199901L) || (__GNUC__ >= 3)
#define SetDTAttrs(o, win, ...) IDataTypes->SetDTAttrs(o, win, __VA_ARGS__) 
#elif (__GNUC__ == 2 && __GNUC_MINOR__ >= 95)
#define SetDTAttrs(o, win, vargs...) IDataTypes->SetDTAttrs(o, win, ## vargs) 
#endif
#define GetDTAttrsA(o, attrs) IDataTypes->GetDTAttrsA(o, attrs) 
#if (defined(__STDC_VERSION__) && __STDC_VERSION__ >= 199901L) || (__GNUC__ >= 3)
#define GetDTAttrs(...) IDataTypes->GetDTAttrs(__VA_ARGS__) 
#elif (__GNUC__ == 2 && __GNUC_MINOR__ >= 95)
#define GetDTAttrs(vargs...) IDataTypes->GetDTAttrs(## vargs) 
#endif
#define AddDTObject(win, req, o, pos) IDataTypes->AddDTObject(win, req, o, pos) 
#define RefreshDTObjectA(o, win, req, attrs) IDataTypes->RefreshDTObjectA(o, win, req, attrs) 
#if (defined(__STDC_VERSION__) && __STDC_VERSION__ >= 199901L) || (__GNUC__ >= 3)
#define RefreshDTObjects(o, win, ...) IDataTypes->RefreshDTObjects(o, win, __VA_ARGS__) 
#elif (__GNUC__ == 2 && __GNUC_MINOR__ >= 95)
#define RefreshDTObjects(o, win, vargs...) IDataTypes->RefreshDTObjects(o, win, ## vargs) 
#endif
#if (defined(__STDC_VERSION__) && __STDC_VERSION__ >= 199901L) || (__GNUC__ >= 3)
#define RefreshDTObject(o, win, ...) IDataTypes->RefreshDTObject(o, win, __VA_ARGS__) 
#elif (__GNUC__ == 2 && __GNUC_MINOR__ >= 95)
#define RefreshDTObject(o, win, vargs...) IDataTypes->RefreshDTObject(o, win, ## vargs) 
#endif
#define DoAsyncLayout(o, gpl) IDataTypes->DoAsyncLayout(o, gpl) 
#define DoDTMethodA(o, win, req, msg) IDataTypes->DoDTMethodA(o, win, req, msg) 
#if (defined(__STDC_VERSION__) && __STDC_VERSION__ >= 199901L) || (__GNUC__ >= 3)
#define DoDTMethod(o, win, ...) IDataTypes->DoDTMethod(o, win, __VA_ARGS__) 
#elif (__GNUC__ == 2 && __GNUC_MINOR__ >= 95)
#define DoDTMethod(o, win, vargs...) IDataTypes->DoDTMethod(o, win, ## vargs) 
#endif
#define RemoveDTObject(win, o) IDataTypes->RemoveDTObject(win, o) 
#define GetDTMethods(object) IDataTypes->GetDTMethods(object) 
#define GetDTTriggerMethods(object) IDataTypes->GetDTTriggerMethods(object) 
#define PrintDTObjectA(o, w, r, msg) IDataTypes->PrintDTObjectA(o, w, r, msg) 
#if (defined(__STDC_VERSION__) && __STDC_VERSION__ >= 199901L) || (__GNUC__ >= 3)
#define PrintDTObject(o, w, ...) IDataTypes->PrintDTObject(o, w, __VA_ARGS__) 
#elif (__GNUC__ == 2 && __GNUC_MINOR__ >= 95)
#define PrintDTObject(o, w, vargs...) IDataTypes->PrintDTObject(o, w, ## vargs) 
#endif
#define ObtainDTDrawInfoA(o, attrs) IDataTypes->ObtainDTDrawInfoA(o, attrs) 
#if (defined(__STDC_VERSION__) && __STDC_VERSION__ >= 199901L) || (__GNUC__ >= 3)
#define ObtainDTDrawInfo(...) IDataTypes->ObtainDTDrawInfo(__VA_ARGS__) 
#elif (__GNUC__ == 2 && __GNUC_MINOR__ >= 95)
#define ObtainDTDrawInfo(vargs...) IDataTypes->ObtainDTDrawInfo(## vargs) 
#endif
#define DrawDTObjectA(rp, o, x, y, w, h, th, tv, attrs) IDataTypes->DrawDTObjectA(rp, o, x, y, w, h, th, tv, attrs) 
#if (defined(__STDC_VERSION__) && __STDC_VERSION__ >= 199901L) || (__GNUC__ >= 3)
#define DrawDTObject(rp, o, x, y, w, h, th, ...) IDataTypes->DrawDTObject(rp, o, x, y, w, h, th, __VA_ARGS__) 
#elif (__GNUC__ == 2 && __GNUC_MINOR__ >= 95)
#define DrawDTObject(rp, o, x, y, w, h, th, vargs...) IDataTypes->DrawDTObject(rp, o, x, y, w, h, th, ## vargs) 
#endif
#define ReleaseDTDrawInfo(o, handle) IDataTypes->ReleaseDTDrawInfo(o, handle) 
#define GetDTString(id) IDataTypes->GetDTString(id) 
#if (defined(__STDC_VERSION__) && __STDC_VERSION__ >= 199901L) || (__GNUC__ >= 3)
#define SaveDTObject(o, win, req, file, mode, ...) IDataTypes->SaveDTObject(o, win, req, file, mode, __VA_ARGS__) 
#elif (__GNUC__ == 2 && __GNUC_MINOR__ >= 95)
#define SaveDTObject(o, win, req, file, mode, vargs...) IDataTypes->SaveDTObject(o, win, req, file, mode, ## vargs) 
#endif
#if (defined(__STDC_VERSION__) && __STDC_VERSION__ >= 199901L) || (__GNUC__ >= 3)
#define DoDTDomain(o, win, req, rport, which, ...) IDataTypes->DoDTDomain(o, win, req, rport, which, __VA_ARGS__) 
#elif (__GNUC__ == 2 && __GNUC_MINOR__ >= 95)
#define DoDTDomain(o, win, req, rport, which, vargs...) IDataTypes->DoDTDomain(o, win, req, rport, which, ## vargs) 
#endif
#if (defined(__STDC_VERSION__) && __STDC_VERSION__ >= 199901L) || (__GNUC__ >= 3)
#define FindToolNode(...) IDataTypes->FindToolNode(__VA_ARGS__) 
#elif (__GNUC__ == 2 && __GNUC_MINOR__ >= 95)
#define FindToolNode(vargs...) IDataTypes->FindToolNode(## vargs) 
#endif
#if (defined(__STDC_VERSION__) && __STDC_VERSION__ >= 199901L) || (__GNUC__ >= 3)
#define LaunchTool(t, ...) IDataTypes->LaunchTool(t, __VA_ARGS__) 
#elif (__GNUC__ == 2 && __GNUC_MINOR__ >= 95)
#define LaunchTool(t, vargs...) IDataTypes->LaunchTool(t, ## vargs) 
#endif
#define LockDataType(dt) IDataTypes->LockDataType(dt) 
#define FindToolNodeA(tl, attrs) IDataTypes->FindToolNodeA(tl, attrs) 
#define LaunchToolA(t, project, attrs) IDataTypes->LaunchToolA(t, project, attrs) 
#define FindMethod(methods, searchmethodid) IDataTypes->FindMethod(methods, searchmethodid) 
#define FindTriggerMethod(dtm, command, method) IDataTypes->FindTriggerMethod(dtm, command, method) 
#define CopyDTMethods(methods, include, exclude) IDataTypes->CopyDTMethods(methods, include, exclude) 
#define CopyDTTriggerMethods(methods, include, exclude) IDataTypes->CopyDTTriggerMethods(methods, include, exclude) 
#define FreeDTMethods(methods) IDataTypes->FreeDTMethods(methods) 
#define GetDTTriggerMethodDataFlags(triggermethod) IDataTypes->GetDTTriggerMethodDataFlags(triggermethod) 
#define SaveDTObjectA(o, win, req, file, mode, saveicon, attrs) IDataTypes->SaveDTObjectA(o, win, req, file, mode, saveicon, attrs) 
#define StartDragSelect(o) IDataTypes->StartDragSelect(o) 
#define DoDTDomainA(o, win, req, rport, which, domain, attrs) IDataTypes->DoDTDomainA(o, win, req, rport, which, domain, attrs) 
#define datatypesPrivate001() IDataTypes->datatypesPrivate001() 
#define datatypesPrivate002() IDataTypes->datatypesPrivate002() 

#endif /* INLINE4_DATATYPES_H */
