#ifndef INLINE4_FLITE_H
#define INLINE4_FLITE_H

/*
** This file was auto generated by idltool 53.1.
**
** It provides compatibility to OS3 style library
** calls by substituting functions.
**
** Do not edit manually.
*/ 

#ifndef EXEC_TYPES_H
#include <exec/types.h>
#endif
#ifndef EXEC_EXEC_H
#include <exec/exec.h>
#endif
#ifndef EXEC_INTERFACES_H
#include <exec/interfaces.h>
#endif

#ifndef DEVICES_FLITE_H
#include <devices/flite.h>
#endif
#include <interfaces/flite.h>

/* Inline macros for Interface "main" */
#define OpenVoice(name) IFlite->OpenVoice((name)) 
#define CloseVoice(voice) IFlite->CloseVoice((voice)) 

#endif /* INLINE4_FLITE_H */
