#ifndef INLINE4_ICON_H
#define INLINE4_ICON_H

/*
** This file was auto generated by idltool 51.8.
**
** It provides compatibility to OS3 style library
** calls by substituting functions.
**
** Do not edit manually.
*/ 

#ifndef EXEC_TYPES_H
#include <exec/types.h>
#endif
#ifndef EXEC_EXEC_H
#include <exec/exec.h>
#endif
#ifndef EXEC_INTERFACES_H
#include <exec/interfaces.h>
#endif

#ifndef WORKBENCH_WORKBENCH_H
#include <workbench/workbench.h>
#endif
#ifndef DATATYPES_PICTURECLASS_H
#include <datatypes/pictureclass.h>
#endif

/* Inline macros for Interface "main" */
#define FreeFreeList(freelist) IIcon->FreeFreeList(freelist) 
#define AddFreeList(freelist, mem, size) IIcon->AddFreeList(freelist, mem, size) 
#define GetDiskObject(name) IIcon->GetDiskObject(name) 
#define PutDiskObject(name, diskobj) IIcon->PutDiskObject(name, diskobj) 
#define FreeDiskObject(diskobj) IIcon->FreeDiskObject(diskobj) 
#define FindToolType(toolTypeArray, typeName) IIcon->FindToolType(toolTypeArray, typeName) 
#define MatchToolValue(typeString, value) IIcon->MatchToolValue(typeString, value) 
#define BumpRevision(newname, oldname) IIcon->BumpRevision(newname, oldname) 
#define FreeAlloc(freelist, len, type) IIcon->FreeAlloc(freelist, len, type) 
#define GetDefDiskObject(type) IIcon->GetDefDiskObject(type) 
#define PutDefDiskObject(diskObject) IIcon->PutDefDiskObject(diskObject) 
#define GetDiskObjectNew(name) IIcon->GetDiskObjectNew(name) 
#define DeleteDiskObject(name) IIcon->DeleteDiskObject(name) 
#define FreeFree(fl, address) IIcon->FreeFree(fl, address) 
#define DupDiskObjectA(diskObject, tags) IIcon->DupDiskObjectA(diskObject, tags) 
#if (defined(__STDC_VERSION__) && __STDC_VERSION__ >= 199901L) || (__GNUC__ >= 3)
#define DupDiskObject(...) IIcon->DupDiskObject(__VA_ARGS__) 
#elif (__GNUC__ == 2 && __GNUC_MINOR__ >= 95)
#define DupDiskObject(vargs...) IIcon->DupDiskObject(## vargs) 
#endif
#define IconControlA(icon, tags) IIcon->IconControlA(icon, tags) 
#if (defined(__STDC_VERSION__) && __STDC_VERSION__ >= 199901L) || (__GNUC__ >= 3)
#define IconControl(...) IIcon->IconControl(__VA_ARGS__) 
#elif (__GNUC__ == 2 && __GNUC_MINOR__ >= 95)
#define IconControl(vargs...) IIcon->IconControl(## vargs) 
#endif
#define DrawIconStateA(rp, icon, label, leftOffset, topOffset, state, tags) IIcon->DrawIconStateA(rp, icon, label, leftOffset, topOffset, state, tags) 
#if (defined(__STDC_VERSION__) && __STDC_VERSION__ >= 199901L) || (__GNUC__ >= 3)
#define DrawIconState(rp, icon, label, leftOffset, topOffset, ...) IIcon->DrawIconState(rp, icon, label, leftOffset, topOffset, __VA_ARGS__) 
#elif (__GNUC__ == 2 && __GNUC_MINOR__ >= 95)
#define DrawIconState(rp, icon, label, leftOffset, topOffset, vargs...) IIcon->DrawIconState(rp, icon, label, leftOffset, topOffset, ## vargs) 
#endif
#define GetIconRectangleA(rp, icon, label, rect, tags) IIcon->GetIconRectangleA(rp, icon, label, rect, tags) 
#if (defined(__STDC_VERSION__) && __STDC_VERSION__ >= 199901L) || (__GNUC__ >= 3)
#define GetIconRectangle(rp, icon, label, ...) IIcon->GetIconRectangle(rp, icon, label, __VA_ARGS__) 
#elif (__GNUC__ == 2 && __GNUC_MINOR__ >= 95)
#define GetIconRectangle(rp, icon, label, vargs...) IIcon->GetIconRectangle(rp, icon, label, ## vargs) 
#endif
#define NewDiskObject(type) IIcon->NewDiskObject(type) 
#define GetIconTagList(name, tags) IIcon->GetIconTagList(name, tags) 
#if (defined(__STDC_VERSION__) && __STDC_VERSION__ >= 199901L) || (__GNUC__ >= 3)
#define GetIconTags(...) IIcon->GetIconTags(__VA_ARGS__) 
#elif (__GNUC__ == 2 && __GNUC_MINOR__ >= 95)
#define GetIconTags(vargs...) IIcon->GetIconTags(## vargs) 
#endif
#define PutIconTagList(name, icon, tags) IIcon->PutIconTagList(name, icon, tags) 
#if (defined(__STDC_VERSION__) && __STDC_VERSION__ >= 199901L) || (__GNUC__ >= 3)
#define PutIconTags(name, ...) IIcon->PutIconTags(name, __VA_ARGS__) 
#elif (__GNUC__ == 2 && __GNUC_MINOR__ >= 95)
#define PutIconTags(name, vargs...) IIcon->PutIconTags(name, ## vargs) 
#endif
#define LayoutIconA(icon, screen, tags) IIcon->LayoutIconA(icon, screen, tags) 
#if (defined(__STDC_VERSION__) && __STDC_VERSION__ >= 199901L) || (__GNUC__ >= 3)
#define LayoutIcon(icon, ...) IIcon->LayoutIcon(icon, __VA_ARGS__) 
#elif (__GNUC__ == 2 && __GNUC_MINOR__ >= 95)
#define LayoutIcon(icon, vargs...) IIcon->LayoutIcon(icon, ## vargs) 
#endif
#define ChangeToSelectedIconColor(cr) IIcon->ChangeToSelectedIconColor(cr) 
#define BumpRevisionLength(newname, oldname, maxlength) IIcon->BumpRevisionLength(newname, oldname, maxlength) 

#endif /* INLINE4_ICON_H */
