#ifndef INLINE4_LISTBROWSER_H
#define INLINE4_LISTBROWSER_H

/*
** This file was auto generated by idltool 51.8.
**
** It provides compatibility to OS3 style library
** calls by substituting functions.
**
** Do not edit manually.
*/ 

#ifndef EXEC_TYPES_H
#include <exec/types.h>
#endif
#ifndef EXEC_EXEC_H
#include <exec/exec.h>
#endif
#ifndef EXEC_INTERFACES_H
#include <exec/interfaces.h>
#endif

#ifndef INTUITION_INTUITION_H
#include <intuition/intuition.h>
#endif
#ifndef INTUITION_CLASSES_H
#include <intuition/classes.h>
#endif
#ifndef GADGETS_LISTBROWSER_H
#include <gadgets/listbrowser.h>
#endif

/* Inline macros for Interface "main" */
#define LISTBROWSER_GetClass() IListBrowser->LISTBROWSER_GetClass() 
#define AllocListBrowserNodeA(columns, tags) IListBrowser->AllocListBrowserNodeA(columns, tags) 
#if (defined(__STDC_VERSION__) && __STDC_VERSION__ >= 199901L) || (__GNUC__ >= 3)
#define AllocListBrowserNode(...) IListBrowser->AllocListBrowserNode(__VA_ARGS__) 
#elif (__GNUC__ == 2 && __GNUC_MINOR__ >= 95)
#define AllocListBrowserNode(vargs...) IListBrowser->AllocListBrowserNode(## vargs) 
#endif
#define FreeListBrowserNode(node) IListBrowser->FreeListBrowserNode(node) 
#define SetListBrowserNodeAttrsA(node, tags) IListBrowser->SetListBrowserNodeAttrsA(node, tags) 
#if (defined(__STDC_VERSION__) && __STDC_VERSION__ >= 199901L) || (__GNUC__ >= 3)
#define SetListBrowserNodeAttrs(...) IListBrowser->SetListBrowserNodeAttrs(__VA_ARGS__) 
#elif (__GNUC__ == 2 && __GNUC_MINOR__ >= 95)
#define SetListBrowserNodeAttrs(vargs...) IListBrowser->SetListBrowserNodeAttrs(## vargs) 
#endif
#define GetListBrowserNodeAttrsA(node, tags) IListBrowser->GetListBrowserNodeAttrsA(node, tags) 
#if (defined(__STDC_VERSION__) && __STDC_VERSION__ >= 199901L) || (__GNUC__ >= 3)
#define GetListBrowserNodeAttrs(...) IListBrowser->GetListBrowserNodeAttrs(__VA_ARGS__) 
#elif (__GNUC__ == 2 && __GNUC_MINOR__ >= 95)
#define GetListBrowserNodeAttrs(vargs...) IListBrowser->GetListBrowserNodeAttrs(## vargs) 
#endif
#define ListBrowserSelectAll(list) IListBrowser->ListBrowserSelectAll(list) 
#define ShowListBrowserNodeChildren(node, depth) IListBrowser->ShowListBrowserNodeChildren(node, depth) 
#define HideListBrowserNodeChildren(node) IListBrowser->HideListBrowserNodeChildren(node) 
#define ShowAllListBrowserChildren(list) IListBrowser->ShowAllListBrowserChildren(list) 
#define HideAllListBrowserChildren(list) IListBrowser->HideAllListBrowserChildren(list) 
#define FreeListBrowserList(list) IListBrowser->FreeListBrowserList(list) 
#define AllocLBColumnInfoA(columns, tags) IListBrowser->AllocLBColumnInfoA(columns, tags) 
#if (defined(__STDC_VERSION__) && __STDC_VERSION__ >= 199901L) || (__GNUC__ >= 3)
#define AllocLBColumnInfo(...) IListBrowser->AllocLBColumnInfo(__VA_ARGS__) 
#elif (__GNUC__ == 2 && __GNUC_MINOR__ >= 95)
#define AllocLBColumnInfo(vargs...) IListBrowser->AllocLBColumnInfo(## vargs) 
#endif
#define SetLBColumnInfoAttrsA(columninfo, tags) IListBrowser->SetLBColumnInfoAttrsA(columninfo, tags) 
#if (defined(__STDC_VERSION__) && __STDC_VERSION__ >= 199901L) || (__GNUC__ >= 3)
#define SetLBColumnInfoAttrs(...) IListBrowser->SetLBColumnInfoAttrs(__VA_ARGS__) 
#elif (__GNUC__ == 2 && __GNUC_MINOR__ >= 95)
#define SetLBColumnInfoAttrs(vargs...) IListBrowser->SetLBColumnInfoAttrs(## vargs) 
#endif
#define GetLBColumnInfoAttrsA(columninfo, tags) IListBrowser->GetLBColumnInfoAttrsA(columninfo, tags) 
#if (defined(__STDC_VERSION__) && __STDC_VERSION__ >= 199901L) || (__GNUC__ >= 3)
#define GetLBColumnInfoAttrs(...) IListBrowser->GetLBColumnInfoAttrs(__VA_ARGS__) 
#elif (__GNUC__ == 2 && __GNUC_MINOR__ >= 95)
#define GetLBColumnInfoAttrs(vargs...) IListBrowser->GetLBColumnInfoAttrs(## vargs) 
#endif
#define FreeLBColumnInfo(columninfo) IListBrowser->FreeLBColumnInfo(columninfo) 
#define ListBrowserClearAll(list) IListBrowser->ListBrowserClearAll(list) 

#endif /* INLINE4_LISTBROWSER_H */
