#ifndef INLINE4_PICASSO96API_H
#define INLINE4_PICASSO96API_H

/*
** This file was auto generated by idltool 53.5.
**
** It provides compatibility to OS3 style library
** calls by substituting functions.
**
** Do not edit manually.
*/ 

#ifndef EXEC_TYPES_H
#include <exec/types.h>
#endif
#ifndef EXEC_EXEC_H
#include <exec/exec.h>
#endif
#ifndef EXEC_INTERFACES_H
#include <exec/interfaces.h>
#endif

#ifndef LIBRARIES_PICASSO96_H
#include <libraries/Picasso96.h>
#endif
#ifndef GRAPHICS_RASTPORT_H
#include <graphics/rastport.h>
#endif
#ifndef UTILITY_HOOKS_H
#include <utility/hooks.h>
#endif
#include <interfaces/Picasso96API.h>

/* Inline macros for Interface "main" */
#define p96AllocBitMap(SizeX, SizeY, Depth, Flags, friendBitMap, RGBFormat) IP96->p96AllocBitMap((SizeX), (SizeY), (Depth), (Flags), (friendBitMap), (RGBFormat)) 
#define p96FreeBitMap(bitMap) IP96->p96FreeBitMap((bitMap)) 
#define p96GetBitMapAttr(bitMap, Attribute) IP96->p96GetBitMapAttr((bitMap), (Attribute)) 
#define p96LockBitMap(bitMap, Buffer, Size) IP96->p96LockBitMap((bitMap), (Buffer), (Size)) 
#define p96UnlockBitMap(bitMap, Lock) IP96->p96UnlockBitMap((bitMap), (Lock)) 
#define p96BestModeIDTagList(Tags) IP96->p96BestModeIDTagList((Tags)) 
#if (defined(__STDC_VERSION__) && __STDC_VERSION__ >= 199901L) || (__GNUC__ >= 3)
#define p96BestModeIDTags(...) IP96->p96BestModeIDTags(__VA_ARGS__) 
#elif (__GNUC__ == 2 && __GNUC_MINOR__ >= 95)
#define p96BestModeIDTags(...) IP96->p96BestModeIDTags(## vargs) 
#endif
#define p96RequestModeIDTagList(Tags) IP96->p96RequestModeIDTagList((Tags)) 
#if (defined(__STDC_VERSION__) && __STDC_VERSION__ >= 199901L) || (__GNUC__ >= 3)
#define p96RequestModeIDTags(...) IP96->p96RequestModeIDTags(__VA_ARGS__) 
#elif (__GNUC__ == 2 && __GNUC_MINOR__ >= 95)
#define p96RequestModeIDTags(...) IP96->p96RequestModeIDTags(## vargs) 
#endif
#define p96AllocModeListTagList(Tags) IP96->p96AllocModeListTagList((Tags)) 
#if (defined(__STDC_VERSION__) && __STDC_VERSION__ >= 199901L) || (__GNUC__ >= 3)
#define p96AllocModeListTags(...) IP96->p96AllocModeListTags(__VA_ARGS__) 
#elif (__GNUC__ == 2 && __GNUC_MINOR__ >= 95)
#define p96AllocModeListTags(...) IP96->p96AllocModeListTags(## vargs) 
#endif
#define p96FreeModeList(list) IP96->p96FreeModeList((list)) 
#define p96GetModeIDAttr(Mode, Attribute) IP96->p96GetModeIDAttr((Mode), (Attribute)) 
#define p96OpenScreenTagList(Tags) IP96->p96OpenScreenTagList((Tags)) 
#if (defined(__STDC_VERSION__) && __STDC_VERSION__ >= 199901L) || (__GNUC__ >= 3)
#define p96OpenScreenTags(...) IP96->p96OpenScreenTags(__VA_ARGS__) 
#elif (__GNUC__ == 2 && __GNUC_MINOR__ >= 95)
#define p96OpenScreenTags(...) IP96->p96OpenScreenTags(## vargs) 
#endif
#define p96CloseScreen(screen) IP96->p96CloseScreen((screen)) 
#define p96WritePixelArray(ri, SrcX, SrcY, rp, DestX, DestY, SizeX, SizeY) IP96->p96WritePixelArray((ri), (SrcX), (SrcY), (rp), (DestX), (DestY), (SizeX), (SizeY)) 
#define p96ReadPixelArray(ri, DestX, DestY, rp, SrcX, SrcY, SizeX, SizeY) IP96->p96ReadPixelArray((ri), (DestX), (DestY), (rp), (SrcX), (SrcY), (SizeX), (SizeY)) 
#define p96WritePixel(rp, x, y, color) IP96->p96WritePixel((rp), (x), (y), (color)) 
#define p96ReadPixel(rp, x, y) IP96->p96ReadPixel((rp), (x), (y)) 
#define p96RectFill(rp, MinX, MinY, MaxX, MaxY, color) IP96->p96RectFill((rp), (MinX), (MinY), (MaxX), (MaxY), (color)) 
#define p96WriteTrueColorData(tci, SrcX, SrcY, rp, DestX, DestY, SizeX, SizeY) IP96->p96WriteTrueColorData((tci), (SrcX), (SrcY), (rp), (DestX), (DestY), (SizeX), (SizeY)) 
#define p96ReadTrueColorData(tci, DestX, DestY, rp, SrcX, SrcY, SizeX, SizeY) IP96->p96ReadTrueColorData((tci), (DestX), (DestY), (rp), (SrcX), (SrcY), (SizeX), (SizeY)) 
#define p96PIP_OpenTagList(Tags) IP96->p96PIP_OpenTagList((Tags)) 
#if (defined(__STDC_VERSION__) && __STDC_VERSION__ >= 199901L) || (__GNUC__ >= 3)
#define p96PIP_OpenTags(...) IP96->p96PIP_OpenTags(__VA_ARGS__) 
#elif (__GNUC__ == 2 && __GNUC_MINOR__ >= 95)
#define p96PIP_OpenTags(...) IP96->p96PIP_OpenTags(## vargs) 
#endif
#define p96PIP_Close(window) IP96->p96PIP_Close((window)) 
#define p96PIP_SetTagList(window, Tags) IP96->p96PIP_SetTagList((window), (Tags)) 
#if (defined(__STDC_VERSION__) && __STDC_VERSION__ >= 199901L) || (__GNUC__ >= 3)
#define p96PIP_SetTags(...) IP96->p96PIP_SetTags(__VA_ARGS__) 
#elif (__GNUC__ == 2 && __GNUC_MINOR__ >= 95)
#define p96PIP_SetTags(vargs...) IP96->p96PIP_SetTags(## vargs) 
#endif
#define p96PIP_GetTagList(window, Tags) IP96->p96PIP_GetTagList((window), (Tags)) 
#if (defined(__STDC_VERSION__) && __STDC_VERSION__ >= 199901L) || (__GNUC__ >= 3)
#define p96PIP_GetTags(...) IP96->p96PIP_GetTags(__VA_ARGS__) 
#elif (__GNUC__ == 2 && __GNUC_MINOR__ >= 95)
#define p96PIP_GetTags(vargs...) IP96->p96PIP_GetTags(## vargs) 
#endif
#define p96PIP_GetIMsg(port) IP96->p96PIP_GetIMsg((port)) 
#define p96PIP_ReplyIMsg(intuiMessage) IP96->p96PIP_ReplyIMsg((intuiMessage)) 
#define p96GetRTGDataTagList(Tags) IP96->p96GetRTGDataTagList((Tags)) 
#if (defined(__STDC_VERSION__) && __STDC_VERSION__ >= 199901L) || (__GNUC__ >= 3)
#define p96GetRTGDataTags(...) IP96->p96GetRTGDataTags(__VA_ARGS__) 
#elif (__GNUC__ == 2 && __GNUC_MINOR__ >= 95)
#define p96GetRTGDataTags(...) IP96->p96GetRTGDataTags(## vargs) 
#endif
#define p96GetBoardDataTagList(board, Tags) IP96->p96GetBoardDataTagList((board), (Tags)) 
#if (defined(__STDC_VERSION__) && __STDC_VERSION__ >= 199901L) || (__GNUC__ >= 3)
#define p96GetBoardDataTags(...) IP96->p96GetBoardDataTags(__VA_ARGS__) 
#elif (__GNUC__ == 2 && __GNUC_MINOR__ >= 95)
#define p96GetBoardDataTags(vargs...) IP96->p96GetBoardDataTags(## vargs) 
#endif
#define p96EncodeColor(RGBFormat, Color) IP96->p96EncodeColor((RGBFormat), (Color)) 
#define p96LockBitMapToBoard(bm, board_number, buf, size) IP96->p96LockBitMapToBoard((bm), (board_number), (buf), (size)) 
#define p96UnlockBitMapFromBoard(bm, modified) IP96->p96UnlockBitMapFromBoard((bm), (modified)) 

#endif /* INLINE4_PICASSO96API_H */
