#ifndef INLINE4_POPUPMENU_H
#define INLINE4_POPUPMENU_H

/*
** This file was auto generated by idltool 51.8.
**
** It provides compatibility to OS3 style library
** calls by substituting functions.
**
** Do not edit manually.
*/ 

#ifndef EXEC_TYPES_H
#include <exec/types.h>
#endif
#ifndef EXEC_EXEC_H
#include <exec/exec.h>
#endif
#ifndef EXEC_INTERFACES_H
#include <exec/interfaces.h>
#endif

#ifndef CLASSES_POPUPMENU_H
#include <classes/popupmenu.h>
#endif

/* Inline macros for Interface "main" */
#define POPUPMENU_GetClass() IPopupMenu->POPUPMENU_GetClass() 
#define POPUPMENU_GetItemClass() IPopupMenu->POPUPMENU_GetItemClass() 
#define POPUPMENU_MakeMXListA(ids) IPopupMenu->POPUPMENU_MakeMXListA(ids) 
#if (defined(__STDC_VERSION__) && __STDC_VERSION__ >= 199901L) || (__GNUC__ >= 3)
#define POPUPMENU_MakeMXList(...) IPopupMenu->POPUPMENU_MakeMXList(__VA_ARGS__) 
#elif (__GNUC__ == 2 && __GNUC_MINOR__ >= 95)
#define POPUPMENU_MakeMXList(...) IPopupMenu->POPUPMENU_MakeMXList(## vargs) 
#endif
#define POPUPMENU_FreeIDList(idlist) IPopupMenu->POPUPMENU_FreeIDList(idlist) 
#define POPUPMENU_MakeIDListA(tags) IPopupMenu->POPUPMENU_MakeIDListA(tags) 
#if (defined(__STDC_VERSION__) && __STDC_VERSION__ >= 199901L) || (__GNUC__ >= 3)
#define POPUPMENU_MakeIDList(...) IPopupMenu->POPUPMENU_MakeIDList(__VA_ARGS__) 
#elif (__GNUC__ == 2 && __GNUC_MINOR__ >= 95)
#define POPUPMENU_MakeIDList(...) IPopupMenu->POPUPMENU_MakeIDList(## vargs) 
#endif

#endif /* INLINE4_POPUPMENU_H */
