#ifndef CLIB_EXPANSION_PROTOS_H
#define CLIB_EXPANSION_PROTOS_H

/*
** This file was machine generated by idltool.py 54.8.
** Do not edit.
**
** Copyright (C) 2003-2021 Trevor Dickinson
**
** C prototypes. For use with 32 bit integers only.
*/

#include <exec/types.h>
#include <libraries/configvars.h>
#include <dos/filehandler.h>
#include <utility/tagitem.h>

#ifdef __amigaos4__
#error Include <proto/> header files, not <clib/> header files in AmigaOS 4.
#endif

#ifdef __cplusplus
#ifdef __USE_AMIGAOS_NAMESPACE__
namespace AmigaOS {
#endif
extern "C" {
#endif /* __cplusplus */

void AddConfigDev(struct ConfigDev * configDev);
BOOL AddBootNode(LONG bootPri, ULONG flags, APTR deviceNode, struct ConfigDev * configDev);
ULONG AllocBoardMem(ULONG slotSpec);
struct ConfigDev * AllocConfigDev(void);
APTR AllocExpansionMem(ULONG numSlots, ULONG slotAlign);
ULONG ConfigBoard(APTR board, struct ConfigDev * configDev);
ULONG ConfigChain(APTR baseAddr);
struct ConfigDev * FindConfigDev(const struct ConfigDev * oldConfigDev, LONG manufacturer, LONG product);
void FreeBoardMem(ULONG startSlot, ULONG slotSpec);
void FreeConfigDev(struct ConfigDev * configDev);
void FreeExpansionMem(ULONG startSlot, ULONG numSlots);
UBYTE ReadExpansionByte(CONST_APTR board, ULONG offset);
ULONG ReadExpansionRom(CONST_APTR board, struct ConfigDev * configDev);
void RemConfigDev(struct ConfigDev * configDev);
void WriteExpansionByte(APTR board, ULONG offset, UBYTE byte);
void ObtainConfigBinding(void);
void ReleaseConfigBinding(void);
void SetCurrentBinding(struct CurrentBinding * currentBinding, ULONG bindingSize);
ULONG GetCurrentBinding(const struct CurrentBinding * currentBinding, ULONG bindingSize);
struct DeviceNode * MakeDosNode(CONST_APTR parmPacket);
BOOL AddDosNode(LONG bootPri, ULONG flags, struct DeviceNode * deviceNode);
void WriteExpansionWord(APTR board, ULONG offset, UWORD word);
ULONG GetMachineInfo(const struct TagItem * tagList);
ULONG GetMachineInfoTags(Tag tag1, ...);

#ifdef __cplusplus
}
#ifdef __USE_AMIGAOS_NAMESPACE__
}
#endif
#endif /* __cplusplus */

#endif /* CLIB_EXPANSION_PROTOS_H */
