#ifndef BATTCLOCK_INTERFACE_DEF_H
#define BATTCLOCK_INTERFACE_DEF_H

/*
** This file was machine generated by idltool 52.6.
** Do not edit
*/ 

#ifndef EXEC_TYPES_H
#include <exec/types.h>
#endif
#ifndef EXEC_EXEC_H
#include <exec/exec.h>
#endif
#ifndef EXEC_INTERFACES_H
#include <exec/interfaces.h>
#endif


#ifdef __cplusplus
#ifdef __USE_AMIGAOS_NAMESPACE__
namespace AmigaOS {
#endif
extern "C" {
#endif

struct BattClockIFace
{
	struct InterfaceData Data;

	ULONG APICALL (*Obtain)(struct BattClockIFace *Self);
	ULONG APICALL (*Release)(struct BattClockIFace *Self);
	void APICALL (*Expunge)(struct BattClockIFace *Self);
	struct Interface * APICALL (*Clone)(struct BattClockIFace *Self);
	VOID APICALL (*ResetBattClock)(struct BattClockIFace *Self);
	ULONG APICALL (*ReadBattClock)(struct BattClockIFace *Self);
	VOID APICALL (*WriteBattClock)(struct BattClockIFace *Self, ULONG time);
	ULONG APICALL (*ReadBattClockMem)(struct BattClockIFace *Self, ULONG offset, ULONG length);
	VOID APICALL (*WriteBattClockMem)(struct BattClockIFace *Self, ULONG data, ULONG offset, ULONG length);
};

#ifdef __cplusplus
}
#ifdef __USE_AMIGAOS_NAMESPACE__
}
#endif
#endif

#endif /* BATTCLOCK_INTERFACE_DEF_H */
