#ifndef BTREE_INTERFACE_DEF_H
#define BTREE_INTERFACE_DEF_H

/*
** This file was machine generated by idltool 53.5.
** Do not edit
*/ 

#ifndef EXEC_TYPES_H
#include <exec/types.h>
#endif
#ifndef EXEC_EXEC_H
#include <exec/exec.h>
#endif
#ifndef EXEC_INTERFACES_H
#include <exec/interfaces.h>
#endif

#ifndef LIBRARIES_BTREE_H
#include <libraries/btree.h>
#endif

#ifdef __cplusplus
#ifdef __USE_AMIGAOS_NAMESPACE__
namespace AmigaOS {
#endif
extern "C" {
#endif

struct BTreeIFace
{
	struct InterfaceData Data;

	uint32 APICALL (*Obtain)(struct BTreeIFace *Self);
	uint32 APICALL (*Release)(struct BTreeIFace *Self);
	void APICALL (*Expunge)(struct BTreeIFace *Self);
	struct Interface * APICALL (*Clone)(struct BTreeIFace *Self);
	APTR APICALL (*CreateTree)(struct BTreeIFace *Self, ULONG Type, const struct BTArgArray * argArray);
	void APICALL (*DeleteTree)(struct BTreeIFace *Self, APTR Tree);
	APTR APICALL (*InsertTreeNode)(struct BTreeIFace *Self, APTR Tree, CONST_APTR Key, CONST_APTR Data);
	void APICALL (*DeleteTreeNode)(struct BTreeIFace *Self, APTR Tree, APTR Node);
	APTR APICALL (*GetTreeNodeKey)(struct BTreeIFace *Self, CONST_APTR Tree, CONST_APTR Node);
	APTR APICALL (*GetTreeNodeData)(struct BTreeIFace *Self, CONST_APTR Tree, CONST_APTR Node);
	APTR APICALL (*SuccTreeNode)(struct BTreeIFace *Self, CONST_APTR Tree, CONST_APTR Node);
	APTR APICALL (*PredTreeNode)(struct BTreeIFace *Self, CONST_APTR Tree, CONST_APTR Node);
	APTR APICALL (*MinTreeNode)(struct BTreeIFace *Self, CONST_APTR Tree);
	APTR APICALL (*MaxTreeNode)(struct BTreeIFace *Self, CONST_APTR Tree);
	APTR APICALL (*FindTreeNodeByKey)(struct BTreeIFace *Self, CONST_APTR Tree, CONST_APTR Key);
	APTR APICALL (*FindTreeNodeByData)(struct BTreeIFace *Self, CONST_APTR Tree, CONST_APTR Data);
	ULONG APICALL (*ForTreeNodes)(struct BTreeIFace *Self, CONST_APTR Tree, void (*nodeFunc)(APTR userData, CONST_APTR Node), CONST_APTR userData);
	ULONG APICALL (*EnumTreeNodes)(struct BTreeIFace *Self, CONST_APTR Tree, CONST_APTR lowKey, CONST_APTR highKey, LONG (*nodeFunc)(APTR userData, CONST_APTR Node), CONST_APTR userData);
	ULONG APICALL (*GetTreeSize)(struct BTreeIFace *Self, CONST_APTR Tree);
	ULONG APICALL (*GetTreeHeight)(struct BTreeIFace *Self, CONST_APTR Tree);
	void APICALL (*FlushTree)(struct BTreeIFace *Self, APTR Tree);
	APTR APICALL (*SetTreeNodeData)(struct BTreeIFace *Self, CONST_APTR Tree, APTR Node, CONST_APTR NewData);
};

#ifdef __cplusplus
}
#ifdef __USE_AMIGAOS_NAMESPACE__
}
#endif
#endif

#endif /* BTREE_INTERFACE_DEF_H */
