#ifndef FILESYSBOX_INTERFACE_DEF_H
#define FILESYSBOX_INTERFACE_DEF_H

/*
** This file was machine generated by idltool 53.25.
** Do not edit
*/ 

#ifndef EXEC_TYPES_H
#include <exec/types.h>
#endif
#ifndef EXEC_EXEC_H
#include <exec/exec.h>
#endif
#ifndef EXEC_INTERFACES_H
#include <exec/interfaces.h>
#endif

#ifndef UTILITY_TAGITEM_H
#include <utility/tagitem.h>
#endif
#ifndef LIBRARIES_FILESYSBOX_H
#include <libraries/filesysbox.h>
#endif
#ifndef DEVICES_TIMER_H
#include <devices/timer.h>
#endif

#ifdef __cplusplus
#ifdef __USE_AMIGAOS_NAMESPACE__
namespace AmigaOS {
#endif
extern "C" {
#endif

struct FileSysBoxIFace
{
	struct InterfaceData Data;

	uint32 APICALL (*Obtain)(struct FileSysBoxIFace *Self);
	uint32 APICALL (*Release)(struct FileSysBoxIFace *Self);
	APTR Expunge_UNIMPLEMENTED;
	APTR Clone_UNIMPLEMENTED;
	APTR APICALL (*FbxQueryMountMsg)(struct FileSysBoxIFace *Self, struct Message * msg, int32 attr);
	struct FbxFS * APICALL (*FbxSetupFS)(struct FileSysBoxIFace *Self, struct Message * msg, const struct TagItem * tags, const struct fuse_operations * ops, int32 opssize, APTR udata);
	int32 APICALL (*FbxEventLoop)(struct FileSysBoxIFace *Self, struct FbxFS * fs);
	void APICALL (*FbxCleanupFS)(struct FileSysBoxIFace *Self, struct FbxFS * fs);
	void APICALL (*FbxReturnMountMsg)(struct FileSysBoxIFace *Self, struct Message * msg, int32 r1, int32 r2);
	int32 APICALL (*FbxFuseVersion)(struct FileSysBoxIFace *Self);
	int32 APICALL (*FbxVersion)(struct FileSysBoxIFace *Self);
	struct FbxFS * APICALL (*FbxSetupFSTags)(struct FileSysBoxIFace *Self, struct Message * msg, const struct fuse_operations * ops, int32 opssize, APTR udata, ...);
	void APICALL (*FbxSetSignalCallback)(struct FileSysBoxIFace *Self, struct FbxFS * fs, FbxSignalCallbackFunc func, uint32 signals);
	struct FbxTimerCallbackData * APICALL (*FbxInstallTimerCallback)(struct FileSysBoxIFace *Self, struct FbxFS * fs, FbxTimerCallbackFunc func, uint32 period);
	void APICALL (*FbxUninstallTimerCallback)(struct FileSysBoxIFace *Self, struct FbxFS * fs, struct FbxTimerCallbackData * cb);
	void APICALL (*FbxSignalDiskChange)(struct FileSysBoxIFace *Self, struct FbxFS * fs);
	void APICALL (*FbxQueryFS)(struct FileSysBoxIFace *Self, struct FbxFS * fs, const struct TagItem * tags);
	void APICALL (*FbxQueryFSTags)(struct FileSysBoxIFace *Self, struct FbxFS * fs, ...);
	void APICALL (*FbxGetSysTime)(struct FileSysBoxIFace *Self, struct FbxFS * fs, struct TimeVal * tv);
};

#ifdef __cplusplus
}
#ifdef __USE_AMIGAOS_NAMESPACE__
}
#endif
#endif

#endif /* FILESYSBOX_INTERFACE_DEF_H */
