#ifndef FLITE_INTERFACE_DEF_H
#define FLITE_INTERFACE_DEF_H

/*
** This file was machine generated by idltool 53.1.
** Do not edit
*/ 

#ifndef EXEC_TYPES_H
#include <exec/types.h>
#endif
#ifndef EXEC_EXEC_H
#include <exec/exec.h>
#endif
#ifndef EXEC_INTERFACES_H
#include <exec/interfaces.h>
#endif

#ifndef DEVICES_FLITE_H
#include <devices/flite.h>
#endif

#ifdef __cplusplus
#ifdef __USE_AMIGAOS_NAMESPACE__
namespace AmigaOS {
#endif
extern "C" {
#endif

struct FliteIFace
{
	struct InterfaceData Data;

	uint32 APICALL (*Obtain)(struct FliteIFace *Self);
	uint32 APICALL (*Release)(struct FliteIFace *Self);
	void APICALL (*Expunge)(struct FliteIFace *Self);
	struct Interface * APICALL (*Clone)(struct FliteIFace *Self);
	struct FliteVoice * APICALL (*OpenVoice)(struct FliteIFace *Self, CONST_STRPTR name);
	void APICALL (*CloseVoice)(struct FliteIFace *Self, struct FliteVoice * voice);
};

#ifdef __cplusplus
}
#ifdef __USE_AMIGAOS_NAMESPACE__
}
#endif
#endif

#endif /* FLITE_INTERFACE_DEF_H */
