#ifndef MISC_INTERFACE_DEF_H
#define MISC_INTERFACE_DEF_H

/*
** This file was machine generated by idltool 52.6.
** Do not edit
*/ 

#ifndef EXEC_TYPES_H
#include <exec/types.h>
#endif
#ifndef EXEC_EXEC_H
#include <exec/exec.h>
#endif
#ifndef EXEC_INTERFACES_H
#include <exec/interfaces.h>
#endif


#ifdef __cplusplus
#ifdef __USE_AMIGAOS_NAMESPACE__
namespace AmigaOS {
#endif
extern "C" {
#endif

struct MiscIFace
{
	struct InterfaceData Data;

	ULONG APICALL (*Obtain)(struct MiscIFace *Self);
	ULONG APICALL (*Release)(struct MiscIFace *Self);
	void APICALL (*Expunge)(struct MiscIFace *Self);
	struct Interface * APICALL (*Clone)(struct MiscIFace *Self);
	CONST_STRPTR APICALL (*AllocMiscResource)(struct MiscIFace *Self, ULONG unitNum, CONST_STRPTR name);
	VOID APICALL (*FreeMiscResource)(struct MiscIFace *Self, ULONG unitNum);
};

#ifdef __cplusplus
}
#ifdef __USE_AMIGAOS_NAMESPACE__
}
#endif
#endif

#endif /* MISC_INTERFACE_DEF_H */
