#ifndef NONVOLATILE_INTERFACE_DEF_H
#define NONVOLATILE_INTERFACE_DEF_H

/*
** This file was machine generated by idltool 52.6.
** Do not edit
*/ 

#ifndef EXEC_TYPES_H
#include <exec/types.h>
#endif
#ifndef EXEC_EXEC_H
#include <exec/exec.h>
#endif
#ifndef EXEC_INTERFACES_H
#include <exec/interfaces.h>
#endif

#ifndef EXEC_LISTS_H
#include <exec/lists.h>
#endif
#ifndef LIBRARIES_NONVOLATILE_H
#include <libraries/nonvolatile.h>
#endif

#ifdef __cplusplus
#ifdef __USE_AMIGAOS_NAMESPACE__
namespace AmigaOS {
#endif
extern "C" {
#endif

struct NVIFace
{
	struct InterfaceData Data;

	uint32 APICALL (*Obtain)(struct NVIFace *Self);
	uint32 APICALL (*Release)(struct NVIFace *Self);
	void APICALL (*Expunge)(struct NVIFace *Self);
	struct Interface * APICALL (*Clone)(struct NVIFace *Self);
	APTR APICALL (*GetCopyNV)(struct NVIFace *Self, CONST_STRPTR appName, CONST_STRPTR itemName, BOOL killRequesters);
	VOID APICALL (*FreeNVData)(struct NVIFace *Self, APTR data);
	UWORD APICALL (*StoreNV)(struct NVIFace *Self, CONST_STRPTR appName, CONST_STRPTR itemName, const APTR data, ULONG length, BOOL killRequesters);
	BOOL APICALL (*DeleteNV)(struct NVIFace *Self, CONST_STRPTR appName, CONST_STRPTR itemName, BOOL killRequesters);
	struct NVInfo * APICALL (*GetNVInfo)(struct NVIFace *Self, BOOL killRequesters);
	struct MinList * APICALL (*GetNVList)(struct NVIFace *Self, CONST_STRPTR appName, BOOL killRequesters);
	BOOL APICALL (*SetNVProtection)(struct NVIFace *Self, CONST_STRPTR appName, CONST_STRPTR itemName, LONG mask, BOOL killRequesters);
	ULONG APICALL (*SetUBootVar)(struct NVIFace *Self, CONST_STRPTR name, CONST_STRPTR value);
	CONST_STRPTR APICALL (*GetUBootVar)(struct NVIFace *Self, CONST_STRPTR name);
	void APICALL (*FreeUBootVar)(struct NVIFace *Self, CONST_STRPTR value);
};

#ifdef __cplusplus
}
#ifdef __USE_AMIGAOS_NAMESPACE__
}
#endif
#endif

#endif /* NONVOLATILE_INTERFACE_DEF_H */
