#ifndef PICASSO96API_INTERFACE_DEF_H
#define PICASSO96API_INTERFACE_DEF_H

/*
** This file was machine generated by idltool 53.6.
** Do not edit
*/

#ifndef EXEC_TYPES_H
#include <exec/types.h>
#endif
#ifndef EXEC_EXEC_H
#include <exec/exec.h>
#endif
#ifndef EXEC_INTERFACES_H
#include <exec/interfaces.h>
#endif

#ifndef LIBRARIES_PICASSO96_H
#include <libraries/Picasso96.h>
#endif
#ifndef GRAPHICS_RASTPORT_H
#include <graphics/rastport.h>
#endif
#ifndef UTILITY_HOOKS_H
#include <utility/hooks.h>
#endif

#ifdef __cplusplus
#ifdef __USE_AMIGAOS_NAMESPACE__
namespace AmigaOS {
#endif
extern "C" {
#endif

struct P96IFace
{
	struct InterfaceData Data;

	ULONG APICALL (*Obtain)(struct P96IFace *Self);
	ULONG APICALL (*Release)(struct P96IFace *Self);
	void APICALL (*Expunge)(struct P96IFace *Self);
	struct Interface * APICALL (*Clone)(struct P96IFace *Self);
	DEPRECATED struct BitMap * APICALL (*p96AllocBitMap)(struct P96IFace *Self, ULONG SizeX, ULONG SizeY, ULONG Depth, ULONG Flags, struct BitMap * friendBitMap, RGBFTYPE RGBFormat);
	DEPRECATED void APICALL (*p96FreeBitMap)(struct P96IFace *Self, struct BitMap * bitMap);
	ULONG APICALL (*p96GetBitMapAttr)(struct P96IFace *Self, struct BitMap * bitMap, ULONG Attribute);
	DEPRECATED LONG APICALL (*p96LockBitMap)(struct P96IFace *Self, struct BitMap * bitMap, UBYTE * Buffer, ULONG Size);
	DEPRECATED void APICALL (*p96UnlockBitMap)(struct P96IFace *Self, struct BitMap * bitMap, LONG Lock);
	ULONG APICALL (*p96BestModeIDTagList)(struct P96IFace *Self, struct TagItem * Tags);
	ULONG APICALL (*p96BestModeIDTags)(struct P96IFace *Self, ...);
	ULONG APICALL (*p96RequestModeIDTagList)(struct P96IFace *Self, struct TagItem * Tags);
	ULONG APICALL (*p96RequestModeIDTags)(struct P96IFace *Self, ...);
	struct List * APICALL (*p96AllocModeListTagList)(struct P96IFace *Self, struct TagItem * Tags);
	struct List * APICALL (*p96AllocModeListTags)(struct P96IFace *Self, ...);
	void APICALL (*p96FreeModeList)(struct P96IFace *Self, struct List * list);
	ULONG APICALL (*p96GetModeIDAttr)(struct P96IFace *Self, ULONG Mode, ULONG Attribute);
	struct Screen * APICALL (*p96OpenScreenTagList)(struct P96IFace *Self, struct TagItem * Tags);
	struct Screen * APICALL (*p96OpenScreenTags)(struct P96IFace *Self, ...);
	BOOL APICALL (*p96CloseScreen)(struct P96IFace *Self, struct Screen * screen);
	DEPRECATED void APICALL (*p96WritePixelArray)(struct P96IFace *Self, struct RenderInfo * ri, UWORD SrcX, UWORD SrcY, struct RastPort * rp, UWORD DestX, UWORD DestY, UWORD SizeX, UWORD SizeY);
	DEPRECATED void APICALL (*p96ReadPixelArray)(struct P96IFace *Self, struct RenderInfo * ri, UWORD DestX, UWORD DestY, struct RastPort * rp, UWORD SrcX, UWORD SrcY, UWORD SizeX, UWORD SizeY);
	DEPRECATED ULONG APICALL (*p96WritePixel)(struct P96IFace *Self, struct RastPort * rp, UWORD x, UWORD y, ULONG color);
	DEPRECATED ULONG APICALL (*p96ReadPixel)(struct P96IFace *Self, struct RastPort * rp, UWORD x, UWORD y);
	DEPRECATED void APICALL (*p96RectFill)(struct P96IFace *Self, struct RastPort * rp, UWORD MinX, UWORD MinY, UWORD MaxX, UWORD MaxY, ULONG color);
	void APICALL (*p96WriteTrueColorData)(struct P96IFace *Self, struct TrueColorInfo * tci, UWORD SrcX, UWORD SrcY, struct RastPort * rp, UWORD DestX, UWORD DestY, UWORD SizeX, UWORD SizeY);
	void APICALL (*p96ReadTrueColorData)(struct P96IFace *Self, struct TrueColorInfo * tci, UWORD DestX, UWORD DestY, struct RastPort * rp, UWORD SrcX, UWORD SrcY, UWORD SizeX, UWORD SizeY);
	struct Window * APICALL (*p96PIP_OpenTagList)(struct P96IFace *Self, struct TagItem * Tags);
	struct Window * APICALL (*p96PIP_OpenTags)(struct P96IFace *Self, ...);
	BOOL APICALL (*p96PIP_Close)(struct P96IFace *Self, struct Window * window);
	LONG APICALL (*p96PIP_SetTagList)(struct P96IFace *Self, struct Window * window, struct TagItem * Tags);
	LONG APICALL (*p96PIP_SetTags)(struct P96IFace *Self, struct Window * window, ...);
	LONG APICALL (*p96PIP_GetTagList)(struct P96IFace *Self, struct Window * window, struct TagItem * Tags);
	LONG APICALL (*p96PIP_GetTags)(struct P96IFace *Self, struct Window * window, ...);
	struct IntuiMessage * APICALL (*p96PIP_GetIMsg)(struct P96IFace *Self, struct MsgPort * port);
	void APICALL (*p96PIP_ReplyIMsg)(struct P96IFace *Self, struct IntuiMessage * intuiMessage);
	LONG APICALL (*p96GetRTGDataTagList)(struct P96IFace *Self, struct TagItem * Tags);
	LONG APICALL (*p96GetRTGDataTags)(struct P96IFace *Self, ...);
	LONG APICALL (*p96GetBoardDataTagList)(struct P96IFace *Self, ULONG board, struct TagItem * Tags);
	LONG APICALL (*p96GetBoardDataTags)(struct P96IFace *Self, ULONG board, ...);
	ULONG APICALL (*p96EncodeColor)(struct P96IFace *Self, RGBFTYPE RGBFormat, ULONG Color);
	DEPRECATED BOOL APICALL (*p96LockBitMapToBoard)(struct P96IFace *Self, struct BitMap * bm, ULONG board_number, UBYTE * buf, ULONG size);
	DEPRECATED void APICALL (*p96UnlockBitMapFromBoard)(struct P96IFace *Self, struct BitMap * bm, BOOL modified);
};

#ifdef __cplusplus
}
#ifdef __USE_AMIGAOS_NAMESPACE__
}
#endif
#endif

#endif /* PICASSO96API_INTERFACE_DEF_H */
