#ifndef TIMER_INTERFACE_DEF_H
#define TIMER_INTERFACE_DEF_H

/*
** This file was machine generated by idltool 52.6.
** Do not edit
*/ 

#ifndef EXEC_TYPES_H
#include <exec/types.h>
#endif
#ifndef EXEC_EXEC_H
#include <exec/exec.h>
#endif
#ifndef EXEC_INTERFACES_H
#include <exec/interfaces.h>
#endif

#ifndef DEVICES_TIMER_H
#include <devices/timer.h>
#endif

#ifdef __cplusplus
#ifdef __USE_AMIGAOS_NAMESPACE__
namespace AmigaOS {
#endif
extern "C" {
#endif

struct TimerIFace
{
	struct InterfaceData Data;

	uint32 APICALL (*Obtain)(struct TimerIFace *Self);
	uint32 APICALL (*Release)(struct TimerIFace *Self);
	void APICALL (*Expunge)(struct TimerIFace *Self);
	struct Interface * APICALL (*Clone)(struct TimerIFace *Self);
	VOID APICALL (*AddTime)(struct TimerIFace *Self, struct TimeVal * dest, const struct TimeVal * src);
	VOID APICALL (*SubTime)(struct TimerIFace *Self, struct TimeVal * dest, const struct TimeVal * src);
	LONG APICALL (*CmpTime)(struct TimerIFace *Self, struct TimeVal * dest, const struct TimeVal * src);
	ULONG APICALL (*ReadEClock)(struct TimerIFace *Self, struct EClockVal * dest);
	VOID APICALL (*GetSysTime)(struct TimerIFace *Self, struct TimeVal * dest);
	VOID APICALL (*GetUpTime)(struct TimerIFace *Self, struct TimeVal * dest);
	VOID APICALL (*MicroDelay)(struct TimerIFace *Self, ULONG microseconds);
};

#ifdef __cplusplus
}
#ifdef __USE_AMIGAOS_NAMESPACE__
}
#endif
#endif

#endif /* TIMER_INTERFACE_DEF_H */
