#ifndef XADMASTER_INTERFACE_DEF_H
#define XADMASTER_INTERFACE_DEF_H

/*
** This file was machine generated by idltool 52.7.
** Do not edit
*/ 

#ifndef EXEC_TYPES_H
#include <exec/types.h>
#endif
#ifndef EXEC_EXEC_H
#include <exec/exec.h>
#endif
#ifndef EXEC_INTERFACES_H
#include <exec/interfaces.h>
#endif

#ifndef UTILITY_TAGITEM_H
#include <utility/tagitem.h>
#endif
#ifndef LIBRARIES_XADMASTER_H
#include <libraries/xadmaster.h>
#endif

#ifdef __cplusplus
#ifdef __USE_AMIGAOS_NAMESPACE__
namespace AmigaOS {
#endif
extern "C" {
#endif

struct XadMasterIFace
{
	struct InterfaceData Data;

	ULONG APICALL (*Obtain)(struct XadMasterIFace *Self);
	ULONG APICALL (*Release)(struct XadMasterIFace *Self);
	void APICALL (*Expunge)(struct XadMasterIFace *Self);
	struct Interface * APICALL (*Clone)(struct XadMasterIFace *Self);
	xadPTR APICALL (*xadAllocObjectA)(struct XadMasterIFace *Self, xadUINT32 type, const struct TagItem * tags);
	xadPTR APICALL (*xadAllocObject)(struct XadMasterIFace *Self, xadUINT32 type, ...);
	void APICALL (*xadFreeObjectA)(struct XadMasterIFace *Self, xadPTR object, const struct TagItem * tags);
	void APICALL (*xadFreeObject)(struct XadMasterIFace *Self, xadPTR object, ...);
	struct xadClient * APICALL (*xadRecogFileA)(struct XadMasterIFace *Self, xadSize size, const void * memory, const struct TagItem * tags);
	struct xadClient * APICALL (*xadRecogFile)(struct XadMasterIFace *Self, xadSize size, const void * memory, ...);
	xadERROR APICALL (*xadGetInfoA)(struct XadMasterIFace *Self, struct xadArchiveInfo * ai, const struct TagItem * tags);
	xadERROR APICALL (*xadGetInfo)(struct XadMasterIFace *Self, struct xadArchiveInfo * ai, ...);
	void APICALL (*xadFreeInfo)(struct XadMasterIFace *Self, struct xadArchiveInfo * ai);
	xadERROR APICALL (*xadFileUnArcA)(struct XadMasterIFace *Self, struct xadArchiveInfo * ai, const struct TagItem * tags);
	xadERROR APICALL (*xadFileUnArc)(struct XadMasterIFace *Self, struct xadArchiveInfo * ai, ...);
	xadERROR APICALL (*xadDiskUnArcA)(struct XadMasterIFace *Self, struct xadArchiveInfo * ai, const struct TagItem * tags);
	xadERROR APICALL (*xadDiskUnArc)(struct XadMasterIFace *Self, struct xadArchiveInfo * ai, ...);
	xadSTRPTR APICALL (*xadGetErrorText)(struct XadMasterIFace *Self, xadERROR errnum);
	struct xadClient * APICALL (*xadGetClientInfo)(struct XadMasterIFace *Self);
	xadERROR APICALL (*xadHookAccess)(struct XadMasterIFace *Self, xadUINT32 command, xadSignSize data, xadPTR buffer, struct xadArchiveInfo * ai);
	xadERROR APICALL (*xadConvertDatesA)(struct XadMasterIFace *Self, const struct TagItem * tags);
	xadERROR APICALL (*xadConvertDates)(struct XadMasterIFace *Self, ...);
	xadUINT16 APICALL (*xadCalcCRC16)(struct XadMasterIFace *Self, xadUINT16 id, xadUINT16 init, xadSize size, const xadUINT8 * buffer);
	xadUINT32 APICALL (*xadCalcCRC32)(struct XadMasterIFace *Self, xadUINT32 id, xadUINT32 init, xadSize size, const xadUINT8 * buffer);
	xadPTR APICALL (*xadAllocVec)(struct XadMasterIFace *Self, xadSize size, xadUINT32 flags);
	void APICALL (*xadCopyMem)(struct XadMasterIFace *Self, const void * src, xadPTR dest, xadSize size);
	xadERROR APICALL (*xadHookTagAccessA)(struct XadMasterIFace *Self, xadUINT32 command, xadSignSize data, xadPTR buffer, struct xadArchiveInfo * ai, const struct TagItem * tags);
	xadERROR APICALL (*xadHookTagAccess)(struct XadMasterIFace *Self, xadUINT32 command, xadSignSize data, xadPTR buffer, struct xadArchiveInfo * ai, ...);
	xadERROR APICALL (*xadConvertProtectionA)(struct XadMasterIFace *Self, const struct TagItem * tags);
	xadERROR APICALL (*xadConvertProtection)(struct XadMasterIFace *Self, ...);
	xadERROR APICALL (*xadGetDiskInfoA)(struct XadMasterIFace *Self, struct xadArchiveInfo * ai, const struct TagItem * tags);
	xadERROR APICALL (*xadGetDiskInfo)(struct XadMasterIFace *Self, struct xadArchiveInfo * ai, ...);
	xadERROR APICALL (*xadDiskFileUnArcA)(struct XadMasterIFace *Self, struct xadArchiveInfo * ai, const struct TagItem * tags);
	xadERROR APICALL (*xadDiskFileUnArc)(struct XadMasterIFace *Self, struct xadArchiveInfo * ai, ...);
	xadERROR APICALL (*xadGetHookAccessA)(struct XadMasterIFace *Self, struct xadArchiveInfo * ai, const struct TagItem * tags);
	xadERROR APICALL (*xadGetHookAccess)(struct XadMasterIFace *Self, struct xadArchiveInfo * ai, ...);
	void APICALL (*xadFreeHookAccessA)(struct XadMasterIFace *Self, struct xadArchiveInfo * ai, const struct TagItem * tags);
	void APICALL (*xadFreeHookAccess)(struct XadMasterIFace *Self, struct xadArchiveInfo * ai, ...);
	xadERROR APICALL (*xadAddFileEntryA)(struct XadMasterIFace *Self, struct xadFileInfo * fi, struct xadArchiveInfo * ai, const struct TagItem * tags);
	xadERROR APICALL (*xadAddFileEntry)(struct XadMasterIFace *Self, struct xadFileInfo * fi, struct xadArchiveInfo * ai, ...);
	xadERROR APICALL (*xadAddDiskEntryA)(struct XadMasterIFace *Self, struct xadDiskInfo * di, struct xadArchiveInfo * ai, const struct TagItem * tags);
	xadERROR APICALL (*xadAddDiskEntry)(struct XadMasterIFace *Self, struct xadDiskInfo * di, struct xadArchiveInfo * ai, ...);
	xadERROR APICALL (*xadGetFilenameA)(struct XadMasterIFace *Self, xadUINT32 buffersize, xadSTRPTR buffer, const xadSTRING * path, const xadSTRING * name, const struct TagItem * tags);
	xadERROR APICALL (*xadGetFilename)(struct XadMasterIFace *Self, xadUINT32 buffersize, xadSTRPTR buffer, const xadSTRING * path, const xadSTRING * name, ...);
	xadSTRPTR APICALL (*xadConvertNameA)(struct XadMasterIFace *Self, xadUINT32 charset, const struct TagItem * tags);
	xadSTRPTR APICALL (*xadConvertName)(struct XadMasterIFace *Self, xadUINT32 charset, ...);
	xadSTRPTR APICALL (*xadGetDefaultNameA)(struct XadMasterIFace *Self, const struct TagItem * tags);
	xadSTRPTR APICALL (*xadGetDefaultName)(struct XadMasterIFace *Self, ...);
	const struct xadSystemInfo * APICALL (*xadGetSystemInfo)(struct XadMasterIFace *Self);
};

#ifdef __cplusplus
}
#ifdef __USE_AMIGAOS_NAMESPACE__
}
#endif
#endif

#endif /* XADMASTER_INTERFACE_DEF_H */
