#ifndef Z_INTERFACE_DEF_H
#define Z_INTERFACE_DEF_H

/*
** This file was machine generated by idltool 53.23.
** Do not edit
*/ 

#ifndef EXEC_TYPES_H
#include <exec/types.h>
#endif
#ifndef EXEC_EXEC_H
#include <exec/exec.h>
#endif
#ifndef EXEC_INTERFACES_H
#include <exec/interfaces.h>
#endif

#ifndef LIBRARIES_Z_H
#include <libraries/z.h>
#endif

#ifdef __cplusplus
#ifdef __USE_AMIGAOS_NAMESPACE__
namespace AmigaOS {
#endif
extern "C" {
#endif

struct ZIFace
{
	struct InterfaceData Data;

	uint32 APICALL (*Obtain)(struct ZIFace *Self);
	uint32 APICALL (*Release)(struct ZIFace *Self);
	APTR Expunge_UNIMPLEMENTED;
	APTR Clone_UNIMPLEMENTED;
	int32 APICALL (*DeflateInit)(struct ZIFace *Self, z_stream * strm, int32 level);
	int32 APICALL (*Deflate)(struct ZIFace *Self, z_stream * strm, int32 flush);
	int32 APICALL (*DeflateEnd)(struct ZIFace *Self, z_stream * strm);
	int32 APICALL (*InflateInit)(struct ZIFace *Self, z_stream * strm);
	int32 APICALL (*Inflate)(struct ZIFace *Self, z_stream * strm, int32 flush);
	int32 APICALL (*InflateEnd)(struct ZIFace *Self, z_stream * strm);
	int32 APICALL (*DeflateInit2)(struct ZIFace *Self, z_stream * strm, int32 level, int32 method, int32 windowBits, int32 memLevel, int32 strategy);
	int32 APICALL (*DeflateSetDictionary)(struct ZIFace *Self, z_stream * strm, const uint8 * dictionary, uint32 dictLength);
	int32 APICALL (*DeflateCopy)(struct ZIFace *Self, z_stream * dest, z_stream * source);
	int32 APICALL (*DeflateReset)(struct ZIFace *Self, z_stream * strm);
	int32 APICALL (*DeflateParams)(struct ZIFace *Self, z_stream * strm, int32 level, int32 strategy);
	int32 APICALL (*DeflateTune)(struct ZIFace *Self, z_stream * strm, int32 good_length, int32 max_lazy, int32 nice_length, int32 max_chain);
	uint32 APICALL (*DeflateBound)(struct ZIFace *Self, z_stream * strm, uint32 sourceLen);
	int32 APICALL (*DeflatePrime)(struct ZIFace *Self, z_stream * strm, int32 bits, int32 value);
	int32 APICALL (*DeflateSetHeader)(struct ZIFace *Self, z_stream * strm, gz_header * head);
	int32 APICALL (*InflateInit2)(struct ZIFace *Self, z_stream * strm, int32 windowBits);
	int32 APICALL (*InflateSetDictionary)(struct ZIFace *Self, z_stream * strm, const uint8 * dictionary, uint32 dictLength);
	int32 APICALL (*InflateSync)(struct ZIFace *Self, z_stream * strm);
	int32 APICALL (*InflateCopy)(struct ZIFace *Self, z_stream * dest, z_stream * source);
	int32 APICALL (*InflateReset)(struct ZIFace *Self, z_stream * strm);
	int32 APICALL (*InflatePrime)(struct ZIFace *Self, z_stream * strm, int32 bits, int32 value);
	int32 APICALL (*InflateGetHeader)(struct ZIFace *Self, z_stream * strm, gz_header * head);
	int32 APICALL (*InflateBackInit)(struct ZIFace *Self, z_stream * strm, int32 windowBits, uint8 * window);
	int32 APICALL (*InflateBack)(struct ZIFace *Self, z_stream * strm, in_func in, void * in_desc, out_func out, void * out_desc);
	int32 APICALL (*InflateBackEnd)(struct ZIFace *Self, z_stream * strm);
	uint32 APICALL (*Adler32)(struct ZIFace *Self, uint32 adler, const uint8 * buf, uint32 len);
	uint32 APICALL (*Adler32Combine)(struct ZIFace *Self, uint32 adler1, uint32 adler2, int32 len2);
	uint32 APICALL (*CRC32)(struct ZIFace *Self, uint32 crc, const uint8 * buf, uint32 len);
	uint32 APICALL (*CRC32Combine)(struct ZIFace *Self, uint32 crc1, uint32 crc2, int32 len2);
	CONST_STRPTR APICALL (*ZlibVersion)(struct ZIFace *Self);
	int32 APICALL (*Compress)(struct ZIFace *Self, APTR dest, uint32 * destLen, CONST_APTR source, uint32 sourceLen);
	int32 APICALL (*Uncompress)(struct ZIFace *Self, APTR dest, uint32 * destLen, CONST_APTR source, uint32 sourceLen);
	int32 APICALL (*Compress2)(struct ZIFace *Self, APTR dest, uint32 * destLen, CONST_APTR source, uint32 sourceLen, int32 level);
	uint32 APICALL (*CompressBound)(struct ZIFace *Self, uint32 sourceLen);
	int32 APICALL (*InflateGetDictionary)(struct ZIFace *Self, z_stream * strm, uint8 * dictionary, uint32 * dictLength);
	CONST_STRPTR APICALL (*ZError)(struct ZIFace *Self, int32 err);
	int32 APICALL (*Uncompress2)(struct ZIFace *Self, APTR dest, uint32 * destLen, CONST_APTR source, uint32 * sourceLen);
	int32 APICALL (*InflateReset2)(struct ZIFace *Self, z_stream * strm, int32 windowBits);
	int32 APICALL (*InflateValidate)(struct ZIFace *Self, z_stream * strm, int32 check);
};

#ifdef __cplusplus
}
#ifdef __USE_AMIGAOS_NAMESPACE__
}
#endif
#endif

#endif /* Z_INTERFACE_DEF_H */
