#ifndef CLIB_FREEGLUT_PROTOS_H
#define CLIB_FREEGLUT_PROTOS_H

#include <tgl/types.h>
#include <stdarg.h>

typedef void (*GLUTproc)();

void glutAddMenuEntry(const char *label, int value);
void glutAddSubMenu(const char *label, int subMenu);
void glutAppStatusFunc(void (*callback)(int));
void glutAppStatusFuncUcall(void (*callback)(int, void *), void *user_data);
void glutAttachMenu(int button);
void glutBitmapCharacter(void *font, int character);
int glutBitmapHeight(void *font);
int glutBitmapLength(void *font, const unsigned char *string);
void glutBitmapString(void *font, const unsigned char *string);
int glutBitmapWidth(void *font, int character);
void glutButtonBoxFunc(void (*callback)(int, int));
void glutButtonBoxFuncUcall(void (*callback)(int, int, void *), void *user_data);
void glutChangeToMenuEntry(int item, const char *label, int value);
void glutChangeToSubMenu(int item, const char *label, int value);
void glutCloseFunc(void (*callback)(void));
void glutCloseFuncUcall(void (*callback)(void *), void *user_data);
void glutCopyColormap(int window);
int glutCreateMenu(void (*callback)(int menu));
int glutCreateMenuUcall(void (*callback)(int menu, void *user_data), void *user_data);
int glutCreateSubWindow(int window, int x, int y, int width, int height);
int glutCreateWindow(const char *title);
void glutDestroyMenu(int menu);
void glutDestroyWindow(int window);
void glutDetachMenu(int button);
int glutDeviceGet(GLenum query);
void glutDialsFunc(void (*callback)(int, int));
void glutDialsFuncUcall(void (*callback)(int, int, void *), void *user_data);
void glutDisplayFunc(void (*callback)(void));
void glutDisplayFuncUcall(void (*callback)(void *), void *user_data);
int glutEnterGameMode(void);
void glutEntryFunc(void (*callback)(int));
void glutEntryFuncUcall(void (*callback)(int, void *), void *user_data);
void glutEstablishOverlay(void);
void glutExit (void);
int glutExtensionSupported(const char *extension);
void glutForceJoystickFunc(void);
void glutFullScreen(void);
void glutFullScreenToggle(void);
int glutGameModeGet(GLenum query);
void glutGameModeString(const char *string);
int glutGet(GLenum query);
GLfloat glutGetColor(int color, int component);
int glutGetMenu(void);
void *glutGetMenuData(void);
int *glutGetModeValues(GLenum mode, int *size);
int glutGetModifiers(void);
GLUTproc glutGetProcAddress(const char *procName);
int glutGetWindow(void);
void *glutGetWindowData(void);
void glutHideOverlay(void);
void glutHideWindow(void);
void glutIconifyWindow(void);
void glutIdleFunc(void (*callback)(void));
void glutIdleFuncUcall(void (*callback)(void *), void *user_data);
void glutIgnoreKeyRepeat(int ignore);
void glutInit(int *pargc, char **argv);
void glutInitContextFlags(int flags);
void glutInitContextFunc(void (*callback)(void));
void glutInitContextFuncUcall(void (*callback)(void *), void *user_data);
void glutInitContextProfile(int profile);
void glutInitContextVersion(int majorVersion, int minorVersion);
void glutInitDisplayMode(unsigned int displayMode);
void glutInitDisplayString(const char *displayMode);
void glutInitErrorFunc(void (*callback)(const char *fmt, va_list ap));
void glutInitErrorFuncUcall(void (*callback)(const char *fmt, va_list ap, void *user_data), void *user_data);
void glutInitWarningFunc(void (*callback)(const char *fmt, va_list ap));
void glutInitWarningFuncUcall(void (*callback)(const char *fmt, va_list ap, void *user_data), void *user_data);
void glutInitWindowPosition(int x, int y);
void glutInitWindowSize(int width, int height);
void glutJoystickFunc(void (*callback)(unsigned int, int, int, int), int pollInterval);
void glutJoystickFuncUcall(void (*callback)(unsigned int, int, int, int, void *), int pollInterval, void *user_data);
void glutKeyboardFunc(void (*callback)(unsigned char, int, int));
void glutKeyboardFuncUcall(void (*callback)(unsigned char, int, int, void *), void *user_data);
void glutKeyboardUpFunc(void (*callback)(unsigned char, int, int));
void glutKeyboardUpFuncUcall(void (*callback)(unsigned char, int, int, void *), void *user_data);
int glutLayerGet(GLenum query);
void glutLeaveFullScreen(void);
void glutLeaveGameMode(void);
void glutLeaveMainLoop(void);
void glutMainLoop(void);
void glutMainLoopEvent(void);
void glutMenuDestroyFunc(void (*callback)(void));
void glutMenuDestroyFuncUcall(void (*callback)(void *), void *user_data);
void glutMenuStateFunc(void (*callback)(int));
void glutMenuStatusFunc(void (*callback)(int, int, int));
void glutMenuStatusFuncUcall(void (*callback)(int, int, int, void *), void *user_data);
void glutMorphOSInit(void **tglcontextpointer, void (*exitpointer)(int));
void glutMorphOSInit2(void **tglcontextpointer, void (*exitpointer)(int), unsigned int contextversion);
void glutMotionFunc(void (*callback)(int, int));
void glutMotionFuncUcall(void (*callback)(int, int, void *), void *user_data);
void glutMouseFunc(void (*callback)(int, int, int, int));
void glutMouseFuncUcall(void (*callback)(int, int, int, int, void *), void *user_data);
void glutMouseWheelFunc(void (*callback)(int, int, int, int));
void glutMouseWheelFuncUcall(void (*callback)(int, int, int, int, void *), void *user_data);
void glutMultiButtonFunc(void (*callback)(int, int, int, int, int));
void glutMultiButtonFuncUcall(void (*callback)(int, int, int, int, int, void *), void *user_data);
void glutMultiEntryFunc(void (*callback)(int, int));
void glutMultiEntryFuncUcall(void (*callback)(int, int, void *), void *user_data);
void glutMultiMotionFunc(void (*callback)(int, int, int));
void glutMultiMotionFuncUcall(void (*callback)(int, int, int, void *), void *user_data);
void glutMultiPassiveFunc(void (*callback)(int, int, int));
void glutMultiPassiveFuncUcall(void (*callback)(int, int, int, void *), void *user_data);
void glutOverlayDisplayFunc(void (*callback)(void));
void glutOverlayDisplayFuncUcall(void (*callback)(void *), void *user_data);
void glutPassiveMotionFunc(void (*callback)(int, int));
void glutPassiveMotionFuncUcall(void (*callback)(int, int, void *), void *user_data);
void glutPopWindow(void);
void glutPositionFunc(void (*callback)(int, int));
void glutPositionFuncUcall(void (*callback)(int, int, void *), void *user_data);
void glutPositionWindow(int x, int y);
void glutPostOverlayRedisplay(void);
void glutPostRedisplay(void);
void glutPostWindowOverlayRedisplay(int window);
void glutPostWindowRedisplay(int window);
void glutPushWindow(void);
void glutRemoveMenuItem(int item);
void glutRemoveOverlay(void);
void glutReportErrors(void);
void glutReshapeFunc(void (*callback)(int, int));
void glutReshapeFuncUcall(void (*callback)(int, int, void *), void *user_data);
void glutReshapeWindow(int width, int height);
void glutSetColor(int color, GLfloat red, GLfloat green, GLfloat blue);
void glutSetCursor(int cursor);
void glutSetIconTitle(const char *title);
void glutSetKeyRepeat(int repeatMode);
void glutSetMenu(int menu);
void glutSetMenuData(void *data);
void glutSetMenuFont(int menuID, void *font);
void glutSetOption (GLenum option_flag, int value);
void glutSetVertexAttribCoord3(GLint attrib);
void glutSetVertexAttribNormal(GLint attrib);
void glutSetVertexAttribTexCoord2(GLint attrib);
void glutSetWindow(int window);
void glutSetWindowData(void *data);
void glutSetWindowTitle(const char *title);
void glutSetupVideoResizing(void);
void glutShowOverlay(void);
void glutShowWindow(void);
void glutSolidCone(double base, double height, GLint slices, GLint stacks);
void glutSolidCube(double size);
void glutSolidCylinder(double radius, double height, GLint slices, GLint stacks);
void glutSolidDodecahedron(void);
void glutSolidIcosahedron(void);
void glutSolidOctahedron(void);
void glutSolidRhombicDodecahedron(void);
void glutSolidSierpinskiSponge (int num_levels, double offset[3], double scale);
void glutSolidSphere(double radius, GLint slices, GLint stacks);
void glutSolidTeacup(double size);
void glutSolidTeapot(double size);
void glutSolidTeaspoon(double size);
void glutSolidTetrahedron(void);
void glutSolidTorus(double innerRadius, double outerRadius, GLint sides, GLint rings);
void glutSpaceballButtonFunc(void (*callback)(int, int));
void glutSpaceballButtonFuncUcall(void (*callback)(int, int, void *), void *user_data);
void glutSpaceballMotionFunc(void (*callback)(int, int, int));
void glutSpaceballMotionFuncUcall(void (*callback)(int, int, int, void *), void *user_data);
void glutSpaceballRotateFunc(void (*callback)(int, int, int));
void glutSpaceballRotateFuncUcall(void (*callback)(int, int, int, void *), void *user_data);
void glutSpecialFunc(void (*callback)(int, int, int));
void glutSpecialFuncUcall(void (*callback)(int, int, int, void *), void *user_data);
void glutSpecialUpFunc(void (*callback)(int, int, int));
void glutSpecialUpFuncUcall(void (*callback)(int, int, int, void *), void *user_data);
void glutStopVideoResizing(void);
void glutStrokeCharacter(void *font, int character);
GLfloat glutStrokeHeight(void *font);
int glutStrokeLength(void *font, const unsigned char *string);
GLfloat glutStrokeLengthf(void *font, const unsigned char *string); /*GLUT 3.8 */
void glutStrokeString(void *font, const unsigned char *string);
int glutStrokeWidth(void *font, int character);
GLfloat glutStrokeWidthf(void *font, int character); /*GLUT 3.8 */
void glutSwapBuffers(void);
void glutTabletButtonFunc(void (*callback)(int, int, int, int));
void glutTabletButtonFuncUcall(void (*callback)(int, int, int, int, void *), void *user_data);
void glutTabletMotionFunc(void (*callback)(int, int));
void glutTabletMotionFuncUcall(void (*callback)(int, int, void *), void *user_data);
void glutTimerFunc(unsigned int time, void (*callback)(int), int value);
void glutTimerFuncUcall(unsigned int time, void (*callback)(int, void *), int value, void *user_data);
void glutUseLayer(GLenum layer);
void glutVideoPan(int x, int y, int width, int height);
void glutVideoResize(int x, int y, int width, int height);
int glutVideoResizeGet(GLenum query);
void glutVisibilityFunc(void (*callback)(int));
void glutVisibilityFuncUcall(void (*callback)(int, void *), void *user_data);
void glutWMCloseFunc(void (*callback)(void));
void glutWMCloseFuncUcall(void (*callback)(void *), void *user_data);
void glutWarpPointer(int x, int y);
void glutWindowStatusFunc(void (*callback)(int));
void glutWindowStatusFuncUcall(void (*callback)(int, void *), void *user_data);
void glutWireCone(double base, double height, GLint slices, GLint stacks);
void glutWireCube(double size);
void glutWireCylinder(double radius, double height, GLint slices, GLint stacks);
void glutWireDodecahedron(void);
void glutWireIcosahedron(void);
void glutWireOctahedron(void);
void glutWireRhombicDodecahedron(void);
void glutWireSierpinskiSponge (int num_levels, double offset[3], double scale);
void glutWireSphere(double radius, GLint slices, GLint stacks);
void glutWireTeacup(double size);
void glutWireTeapot(double size);
void glutWireTeaspoon(double size);
void glutWireTetrahedron(void);
void glutWireTorus(double innerRadius, double outerRadius, GLint sides, GLint rings);

#endif /* CLIB_FREEGLUT_PROTOS_H */
