#ifndef CLIB_TINYGL_PROTOS_H
#define CLIB_TINYGL_PROTOS_H

#include <utility/tagitem.h>

#include <tgl/types.h>

#ifdef __cplusplus
extern "C" {
#endif /* __cplusplus */

void GLEnable(GLContext *context, GLenum cap);
void GLDisable(GLContext *context, GLenum cap);
GLboolean GLIsEnabled(GLContext *context, GLenum cap);
void GLShadeModel(GLContext *context, GLenum mode);
void GLCullFace(GLContext *context, GLenum mode);
void GLPolygonMode(GLContext *context, GLenum face, GLenum mode);
void GLBegin(GLContext *context, GLenum mode);
void GLEnd(GLContext *context);
void GLVertex3f(GLContext *context, GLfloat x, GLfloat y, GLfloat z);
void GLVertex4f(GLContext *context, GLfloat x, GLfloat y, GLfloat z, GLfloat w);
void GLVertex3fv(GLContext *context, const GLfloat *v);
void GLVertex4fv(GLContext *context, const GLfloat *v);
void GLColor3f(GLContext *context, GLfloat red, GLfloat green, GLfloat blue);
void GLColor4f(GLContext *context, GLfloat red, GLfloat green, GLfloat blue, GLfloat alpha);
void GLColor3fv(GLContext *context, const GLfloat *v);
void GLColor4fv(GLContext *context, const GLfloat *v);
void GLColor3ub(GLContext *context, GLubyte red, GLubyte green, GLubyte blue);
void GLColor4ub(GLContext *context, GLubyte red, GLubyte green, GLubyte blue, GLubyte alpha);
void GLColor3ubv(GLContext *context, const GLubyte *v);
void GLColor4ubv(GLContext *context, const GLubyte *v);
void GLNormal3f(GLContext *context, GLfloat nx, GLfloat ny, GLfloat nz);
void GLNormal3fv(GLContext *context, const GLfloat *v);
void GLTexCoord2f(GLContext *context, GLfloat s, GLfloat t);
void GLTexCoord2fv(GLContext *context, const GLfloat *v);
void GLMultiTexCoord2f(GLContext *context, GLenum target, GLfloat s, GLfloat t);
void GLMultiTexCoord2fv(GLContext *context, GLenum target, const GLfloat *v);
void GLEdgeFlag(GLContext *context, GLboolean flag);
void GLMatrixMode(GLContext *context, GLenum mode);
void GLLoadMatrixf(GLContext *context, const GLfloat *m);
void GLLoadIdentity(GLContext *context);
void GLMultMatrixf(GLContext *context, const GLfloat *m);
void GLPushMatrix(GLContext *context);
void GLPopMatrix(GLContext *context);
void GLRotatef(GLContext *context, GLfloat angle, GLfloat x, GLfloat y, GLfloat z);
void GLTranslatef(GLContext *context, GLfloat x, GLfloat y, GLfloat z);
void GLScalef(GLContext *context, GLfloat x, GLfloat y, GLfloat z);
void GLViewportOld(GLContext *c, GLfloat xmin, GLfloat ymin, GLfloat xsize, GLfloat ysize);
void GLFrustum(GLContext *context, GLdouble left, GLdouble right, GLdouble bottom, GLdouble top, GLdouble zNear, GLdouble zFar);
void GLOrtho(GLContext *context, GLdouble left, GLdouble right, GLdouble bottom, GLdouble top, GLdouble zNear, GLdouble zFar);
GLuint GLGenLists(GLContext *context, GLsizei range);
GLboolean GLIsList(GLContext *context, GLuint list);
void GLNewList(GLContext *context, GLuint list, GLenum mode);
void GLEndList(GLContext *context);
void GLCallList(GLContext *context, GLuint list);
void GLDeleteLists(GLContext *context, GLuint list, GLsizei range);
void GLClear(GLContext *context, GLbitfield mask);
void GLClearColor(GLContext *context, GLfloat red, GLfloat green, GLfloat blue, GLfloat alpha);
void GLClearDepth(GLContext *context, GLdouble depth);
GLint GLRenderMode(GLContext *context, GLenum mode);
void GLSelectBuffer(GLContext *context, GLsizei size, GLuint *buffer);
void GLInitNames(GLContext *context);
void GLPushName(GLContext *context, GLuint name);
void GLPopName(GLContext *context);
void GLLoadName(GLContext *context, GLuint name);
void GLGenTextures(GLContext *context, GLsizei n, GLuint *textures);
void GLDeleteTextures(GLContext *context, GLsizei n, const GLuint *textures);
void GLBindTexture(GLContext *context, GLenum target, GLuint texture);
void GLTexImage2D(GLContext *context, GLenum target, GLint level, GLint internalformat, GLsizei width, GLsizei height, GLint border, GLenum format, GLenum type, const void *pixels);
void GLTexSubImage2D(GLContext *context, GLenum target, GLint level, GLint xoffset, GLint yoffset, GLsizei width, GLsizei height, GLenum format, GLenum type, const void *pixels);
void GLTexEnvi(GLContext *context, GLenum target, GLenum pname, GLint param);
void GLTexEnvf(GLContext *context, GLenum target, GLenum pname, GLfloat param);
void GLTexParameteri(GLContext *context, GLenum target, GLenum pname, GLint param);
void GLTexParameterf(GLContext *context, GLenum target, GLenum pname, GLfloat param);
void GLPixelStorei(GLContext *context, GLenum pname, GLint param);
void GLActiveTexture(GLContext *context, GLenum texture);
void GLTexGeni(GLContext *context, GLenum coord, GLenum pname, GLint param);
void GLTexGenfv(GLContext *context, GLenum coord, GLenum pname, const GLfloat *params);
void GLMaterialfv(GLContext *context, GLenum face, GLenum pname, const GLfloat *params);
void GLMaterialf(GLContext *context, GLenum face, GLenum pname, GLfloat param);
void GLColorMaterial(GLContext *context, GLenum face, GLenum mode);
void GLLightfv(GLContext *context, GLenum light, GLenum pname, const GLfloat *params);
void GLLightf(GLContext *context, GLenum light, GLenum pname, GLfloat param);
void GLLightModeli(GLContext *context, GLenum pname, GLint param);
void GLLightModelfv(GLContext *context, GLenum pname, const GLfloat *params);
void GLLightModelf(GLContext *context, GLenum pname, GLfloat param);
void GLFlush(GLContext *context);
void GLHint(GLContext *context, GLenum target, GLenum mode);
void GLGetIntegerv(GLContext *context, GLenum pname, GLint *data);
void GLGetFloatv(GLContext *context, GLenum pname, GLfloat *data);
void GLFrontFace(GLContext *context, GLenum mode);
void GLEnableClientState(GLContext *context, GLenum array);
void GLDisableClientState(GLContext *context, GLenum array);
void GLArrayElement(GLContext *context, GLint i);
void GLVertexPointer(GLContext *context, GLint size, GLenum type, GLsizei stride, const void *pointer);
void GLColorPointer(GLContext *context, GLint size, GLenum type, GLsizei stride, const void *pointer);
void GLNormalPointer(GLContext *context, GLenum type, GLsizei stride, const void *pointer);
void GLTexCoordPointer(GLContext *context, GLint size, GLenum type, GLsizei stride, const void *pointer);
void GLLockArraysEXT(GLContext *context, GLint first, GLsizei count);
void GLUnlockArraysEXT(GLContext *context);
void GLDrawElements(GLContext *context, GLenum mode, GLsizei count, GLenum type, const void *indices);
void GLDrawArrays(GLContext *context, GLenum mode, GLint first, GLsizei count);
void GLClientActiveTexture(GLContext *context, GLenum texture);
void GLPolygonOffset(GLContext *context, GLfloat factor, GLfloat units);
void GLBlendFunc(GLContext *context, GLenum sfactor, GLenum dfactor);
void GLDepthMask(GLContext *context, GLboolean flag);
void GLAlphaFunc(GLContext *context, GLenum func, GLfloat ref);
void GLPointSize(GLContext *context, GLfloat size);
void GLPointParameterf(GLContext *context, GLenum pname, GLfloat param);
void GLPointParameterfv(GLContext *context, GLenum pname, const GLfloat *params);
void GLDepthRange(GLContext *context, GLdouble n, GLdouble f);
void GLDepthFunc(GLContext *context, GLenum func);
void *TGLGetContexts(void);
GLContext *GLInit(void);
void GLClose(GLContext *context);
void GLUPerspective(GLContext *c, GLfloat fovy, GLfloat aspect, GLfloat znear, GLfloat zfar);
void GLULookAt(GLContext *context, GLfloat cx, GLfloat cy, GLfloat cz, GLfloat ox, GLfloat oy, GLfloat oz, GLfloat ux, GLfloat uy, GLfloat uz);
void GLUTInit(GLContext *context , int *argcp, char *argv[]);
void GLUTInitWindowPosition(GLContext *context, int x, int y);
void GLUTInitWindowSize(GLContext *context, int width, int height);
int GLUTCreateWindow(GLContext *context , char *name);
void GLUTFullScreen(GLContext *context);
void GLUTSetWindow(GLContext *context, int win);
int GLUTGetWindow(GLContext *context);
void GLUTDestroyWindow(GLContext *context, int win);
void GLUTSwapBuffers(GLContext *context);
void GLUTMainLoop(GLContext *context);
void GLUTPostRedisplay(GLContext *context);
void GLUTDisplayFunc(GLContext *context , void (*func)(void));
void GLUTReshapeFunc(GLContext *context, void (*func)(int width, int height));
void GLUTIdleFunc(GLContext *context , void (*func)(void));
void GLUTKeyboardFunc(GLContext *context, void (*func)(unsigned char key, int x, int y));
void GLUTKeyboardUpFunc(GLContext *context, void (*func)(unsigned char key, int x, int y));
void GLUTMouseFunc(GLContext *context, void (*func)(int button, int state, int x, int y));
void GLUTMotionFunc(GLContext *context, void (*func)(int x, int y));
void GLUTEntryFunc(GLContext *context, void (*func)(int state));
void GLUTShowWindow(GLContext *context);
void GLUTHideWindow(GLContext *context);
void GLUTPositionWindow(GLContext *context, int x, int y);
void GLUTReshapeWindow(GLContext *context, int newwidth, int newheight);
int GLUTGet(GLContext *context, GLenum state);
void GLUTInitDisplayMode(GLContext *context, unsigned int mode);
void GLUTSpecialFunc(GLContext *context, void (*func)(int key, int x, int y));
void GLUTTimerFunc(GLContext *context, int msecs, void (*func)(int value), int value);
int GLUTGetModifiers(GLContext *context);
void GLUTPassiveMotionFunc(GLContext *context, void (*func)(int x, int y));
int GLAInitializeContextWindowed(GLContext *context, void *w);
void GLADestroyContextWindowed(GLContext *context);
void GLASwapBuffers(GLContext *c);
void *GLUTGetWindowHandle(GLContext *context);
const GLubyte *GLGetString(GLContext *context, GLenum name);
void GLPushAttrib(GLContext *context, GLbitfield mask);
void GLPopAttrib(GLContext *context);
void GLScissor(GLContext *context, GLint x, GLint y, GLsizei width, GLsizei height);
void GLListBase(GLContext *context, GLuint base);
void GLCallLists(GLContext *context, GLsizei n, GLenum type, const void *lists);
void GLGetDoublev(GLContext *context, GLenum pname, GLdouble *data);
void GLUTSpecialUpFunc(GLContext *context, void (*func)(int key, int x, int y));
void GLLineWidth(GLContext *context, GLfloat width);
void GLRectf(GLContext *context, GLfloat x1, GLfloat y1, GLfloat x2, GLfloat y2);
void GLRectfv(GLContext *context, const GLfloat *v1, const GLfloat *v2);
void GLRectiv(GLContext *context, const GLint *v1, const GLint *v2);
void GLRectdv(GLContext *context, const GLdouble *v1, const GLdouble *v2);
void GLEvalPoint1(GLContext *context, GLint i);
void GLEvalPoint2(GLContext *context, GLint i, GLint j);
void GLEvalCoord1f(GLContext *context, GLfloat u);
void GLEvalCoord2f(GLContext *context, GLfloat u, GLfloat v);
void GLEvalCoord1fv(GLContext *context, const GLfloat *u);
void GLEvalCoord2fv(GLContext *context, const GLfloat *u);
void GLEvalMesh1(GLContext *context, GLenum mode, GLint i1, GLint i2);
void GLEvalMesh2(GLContext *context, GLenum mode, GLint i1, GLint i2, GLint j1, GLint j2);
void GLMap1f(GLContext *context, GLenum target, GLfloat u1, GLfloat u2, GLint stride, GLint order, const GLfloat *points);
void GLMap1d(GLContext *context, GLenum target, GLdouble u1, GLdouble u2, GLint stride, GLint order, const GLdouble *points);
void GLMap2f(GLContext *context, GLenum target, GLfloat u1, GLfloat u2, GLint ustride, GLint uorder, GLfloat v1, GLfloat v2, GLint vstride, GLint vorder, const GLfloat *points);
void GLMap2d(GLContext *context, GLenum target, GLdouble u1, GLdouble u2, GLint ustride, GLint uorder, GLdouble v1, GLdouble v2, GLint vstride, GLint vorder, const GLdouble *points);
void GLGetMapdv(GLContext *context, GLenum target, GLenum query, GLdouble *v);
void GLGetMapfv(GLContext *context, GLenum target, GLenum query, GLfloat *v);
void GLGetMapiv(GLContext *context, GLenum target, GLenum query, GLint *v);
void GLMapGrid1f(GLContext *context, GLint un, GLfloat u1, GLfloat u2);
void GLMapGrid1d(GLContext *context, GLint un, GLdouble u1, GLdouble u2);
void GLMapGrid2f(GLContext *context, GLint un, GLfloat u1, GLfloat u2, GLint vn, GLfloat v1, GLfloat v2);
void GLMapGrid2d(GLContext *context, GLint un, GLdouble u1, GLdouble u2, GLint vn, GLdouble v1, GLdouble v2);
void GLMultMatrixd(GLContext *context, const GLdouble *m);
int GLAInitializeContextScreen(GLContext *context, void *s);
void GLADestroyContextScreen(GLContext *context);
int GLAInitializeContextBitMap(GLContext *context, void *b);
void GLADestroyContextBitMap(GLContext *context);
void GLColorTable(GLContext *context, GLenum target, GLenum internalformat, GLsizei width, GLenum format, GLenum type, const void *table);
void GLRasterPos2f(GLContext *context, GLfloat x, GLfloat y);
void GLWindowPos2f(GLContext *context, GLfloat x, GLfloat y);
void GLBitmap(GLContext *context, GLsizei width, GLsizei height, GLfloat xorig, GLfloat yorig, GLfloat xmove, GLfloat ymove, const GLubyte *bitmap);
void GLRasterPos3f(GLContext *context, GLfloat x, GLfloat y, GLfloat z);
void GLUTVisibilityFunc(GLContext *context, void (*func)(int state));
void GLFogf(GLContext *context, GLenum pname, GLfloat param);
void GLFogfv(GLContext *context, GLenum pname, const GLfloat *params);
void GLASetSync(GLContext *context, int enable);
void GLLoadMatrixd(GLContext *context, const GLdouble *m);
void GLVertex3dv(GLContext *context, const GLdouble *v);
void GLVertex4dv(GLContext *context, const GLdouble *v);
void GLTexCoord2dv(GLContext *context, const GLdouble *v);
void GLMultiTexCoord2dv(GLContext *context, GLenum target, const GLdouble *v);
void GLColor3dv(GLContext *context, const GLdouble *v);
void GLColor4dv(GLContext *context, const GLdouble *v);
void GLReadPixels(GLContext *context, GLint x, GLint y, GLsizei width, GLsizei height, GLenum format, GLenum type, void *pixels);
int GLAReinitializeContextWindowed(GLContext *context, void *w);
GLboolean GLIsTexture(GLContext *context, GLuint texture);
void GLGetTexLevelParameteriv(GLContext *context, GLenum target, GLint level, GLenum pname, GLint *params);
void GLGetTexImage(GLContext *context, GLenum target, GLint level, GLenum format, GLenum type, void *pixels);
void GLStencilFunc(GLContext *context, GLenum func, GLint ref, GLuint mask);
void GLStencilOp(GLContext *context, GLenum fail, GLenum zfail, GLenum zpass);
void GLStencilMask(GLContext *context, GLuint mask);
void GLClearStencil(GLContext *context, GLint s);
void GLADestroyContext(GLContext *context);
int GLAInitializeContext(GLContext *context, struct TagItem *tags);
void GLGetLightfv(GLContext *context, GLenum light, GLenum pname, GLfloat *params);
void GLReadBuffer(GLContext *context, GLenum src);
GLenum GLGetError(GLContext *context);
void GLTexCoord2iv(GLContext *context, const GLint *v);
void GLClipPlane(GLContext *context, GLenum plane, const GLdouble *equation);
void GLTexCoord3f(GLContext *context, GLfloat s, GLfloat t, GLfloat r);
void GLColorMask(GLContext *context, GLboolean red, GLboolean green, GLboolean blue, GLboolean alpha);
void GLMultiTexCoord3f(GLContext *context, GLenum target, GLfloat s, GLfloat t, GLfloat r);
void GLMultiTexCoord3fv(GLContext *context, GLenum target, const GLfloat *v);
void GLDrawPixels(GLContext *context, GLsizei width, GLsizei height, GLenum format, GLenum type, const void *pixels);
void GLRasterPos2fv(GLContext *context, const GLfloat *v);
void GLRasterPos3fv(GLContext *context, const GLfloat *v);
void GLNormal3sv(GLContext *context, const GLshort *v);
void GLNormal3s(GLContext *context, GLshort nx, GLshort ny, GLshort nz);
void GLPixelTransferi(GLContext *context, GLenum pname, GLint param);
void GLPixelTransferf(GLContext *context, GLenum pname, GLfloat param);
void GLPixelZoom(GLContext *context, GLfloat xfactor, GLfloat yfactor);
void GLUPickMatrix(GLContext *c, GLfloat x, GLfloat y, GLfloat width, GLfloat height, GLint viewport[4]);
void GLDrawBuffer(GLContext *context, GLenum buf);
void GLNormal3dv(GLContext *context, const GLdouble *v);
void GLPushClientAttrib(GLContext *context, GLbitfield mask);
void GLPopClientAttrib(GLContext *context);
void GLLineStipple(GLContext *context, GLint factor, GLushort pattern);
void GLCopyPixels(GLContext *context, GLint x, GLint y, GLsizei width, GLsizei height, GLenum type);
void GLTexEnvfv(GLContext *context, GLenum target, GLenum pname, const GLfloat *params);
void GLDrawRangeElements(GLContext *context, GLenum mode, GLuint start, GLuint end, GLsizei count, GLenum type, const void *indices);
void GLCopyTexImage2D(GLContext *context, GLenum target, GLint level, GLenum internalformat, GLint x, GLint y, GLsizei width, GLsizei height, GLint border);
void GLCopyTexSubImage2D(GLContext *context, GLenum target, GLint level, GLint xoffset, GLint yoffset, GLint x, GLint y, GLsizei width, GLsizei height);
void GLASetAttr(GLContext *context, unsigned int attr, unsigned int value);
void GLMultiTexCoord4f(GLContext *context, GLenum target, GLfloat s, GLfloat t, GLfloat r, GLfloat q);
void GLMultiTexCoord4fv(GLContext *context, GLenum target, const GLfloat *v);
void GLAttachShader(GLContext *context, GLuint program, GLuint shader);
void GLCompileShader(GLContext *context, GLuint shader);
void GLLinkProgram(GLContext *context, GLuint program);
GLuint GLCreateShader(GLContext *context, GLenum type);
void GLShaderSource(GLContext *context, GLuint shader, GLsizei count, const GLchar *const*string, const GLint *length);
void GLValidateProgram(GLContext *context, GLuint program);
GLuint GLCreateProgram(GLContext *context);
void GLTexImage1D(GLContext *context, GLenum target, GLint level, GLint internalformat, GLsizei width, GLint border, GLenum format, GLenum type, const void *pixels);
void GLTexSubImage1D(GLContext *context, GLenum target, GLint level, GLint xoffset, GLsizei width, GLenum format, GLenum type, const void *pixels);
void GLPrioritizeTextures(GLContext *context, GLsizei n, const GLuint *textures, const GLfloat *priorities);
void GLGetClipPlane(GLContext *context, GLenum plane, GLdouble *equation);
void GLTexCoord1dv(GLContext *context, const GLdouble *v);
void GLTexCoord3dv(GLContext *context, const GLdouble *v);
void GLTexCoord4dv(GLContext *context, const GLdouble *v);
void GLGetMaterialfv(GLContext *context, GLenum face, GLenum pname, GLfloat *params);
void GLGetPointerv(GLContext *context, GLenum pname, void **params);
void GLGetTexEnvfv(GLContext *context, GLenum target, GLenum pname, GLfloat *params);
void GLGetTexEnviv(GLContext *context, GLenum target, GLenum pname, GLint *params);
void GLGetTexParameterfv(GLContext *context, GLenum target, GLenum pname, GLfloat *params);
void GLGetTexParameteriv(GLContext *context, GLenum target, GLenum pname, GLint *params);
void GLGenBuffers(GLContext *context, GLsizei n, GLuint *buffers);
void GLBindBuffer(GLContext *context, GLenum target, GLuint buffer);
void GLBufferData(GLContext *context, GLenum target, GLsizeiptr size, const void *data, GLenum usage);
void GLBufferSubData(GLContext *context, GLenum target, GLintptr offset, GLsizeiptr size, const void *data);
void GLDeleteBuffers(GLContext *context, GLsizei n, const GLuint *buffers);
void GLGetBufferParameteriv(GLContext *context, GLenum target, GLenum pname, GLint *params);
void GLUniform1f(GLContext *context, GLint location, GLfloat v0);
void GLUniform2f(GLContext *context, GLint location, GLfloat v0, GLfloat v1);
void GLUniform3f(GLContext *context, GLint location, GLfloat v0, GLfloat v1, GLfloat v2);
void GLUniform4f(GLContext *context, GLint location, GLfloat v0, GLfloat v1, GLfloat v2, GLfloat v3);
void GLUniform4fv(GLContext *context, GLint location, GLsizei count, const GLfloat *value);
void GLUniformMatrix4fv(GLContext *context, GLint location, GLsizei count, GLboolean transpose, const GLfloat *value);
GLint GLGetUniformLocation(GLContext *context, GLuint program, const GLchar *name);
GLint GLGetAttribLocation(GLContext *context, GLuint program, const GLchar *name);
void GLVertexAttribPointer(GLContext *context, GLuint index, GLint size, GLenum type, GLboolean normalized, GLsizei stride, const void *pointer);
void GLEnableVertexAttribArray(GLContext *context, GLuint index);
void GLDisableVertexAttribArray(GLContext *context, GLuint index);
void GLUseProgram(GLContext *context, GLuint program);
void GLUniform1i(GLContext *context, GLint location, GLint v0);
void GLGetShaderiv(GLContext *context, GLuint shader, GLenum pname, GLint *params);
void GLGetProgramiv(GLContext *context, GLuint program, GLenum pname, GLint *params);
void GLGetShaderInfoLog(GLContext *context, GLuint shader, GLsizei bufSize, GLsizei *length, GLchar *infoLog);
void GLGetProgramInfoLog(GLContext *context, GLuint program, GLsizei bufSize, GLsizei *length, GLchar *infoLog);
void GLBlendEquation(GLContext *context, GLenum mode);
void GLBlendColor(GLContext *context, GLfloat red, GLfloat green, GLfloat blue, GLfloat alpha);
void GLBlendEquationSeparate(GLContext *context, GLenum modeRGB, GLenum modeAlpha);
void GLBlendFuncSeparate(GLContext *context, GLenum sfactorRGB, GLenum dfactorRGB, GLenum sfactorAlpha, GLenum dfactorAlpha);
void GLUniform1i(GLContext *context, GLint location, GLint v0);
void GLUniform1iv(GLContext *context, GLint location, GLsizei count, const GLint *value);
void GLUniform1ui(GLContext *context, GLint location, GLuint v0);
void GLUniform1uiv(GLContext *context, GLint location, GLsizei count, const GLuint *value);
void GLUniform1fv(GLContext *context, GLint location, GLsizei count, const GLfloat *value);
void GLUniform2i(GLContext *context, GLint location, GLint v0, GLint v1);
void GLUniform2iv(GLContext *context, GLint location, GLsizei count, const GLint *value);
void GLUniform2ui(GLContext *context, GLint location, GLuint v0, GLuint v1);
void GLUniform2uiv(GLContext *context, GLint location, GLsizei count, const GLuint *value);
void GLUniform2fv(GLContext *context, GLint location, GLsizei count, const GLfloat *value);
void GLUniform3i(GLContext *context, GLint location, GLint v0, GLint v1, GLint v2);
void GLUniform3iv(GLContext *context, GLint location, GLsizei count, const GLint *value);
void GLUniform3ui(GLContext *context, GLint location, GLuint v0, GLuint v1, GLuint v2);
void GLUniform3uiv(GLContext *context, GLint location, GLsizei count, const GLuint *value);
void GLUniform3fv(GLContext *context, GLint location, GLsizei count, const GLfloat *value);
void GLUniform4i(GLContext *context, GLint location, GLint v0, GLint v1, GLint v2, GLint v3);
void GLUniform4iv(GLContext *context, GLint location, GLsizei count, const GLint *value);
void GLUniform4ui(GLContext *context, GLint location, GLuint v0, GLuint v1, GLuint v2, GLuint v3);
void GLUniform4uiv(GLContext *context, GLint location, GLsizei count, const GLuint *value);
void GLUniformMatrix2fv(GLContext *context, GLint location, GLsizei count, GLboolean transpose, const GLfloat *value);
void GLUniformMatrix2x3fv(GLContext *context, GLint location, GLsizei count, GLboolean transpose, const GLfloat *value);
void GLUniformMatrix2x4fv(GLContext *context, GLint location, GLsizei count, GLboolean transpose, const GLfloat *value);
void GLUniformMatrix3fv(GLContext *context, GLint location, GLsizei count, GLboolean transpose, const GLfloat *value);
void GLUniformMatrix3x2fv(GLContext *context, GLint location, GLsizei count, GLboolean transpose, const GLfloat *value);
void GLUniformMatrix3x4fv(GLContext *context, GLint location, GLsizei count, GLboolean transpose, const GLfloat *value);
void GLUniformMatrix4x2fv(GLContext *context, GLint location, GLsizei count, GLboolean transpose, const GLfloat *value);
void GLUniformMatrix4x3fv(GLContext *context, GLint location, GLsizei count, GLboolean transpose, const GLfloat *value);
void GLLoadTransposeMatrixf(GLContext *context, const GLfloat *m);
void GLLoadTransposeMatrixd(GLContext *context, const GLdouble *m);
void GLMultTransposeMatrixf(GLContext *context, const GLfloat *m);
void GLMultTransposeMatrixd(GLContext *context, const GLdouble *m);
void GLTexParameteriv(GLContext *context, GLenum target, GLenum pname, const GLint *params);
void GLTexParameterfv(GLContext *context, GLenum target, GLenum pname, const GLfloat *params);
void GLViewport(GLContext *context, GLint x, GLint y, GLsizei width, GLsizei height);
void GLAccum(GLContext *context, GLenum op, GLfloat value);
void GLActiveStencilFaceEXT(GLContext *context, GLenum face);
GLboolean GLAreTexturesResident(GLContext *context, GLsizei n, const GLuint *textures, GLboolean *residences);
void GLBeginQuery(GLContext *context, GLenum target, GLuint id);
void GLBindAttribLocation(GLContext *context, GLuint program, GLuint index, const GLchar *name);
void GLBindFramebuffer(GLContext *context, GLenum target, GLuint framebuffer);
void GLBindProgramARB(GLContext *context, GLenum target, GLuint program);
void GLBindRenderbuffer(GLContext *context, GLenum target, GLuint renderbuffer);
void GLBlitFramebuffer(GLContext *context, GLint srcX0, GLint srcY0, GLint srcX1, GLint srcY1, GLint dstX0, GLint dstY0, GLint dstX1, GLint dstY1, GLbitfield mask, GLenum filter);
GLenum GLCheckFramebufferStatus(GLContext *context, GLenum target);
void GLClearAccum(GLContext *context, GLfloat red, GLfloat green, GLfloat blue, GLfloat alpha);
void GLClearIndex(GLContext *context, GLfloat c);
void GLColor3b(GLContext *context, GLbyte red, GLbyte green, GLbyte blue);
void GLColor3bv(GLContext *context, const GLbyte *v);
void GLColor3d(GLContext *context, GLdouble red, GLdouble green, GLdouble blue);
void GLColor3i(GLContext *context, GLint red, GLint green, GLint blue);
void GLColor3iv(GLContext *context, const GLint *v);
void GLColor3s(GLContext *context, GLshort red, GLshort green, GLshort blue);
void GLColor3sv(GLContext *context, const GLshort *v);
void GLColor3ui(GLContext *context, GLuint red, GLuint green, GLuint blue);
void GLColor3uiv(GLContext *context, const GLuint *v);
void GLColor3us(GLContext *context, GLushort red, GLushort green, GLushort blue);
void GLColor3usv(GLContext *context, const GLushort *v);
void GLColor4b(GLContext *context, GLbyte red, GLbyte green, GLbyte blue, GLbyte alpha);
void GLColor4bv(GLContext *context, const GLbyte *v);
void GLColor4d(GLContext *context, GLdouble red, GLdouble green, GLdouble blue, GLdouble alpha);
void GLColor4i(GLContext *context, GLint red, GLint green, GLint blue, GLint alpha);
void GLColor4iv(GLContext *context, const GLint *v);
void GLColor4s(GLContext *context, GLshort red, GLshort green, GLshort blue, GLshort alpha);
void GLColor4sv(GLContext *context, const GLshort *v);
void GLColor4ui(GLContext *context, GLuint red, GLuint green, GLuint blue, GLuint alpha);
void GLColor4uiv(GLContext *context, const GLuint *v);
void GLColor4us(GLContext *context, GLushort red, GLushort green, GLushort blue, GLushort alpha);
void GLColor4usv(GLContext *context, const GLushort *v);
void GLColorSubTable(GLContext *context, GLenum target, GLsizei start, GLsizei count, GLenum format, GLenum type, const void *data);
void GLColorTableParameterfv(GLContext *context, GLenum target, GLenum pname, const GLfloat *params);
void GLColorTableParameteriv(GLContext *context, GLenum target, GLenum pname, const GLint *params);
void GLCompressedTexImage1D(GLContext *context, GLenum target, GLint level, GLenum internalformat, GLsizei width, GLint border, GLsizei imageSize, const void *data);
void GLCompressedTexImage2D(GLContext *context, GLenum target, GLint level, GLenum internalformat, GLsizei width, GLsizei height, GLint border, GLsizei imageSize, const void *data);
void GLCompressedTexImage3D(GLContext *context, GLenum target, GLint level, GLenum internalformat, GLsizei width, GLsizei height, GLsizei depth, GLint border, GLsizei imageSize, const void *data);
void GLCompressedTexSubImage1D(GLContext *context, GLenum target, GLint level, GLint xoffset, GLsizei width, GLenum format, GLsizei imageSize, const void *data);
void GLCompressedTexSubImage2D(GLContext *context, GLenum target, GLint level, GLint xoffset, GLint yoffset, GLsizei width, GLsizei height, GLenum format, GLsizei imageSize, const void *data);
void GLCompressedTexSubImage3D(GLContext *context, GLenum target, GLint level, GLint xoffset, GLint yoffset, GLint zoffset, GLsizei width, GLsizei height, GLsizei depth, GLenum format, GLsizei imageSize, const void *data);
void GLConvolutionFilter1D(GLContext *context, GLenum target, GLenum internalformat, GLsizei width, GLenum format, GLenum type, const void *image);
void GLConvolutionFilter2D(GLContext *context, GLenum target, GLenum internalformat, GLsizei width, GLsizei height, GLenum format, GLenum type, const void *image);
void GLConvolutionParameterf(GLContext *context, GLenum target, GLenum pname, GLfloat params);
void GLConvolutionParameterfv(GLContext *context, GLenum target, GLenum pname, const GLfloat *params);
void GLConvolutionParameteri(GLContext *context, GLenum target, GLenum pname, GLint params);
void GLConvolutionParameteriv(GLContext *context, GLenum target, GLenum pname, const GLint *params);
void GLCopyColorSubTable(GLContext *context, GLenum target, GLsizei start, GLint x, GLint y, GLsizei width);
void GLCopyColorTable(GLContext *context, GLenum target, GLenum internalformat, GLint x, GLint y, GLsizei width);
void GLCopyConvolutionFilter1D(GLContext *context, GLenum target, GLenum internalformat, GLint x, GLint y, GLsizei width);
void GLCopyConvolutionFilter2D(GLContext *context, GLenum target, GLenum internalformat, GLint x, GLint y, GLsizei width, GLsizei height);
void GLCopyTexImage1D(GLContext *context, GLenum target, GLint level, GLenum internalformat, GLint x, GLint y, GLsizei width, GLint border);
void GLCopyTexSubImage1D(GLContext *context, GLenum target, GLint level, GLint xoffset, GLint x, GLint y, GLsizei width);
void GLCopyTexSubImage3D(GLContext *context, GLenum target, GLint level, GLint xoffset, GLint yoffset, GLint zoffset, GLint x, GLint y, GLsizei width, GLsizei height);
void GLCurrentPaletteMatrixARB(GLContext *context, GLint index);
void GLDeleteFramebuffers(GLContext *context, GLsizei n, const GLuint *framebuffers);
void GLDeleteObjectARB(GLContext *context, GLhandleARB obj);
void GLDeleteProgram(GLContext *context, GLuint program);
void GLDeleteProgramsARB(GLContext *context, GLsizei n, const GLuint *programs);
void GLDeleteQueries(GLContext *context, GLsizei n, const GLuint *ids);
void GLDeleteRenderbuffers(GLContext *context, GLsizei n, const GLuint *renderbuffers);
void GLDeleteShader(GLContext *context, GLuint shader);
void GLDetachShader(GLContext *context, GLuint program, GLuint shader);
void GLDrawBuffers(GLContext *context, GLsizei n, const GLenum *bufs);
void GLEdgeFlagPointer(GLContext *context, GLsizei stride, const void *pointer);
void GLEdgeFlagv(GLContext *context, const GLboolean *flag);
void GLEndQuery(GLContext *context, GLenum target);
void GLEvalCoord1d(GLContext *context, GLdouble u);
void GLEvalCoord1dv(GLContext *context, const GLdouble *u);
void GLEvalCoord2d(GLContext *context, GLdouble u, GLdouble v);
void GLEvalCoord2dv(GLContext *context, const GLdouble *u);
void GLFeedbackBuffer(GLContext *context, GLsizei size, GLenum type, GLfloat *buffer);
void GLFinish(GLContext *context);
void GLFogCoordPointer(GLContext *context, GLenum type, GLsizei stride, const void *pointer);
void GLFogCoordd(GLContext *context, GLdouble coord);
void GLFogCoorddv(GLContext *context, const GLdouble *coord);
void GLFogCoordf(GLContext *context, GLfloat coord);
void GLFogCoordfv(GLContext *context, const GLfloat *coord);
void GLFogi(GLContext *context, GLenum pname, GLint param);
void GLFogiv(GLContext *context, GLenum pname, const GLint *params);
void GLFramebufferRenderbuffer(GLContext *context, GLenum target, GLenum attachment, GLenum renderbuffertarget, GLuint renderbuffer);
void GLFramebufferTexture1D(GLContext *context, GLenum target, GLenum attachment, GLenum textarget, GLuint texture, GLint level);
void GLFramebufferTexture2D(GLContext *context, GLenum target, GLenum attachment, GLenum textarget, GLuint texture, GLint level);
void GLFramebufferTexture3D(GLContext *context, GLenum target, GLenum attachment, GLenum textarget, GLuint texture, GLint level, GLint zoffset);
void GLFramebufferTextureLayer(GLContext *context, GLenum target, GLenum attachment, GLuint texture, GLint level, GLint layer);
void GLGenFramebuffers(GLContext *context, GLsizei n, GLuint *framebuffers);
void GLGenProgramsARB(GLContext *context, GLsizei n, GLuint *programs);
void GLGenQueries(GLContext *context, GLsizei n, GLuint *ids);
void GLGenRenderbuffers(GLContext *context, GLsizei n, GLuint *renderbuffers);
void GLGenerateMipmap(GLContext *context, GLenum target);
void GLGetActiveAttrib(GLContext *context, GLuint program, GLuint index, GLsizei bufSize, GLsizei *length, GLint *size, GLenum *type, GLchar *name);
void GLGetActiveUniform(GLContext *context, GLuint program, GLuint index, GLsizei bufSize, GLsizei *length, GLint *size, GLenum *type, GLchar *name);
void GLGetAttachedObjectsARB(GLContext *context, GLhandleARB containerObj, GLsizei maxCount, GLsizei *count, GLhandleARB *obj);
void GLGetAttachedShaders(GLContext *context, GLuint program, GLsizei maxCount, GLsizei *count, GLuint *shaders);
void GLGetBooleanv(GLContext *context, GLenum pname, GLboolean *data);
void GLGetBufferPointerv(GLContext *context, GLenum target, GLenum pname, void **params);
void GLGetBufferSubData(GLContext *context, GLenum target, GLintptr offset, GLsizeiptr size, void *data);
void GLGetColorTable(GLContext *context, GLenum target, GLenum format, GLenum type, void *table);
void GLGetColorTableParameterfv(GLContext *context, GLenum target, GLenum pname, GLfloat *params);
void GLGetColorTableParameterfvSGI(GLContext *context, GLenum target, GLenum pname, GLfloat *params);
void GLGetColorTableParameteriv(GLContext *context, GLenum target, GLenum pname, GLint *params);
void GLGetColorTableParameterivSGI(GLContext *context, GLenum target, GLenum pname, GLint *params);
void GLGetColorTableSGI(GLContext *context, GLenum target, GLenum format, GLenum type, void *table);
void GLGetCompressedTexImage(GLContext *context, GLenum target, GLint level, void *img);
void GLGetConvolutionFilter(GLContext *context, GLenum target, GLenum format, GLenum type, void *image);
void GLGetConvolutionFilterEXT(GLContext *context, GLenum target, GLenum format, GLenum type, void *image);
void GLGetConvolutionParameterfv(GLContext *context, GLenum target, GLenum pname, GLfloat *params);
void GLGetConvolutionParameterfvEXT(GLContext *context, GLenum target, GLenum pname, GLfloat *params);
void GLGetConvolutionParameteriv(GLContext *context, GLenum target, GLenum pname, GLint *params);
void GLGetConvolutionParameterivEXT(GLContext *context, GLenum target, GLenum pname, GLint *params);
void GLGetFramebufferAttachmentParameteriv(GLContext *context, GLenum target, GLenum attachment, GLenum pname, GLint *params);
GLhandleARB GLGetHandleARB(GLContext *context, GLenum pname);
void GLGetHistogram(GLContext *context, GLenum target, GLboolean reset, GLenum format, GLenum type, void *values);
void GLGetHistogramEXT(GLContext *context, GLenum target, GLboolean reset, GLenum format, GLenum type, void *values);
void GLGetHistogramParameterfv(GLContext *context, GLenum target, GLenum pname, GLfloat *params);
void GLGetHistogramParameterfvEXT(GLContext *context, GLenum target, GLenum pname, GLfloat *params);
void GLGetHistogramParameteriv(GLContext *context, GLenum target, GLenum pname, GLint *params);
void GLGetHistogramParameterivEXT(GLContext *context, GLenum target, GLenum pname, GLint *params);
void GLGetInfoLogARB(GLContext *context, GLhandleARB obj, GLsizei maxLength, GLsizei *length, GLcharARB *infoLog);
void GLGetLightiv(GLContext *context, GLenum light, GLenum pname, GLint *params);
void GLGetMaterialiv(GLContext *context, GLenum face, GLenum pname, GLint *params);
void GLGetMinmax(GLContext *context, GLenum target, GLboolean reset, GLenum format, GLenum type, void *values);
void GLGetMinmaxEXT(GLContext *context, GLenum target, GLboolean reset, GLenum format, GLenum type, void *values);
void GLGetMinmaxParameterfv(GLContext *context, GLenum target, GLenum pname, GLfloat *params);
void GLGetMinmaxParameterfvEXT(GLContext *context, GLenum target, GLenum pname, GLfloat *params);
void GLGetMinmaxParameteriv(GLContext *context, GLenum target, GLenum pname, GLint *params);
void GLGetMinmaxParameterivEXT(GLContext *context, GLenum target, GLenum pname, GLint *params);
void GLGetObjectParameterfvARB(GLContext *context, GLhandleARB obj, GLenum pname, GLfloat *params);
void GLGetObjectParameterivARB(GLContext *context, GLhandleARB obj, GLenum pname, GLint *params);
void GLGetPixelMapfv(GLContext *context, GLenum map, GLfloat *values);
void GLGetPixelMapuiv(GLContext *context, GLenum map, GLuint *values);
void GLGetPixelMapusv(GLContext *context, GLenum map, GLushort *values);
void GLGetPolygonStipple(GLContext *context, GLubyte *mask);
void GLGetProgramEnvParameterdvARB(GLContext *context, GLenum target, GLuint index, GLdouble *params);
void GLGetProgramEnvParameterfvARB(GLContext *context, GLenum target, GLuint index, GLfloat *params);
void GLGetProgramLocalParameterdvARB(GLContext *context, GLenum target, GLuint index, GLdouble *params);
void GLGetProgramLocalParameterfvARB(GLContext *context, GLenum target, GLuint index, GLfloat *params);
void GLGetProgramStringARB(GLContext *context, GLenum target, GLenum pname, void *string);
void GLGetProgramivARB(GLContext *context, GLenum target, GLenum pname, GLint *params);
void GLGetQueryObjectiv(GLContext *context, GLuint id, GLenum pname, GLint *params);
void GLGetQueryObjectuiv(GLContext *context, GLuint id, GLenum pname, GLuint *params);
void GLGetQueryiv(GLContext *context, GLenum target, GLenum pname, GLint *params);
void GLGetRenderbufferParameteriv(GLContext *context, GLenum target, GLenum pname, GLint *params);
void GLGetSeparableFilter(GLContext *context, GLenum target, GLenum format, GLenum type, void *row, void *column, void *span);
void GLGetSeparableFilterEXT(GLContext *context, GLenum target, GLenum format, GLenum type, void *row, void *column, void *span);
void GLGetShaderSource(GLContext *context, GLuint shader, GLsizei bufSize, GLsizei *length, GLchar *source);
void GLGetTexGendv(GLContext *context, GLenum coord, GLenum pname, GLdouble *params);
void GLGetTexGenfv(GLContext *context, GLenum coord, GLenum pname, GLfloat *params);
void GLGetTexGeniv(GLContext *context, GLenum coord, GLenum pname, GLint *params);
void GLGetTexLevelParameterfv(GLContext *context, GLenum target, GLint level, GLenum pname, GLfloat *params);
void GLGetUniformfv(GLContext *context, GLuint program, GLint location, GLfloat *params);
void GLGetUniformiv(GLContext *context, GLuint program, GLint location, GLint *params);
void GLGetVertexAttribPointerv(GLContext *context, GLuint index, GLenum pname, void **pointer);
void GLGetVertexAttribdv(GLContext *context, GLuint index, GLenum pname, GLdouble *params);
void GLGetVertexAttribfv(GLContext *context, GLuint index, GLenum pname, GLfloat *params);
void GLGetVertexAttribiv(GLContext *context, GLuint index, GLenum pname, GLint *params);
void GLHistogram(GLContext *context, GLenum target, GLsizei width, GLenum internalformat, GLboolean sink);
void GLIndexMask(GLContext *context, GLuint mask);
void GLIndexPointer(GLContext *context, GLenum type, GLsizei stride, const void *pointer);
void GLIndexd(GLContext *context, GLdouble c);
void GLIndexdv(GLContext *context, const GLdouble *c);
void GLIndexf(GLContext *context, GLfloat c);
void GLIndexfv(GLContext *context, const GLfloat *c);
void GLIndexi(GLContext *context, GLint c);
void GLIndexiv(GLContext *context, const GLint *c);
void GLIndexs(GLContext *context, GLshort c);
void GLIndexsv(GLContext *context, const GLshort *c);
void GLIndexub(GLContext *context, GLubyte c);
void GLIndexubv(GLContext *context, const GLubyte *c);
void GLInterleavedArrays(GLContext *context, GLenum format, GLsizei stride, const void *pointer);
GLboolean GLIsBuffer(GLContext *context, GLuint buffer);
GLboolean GLIsFramebuffer(GLContext *context, GLuint framebuffer);
GLboolean GLIsProgram(GLContext *context, GLuint program);
GLboolean GLIsProgramARB(GLContext *context, GLuint program);
GLboolean GLIsQuery(GLContext *context, GLuint id);
GLboolean GLIsRenderbuffer(GLContext *context, GLuint renderbuffer);
GLboolean GLIsShader(GLContext *context, GLuint shader);
void GLLightModeliv(GLContext *context, GLenum pname, const GLint *params);
void GLLighti(GLContext *context, GLenum light, GLenum pname, GLint param);
void GLLightiv(GLContext *context, GLenum light, GLenum pname, const GLint *params);
void GLLogicOp(GLContext *context, GLenum opcode);
void *GLMapBuffer(GLContext *context, GLenum target, GLenum access);
void GLMateriali(GLContext *context, GLenum face, GLenum pname, GLint param);
void GLMaterialiv(GLContext *context, GLenum face, GLenum pname, const GLint *params);
void GLMatrixIndexPointerARB(GLContext *context, GLint size, GLenum type, GLsizei stride, const void *pointer);
void GLMatrixIndexubvARB(GLContext *context, GLint size, const GLubyte *indices);
void GLMatrixIndexuivARB(GLContext *context, GLint size, const GLuint *indices);
void GLMatrixIndexusvARB(GLContext *context, GLint size, const GLushort *indices);
void GLMinmax(GLContext *context, GLenum target, GLenum internalformat, GLboolean sink);
void GLMultiDrawArrays(GLContext *context, GLenum mode, const GLint *first, const GLsizei *count, GLsizei drawcount);
void GLMultiDrawElements(GLContext *context, GLenum mode, const GLsizei *count, GLenum type, const void *const*indices, GLsizei drawcount);
void GLMultiTexCoord1d(GLContext *context, GLenum target, GLdouble s);
void GLMultiTexCoord1dv(GLContext *context, GLenum target, const GLdouble *v);
void GLMultiTexCoord1f(GLContext *context, GLenum target, GLfloat s);
void GLMultiTexCoord1fv(GLContext *context, GLenum target, const GLfloat *v);
void GLMultiTexCoord1i(GLContext *context, GLenum target, GLint s);
void GLMultiTexCoord1iv(GLContext *context, GLenum target, const GLint *v);
void GLMultiTexCoord1s(GLContext *context, GLenum target, GLshort s);
void GLMultiTexCoord1sv(GLContext *context, GLenum target, const GLshort *v);
void GLMultiTexCoord2d(GLContext *context, GLenum target, GLdouble s, GLdouble t);
void GLMultiTexCoord2i(GLContext *context, GLenum target, GLint s, GLint t);
void GLMultiTexCoord2iv(GLContext *context, GLenum target, const GLint *v);
void GLMultiTexCoord2s(GLContext *context, GLenum target, GLshort s, GLshort t);
void GLMultiTexCoord2sv(GLContext *context, GLenum target, const GLshort *v);
void GLMultiTexCoord3d(GLContext *context, GLenum target, GLdouble s, GLdouble t, GLdouble r);
void GLMultiTexCoord3dv(GLContext *context, GLenum target, const GLdouble *v);
void GLMultiTexCoord3i(GLContext *context, GLenum target, GLint s, GLint t, GLint r);
void GLMultiTexCoord3iv(GLContext *context, GLenum target, const GLint *v);
void GLMultiTexCoord3s(GLContext *context, GLenum target, GLshort s, GLshort t, GLshort r);
void GLMultiTexCoord3sv(GLContext *context, GLenum target, const GLshort *v);
void GLMultiTexCoord4d(GLContext *context, GLenum target, GLdouble s, GLdouble t, GLdouble r, GLdouble q);
void GLMultiTexCoord4dv(GLContext *context, GLenum target, const GLdouble *v);
void GLMultiTexCoord4i(GLContext *context, GLenum target, GLint s, GLint t, GLint r, GLint q);
void GLMultiTexCoord4iv(GLContext *context, GLenum target, const GLint *v);
void GLMultiTexCoord4s(GLContext *context, GLenum target, GLshort s, GLshort t, GLshort r, GLshort q);
void GLMultiTexCoord4sv(GLContext *context, GLenum target, const GLshort *v);
void GLNormal3b(GLContext *context, GLbyte nx, GLbyte ny, GLbyte nz);
void GLNormal3bv(GLContext *context, const GLbyte *v);
void GLNormal3d(GLContext *context, GLdouble nx, GLdouble ny, GLdouble nz);
void GLNormal3i(GLContext *context, GLint nx, GLint ny, GLint nz);
void GLNormal3iv(GLContext *context, const GLint *v);
void GLPassThrough(GLContext *context, GLfloat token);
void GLPixelMapfv(GLContext *context, GLenum map, GLsizei mapsize, const GLfloat *values);
void GLPixelMapuiv(GLContext *context, GLenum map, GLsizei mapsize, const GLuint *values);
void GLPixelMapusv(GLContext *context, GLenum map, GLsizei mapsize, const GLushort *values);
void GLPixelStoref(GLContext *context, GLenum pname, GLfloat param);
void GLPointParameteri(GLContext *context, GLenum pname, GLint param);
void GLPointParameteriv(GLContext *context, GLenum pname, const GLint *params);
void GLPolygonStipple(GLContext *context, const GLubyte *mask);
void GLProgramEnvParameter4dARB(GLContext *context, GLenum target, GLuint index, GLdouble x, GLdouble y, GLdouble z, GLdouble w);
void GLProgramEnvParameter4dvARB(GLContext *context, GLenum target, GLuint index, const GLdouble *params);
void GLProgramEnvParameter4fARB(GLContext *context, GLenum target, GLuint index, GLfloat x, GLfloat y, GLfloat z, GLfloat w);
void GLProgramEnvParameter4fvARB(GLContext *context, GLenum target, GLuint index, const GLfloat *params);
void GLProgramLocalParameter4dARB(GLContext *context, GLenum target, GLuint index, GLdouble x, GLdouble y, GLdouble z, GLdouble w);
void GLProgramLocalParameter4dvARB(GLContext *context, GLenum target, GLuint index, const GLdouble *params);
void GLProgramLocalParameter4fARB(GLContext *context, GLenum target, GLuint index, GLfloat x, GLfloat y, GLfloat z, GLfloat w);
void GLProgramLocalParameter4fvARB(GLContext *context, GLenum target, GLuint index, const GLfloat *params);
void GLProgramStringARB(GLContext *context, GLenum target, GLenum format, GLsizei len, const void *string);
void GLRasterPos2d(GLContext *context, GLdouble x, GLdouble y);
void GLRasterPos2dv(GLContext *context, const GLdouble *v);
void GLRasterPos2i(GLContext *context, GLint x, GLint y);
void GLRasterPos2iv(GLContext *context, const GLint *v);
void GLRasterPos2s(GLContext *context, GLshort x, GLshort y);
void GLRasterPos2sv(GLContext *context, const GLshort *v);
void GLRasterPos3d(GLContext *context, GLdouble x, GLdouble y, GLdouble z);
void GLRasterPos3dv(GLContext *context, const GLdouble *v);
void GLRasterPos3i(GLContext *context, GLint x, GLint y, GLint z);
void GLRasterPos3iv(GLContext *context, const GLint *v);
void GLRasterPos3s(GLContext *context, GLshort x, GLshort y, GLshort z);
void GLRasterPos3sv(GLContext *context, const GLshort *v);
void GLRasterPos4d(GLContext *context, GLdouble x, GLdouble y, GLdouble z, GLdouble w);
void GLRasterPos4dv(GLContext *context, const GLdouble *v);
void GLRasterPos4f(GLContext *context, GLfloat x, GLfloat y, GLfloat z, GLfloat w);
void GLRasterPos4fv(GLContext *context, const GLfloat *v);
void GLRasterPos4i(GLContext *context, GLint x, GLint y, GLint z, GLint w);
void GLRasterPos4iv(GLContext *context, const GLint *v);
void GLRasterPos4s(GLContext *context, GLshort x, GLshort y, GLshort z, GLshort w);
void GLRasterPos4sv(GLContext *context, const GLshort *v);
void GLRectd(GLContext *context, GLdouble x1, GLdouble y1, GLdouble x2, GLdouble y2);
void GLRecti(GLContext *context, GLint x1, GLint y1, GLint x2, GLint y2);
void GLRects(GLContext *context, GLshort x1, GLshort y1, GLshort x2, GLshort y2);
void GLRectsv(GLContext *context, const GLshort *v1, const GLshort *v2);
void GLRenderbufferStorage(GLContext *context, GLenum target, GLenum internalformat, GLsizei width, GLsizei height);
void GLRenderbufferStorageMultisample(GLContext *context, GLenum target, GLsizei samples, GLenum internalformat, GLsizei width, GLsizei height);
void GLResetHistogram(GLContext *context, GLenum target);
void GLResetMinmax(GLContext *context, GLenum target);
void GLRotated(GLContext *context, GLdouble angle, GLdouble x, GLdouble y, GLdouble z);
void GLSampleCoverage(GLContext *context, GLfloat value, GLboolean invert);
void GLScaled(GLContext *context, GLdouble x, GLdouble y, GLdouble z);
void GLSecondaryColor3b(GLContext *context, GLbyte red, GLbyte green, GLbyte blue);
void GLSecondaryColor3bv(GLContext *context, const GLbyte *v);
void GLSecondaryColor3d(GLContext *context, GLdouble red, GLdouble green, GLdouble blue);
void GLSecondaryColor3dv(GLContext *context, const GLdouble *v);
void GLSecondaryColor3f(GLContext *context, GLfloat red, GLfloat green, GLfloat blue);
void GLSecondaryColor3fv(GLContext *context, const GLfloat *v);
void GLSecondaryColor3i(GLContext *context, GLint red, GLint green, GLint blue);
void GLSecondaryColor3iv(GLContext *context, const GLint *v);
void GLSecondaryColor3s(GLContext *context, GLshort red, GLshort green, GLshort blue);
void GLSecondaryColor3sv(GLContext *context, const GLshort *v);
void GLSecondaryColor3ub(GLContext *context, GLubyte red, GLubyte green, GLubyte blue);
void GLSecondaryColor3ubv(GLContext *context, const GLubyte *v);
void GLSecondaryColor3ui(GLContext *context, GLuint red, GLuint green, GLuint blue);
void GLSecondaryColor3uiv(GLContext *context, const GLuint *v);
void GLSecondaryColor3us(GLContext *context, GLushort red, GLushort green, GLushort blue);
void GLSecondaryColor3usv(GLContext *context, const GLushort *v);
void GLSecondaryColorPointer(GLContext *context, GLint size, GLenum type, GLsizei stride, const void *pointer);
void GLSeparableFilter2D(GLContext *context, GLenum target, GLenum internalformat, GLsizei width, GLsizei height, GLenum format, GLenum type, const void *row, const void *column);
void GLStencilFuncSeparate(GLContext *context, GLenum face, GLenum func, GLint ref, GLuint mask);
void GLStencilFuncSeparateATI(GLContext *context, GLenum frontfunc, GLenum backfunc, GLint ref, GLuint mask);
void GLStencilMaskSeparate(GLContext *context, GLenum face, GLuint mask);
void GLStencilOpSeparate(GLContext *context, GLenum face, GLenum sfail, GLenum dpfail, GLenum dppass);
void GLTexCoord1d(GLContext *context, GLdouble s);
void GLTexCoord1f(GLContext *context, GLfloat s);
void GLTexCoord1fv(GLContext *context, const GLfloat *v);
void GLTexCoord1i(GLContext *context, GLint s);
void GLTexCoord1iv(GLContext *context, const GLint *v);
void GLTexCoord1s(GLContext *context, GLshort s);
void GLTexCoord1sv(GLContext *context, const GLshort *v);
void GLTexCoord2d(GLContext *context, GLdouble s, GLdouble t);
void GLTexCoord2i(GLContext *context, GLint s, GLint t);
void GLTexCoord2s(GLContext *context, GLshort s, GLshort t);
void GLTexCoord2sv(GLContext *context, const GLshort *v);
void GLTexCoord3d(GLContext *context, GLdouble s, GLdouble t, GLdouble r);
void GLTexCoord3fv(GLContext *context, const GLfloat *v);
void GLTexCoord3i(GLContext *context, GLint s, GLint t, GLint r);
void GLTexCoord3iv(GLContext *context, const GLint *v);
void GLTexCoord3s(GLContext *context, GLshort s, GLshort t, GLshort r);
void GLTexCoord3sv(GLContext *context, const GLshort *v);
void GLTexCoord4d(GLContext *context, GLdouble s, GLdouble t, GLdouble r, GLdouble q);
void GLTexCoord4f(GLContext *context, GLfloat s, GLfloat t, GLfloat r, GLfloat q);
void GLTexCoord4fv(GLContext *context, const GLfloat *v);
void GLTexCoord4i(GLContext *context, GLint s, GLint t, GLint r, GLint q);
void GLTexCoord4iv(GLContext *context, const GLint *v);
void GLTexCoord4s(GLContext *context, GLshort s, GLshort t, GLshort r, GLshort q);
void GLTexCoord4sv(GLContext *context, const GLshort *v);
void GLTexEnviv(GLContext *context, GLenum target, GLenum pname, const GLint *params);
void GLTexGend(GLContext *context, GLenum coord, GLenum pname, GLdouble param);
void GLTexGendv(GLContext *context, GLenum coord, GLenum pname, const GLdouble *params);
void GLTexGenf(GLContext *context, GLenum coord, GLenum pname, GLfloat param);
void GLTexGeniv(GLContext *context, GLenum coord, GLenum pname, const GLint *params);
void GLTexImage3D(GLContext *context, GLenum target, GLint level, GLint internalformat, GLsizei width, GLsizei height, GLsizei depth, GLint border, GLenum format, GLenum type, const void *pixels);
void GLTexSubImage3D(GLContext *context, GLenum target, GLint level, GLint xoffset, GLint yoffset, GLint zoffset, GLsizei width, GLsizei height, GLsizei depth, GLenum format, GLenum type, const void *pixels);
void GLTranslated(GLContext *context, GLdouble x, GLdouble y, GLdouble z);
GLboolean GLUnmapBuffer(GLContext *context, GLenum target);
void GLVertex2d(GLContext *context, GLdouble x, GLdouble y);
void GLVertex2dv(GLContext *context, const GLdouble *v);
void GLVertex2f(GLContext *context, GLfloat x, GLfloat y);
void GLVertex2fv(GLContext *context, const GLfloat *v);
void GLVertex2i(GLContext *context, GLint x, GLint y);
void GLVertex2iv(GLContext *context, const GLint *v);
void GLVertex2s(GLContext *context, GLshort x, GLshort y);
void GLVertex2sv(GLContext *context, const GLshort *v);
void GLVertex3d(GLContext *context, GLdouble x, GLdouble y, GLdouble z);
void GLVertex3i(GLContext *context, GLint x, GLint y, GLint z);
void GLVertex3iv(GLContext *context, const GLint *v);
void GLVertex3s(GLContext *context, GLshort x, GLshort y, GLshort z);
void GLVertex3sv(GLContext *context, const GLshort *v);
void GLVertex4d(GLContext *context, GLdouble x, GLdouble y, GLdouble z, GLdouble w);
void GLVertex4i(GLContext *context, GLint x, GLint y, GLint z, GLint w);
void GLVertex4iv(GLContext *context, const GLint *v);
void GLVertex4s(GLContext *context, GLshort x, GLshort y, GLshort z, GLshort w);
void GLVertex4sv(GLContext *context, const GLshort *v);
void GLVertexAttrib1d(GLContext *context, GLuint index, GLdouble x);
void GLVertexAttrib1dv(GLContext *context, GLuint index, const GLdouble *v);
void GLVertexAttrib1f(GLContext *context, GLuint index, GLfloat x);
void GLVertexAttrib1fv(GLContext *context, GLuint index, const GLfloat *v);
void GLVertexAttrib1s(GLContext *context, GLuint index, GLshort x);
void GLVertexAttrib1sv(GLContext *context, GLuint index, const GLshort *v);
void GLVertexAttrib2d(GLContext *context, GLuint index, GLdouble x, GLdouble y);
void GLVertexAttrib2dv(GLContext *context, GLuint index, const GLdouble *v);
void GLVertexAttrib2f(GLContext *context, GLuint index, GLfloat x, GLfloat y);
void GLVertexAttrib2fv(GLContext *context, GLuint index, const GLfloat *v);
void GLVertexAttrib2s(GLContext *context, GLuint index, GLshort x, GLshort y);
void GLVertexAttrib2sv(GLContext *context, GLuint index, const GLshort *v);
void GLVertexAttrib3d(GLContext *context, GLuint index, GLdouble x, GLdouble y, GLdouble z);
void GLVertexAttrib3dv(GLContext *context, GLuint index, const GLdouble *v);
void GLVertexAttrib3f(GLContext *context, GLuint index, GLfloat x, GLfloat y, GLfloat z);
void GLVertexAttrib3fv(GLContext *context, GLuint index, const GLfloat *v);
void GLVertexAttrib3s(GLContext *context, GLuint index, GLshort x, GLshort y, GLshort z);
void GLVertexAttrib3sv(GLContext *context, GLuint index, const GLshort *v);
void GLVertexAttrib4Nbv(GLContext *context, GLuint index, const GLbyte *v);
void GLVertexAttrib4Niv(GLContext *context, GLuint index, const GLint *v);
void GLVertexAttrib4Nsv(GLContext *context, GLuint index, const GLshort *v);
void GLVertexAttrib4Nub(GLContext *context, GLuint index, GLubyte x, GLubyte y, GLubyte z, GLubyte w);
void GLVertexAttrib4Nubv(GLContext *context, GLuint index, const GLubyte *v);
void GLVertexAttrib4Nuiv(GLContext *context, GLuint index, const GLuint *v);
void GLVertexAttrib4Nusv(GLContext *context, GLuint index, const GLushort *v);
void GLVertexAttrib4bv(GLContext *context, GLuint index, const GLbyte *v);
void GLVertexAttrib4d(GLContext *context, GLuint index, GLdouble x, GLdouble y, GLdouble z, GLdouble w);
void GLVertexAttrib4dv(GLContext *context, GLuint index, const GLdouble *v);
void GLVertexAttrib4f(GLContext *context, GLuint index, GLfloat x, GLfloat y, GLfloat z, GLfloat w);
void GLVertexAttrib4fv(GLContext *context, GLuint index, const GLfloat *v);
void GLVertexAttrib4iv(GLContext *context, GLuint index, const GLint *v);
void GLVertexAttrib4s(GLContext *context, GLuint index, GLshort x, GLshort y, GLshort z, GLshort w);
void GLVertexAttrib4sv(GLContext *context, GLuint index, const GLshort *v);
void GLVertexAttrib4ubv(GLContext *context, GLuint index, const GLubyte *v);
void GLVertexAttrib4uiv(GLContext *context, GLuint index, const GLuint *v);
void GLVertexAttrib4usv(GLContext *context, GLuint index, const GLushort *v);
void GLVertexBlendARB(GLContext *context, GLint count);
void GLWeightPointerARB(GLContext *context, GLint size, GLenum type, GLsizei stride, const void *pointer);
void GLWeightbvARB(GLContext *context, GLint size, const GLbyte *weights);
void GLWeightdvARB(GLContext *context, GLint size, const GLdouble *weights);
void GLWeightfvARB(GLContext *context, GLint size, const GLfloat *weights);
void GLWeightivARB(GLContext *context, GLint size, const GLint *weights);
void GLWeightsvARB(GLContext *context, GLint size, const GLshort *weights);
void GLWeightubvARB(GLContext *context, GLint size, const GLubyte *weights);
void GLWeightuivARB(GLContext *context, GLint size, const GLuint *weights);
void GLWeightusvARB(GLContext *context, GLint size, const GLushort *weights);
void GLWindowPos2d(GLContext *context, GLdouble x, GLdouble y);
void GLWindowPos2dv(GLContext *context, const GLdouble *v);
void GLWindowPos2fv(GLContext *context, const GLfloat *v);
void GLWindowPos2i(GLContext *context, GLint x, GLint y);
void GLWindowPos2iv(GLContext *context, const GLint *v);
void GLWindowPos2s(GLContext *context, GLshort x, GLshort y);
void GLWindowPos2sv(GLContext *context, const GLshort *v);
void GLWindowPos3d(GLContext *context, GLdouble x, GLdouble y, GLdouble z);
void GLWindowPos3dv(GLContext *context, const GLdouble *v);
void GLWindowPos3f(GLContext *context, GLfloat x, GLfloat y, GLfloat z);
void GLWindowPos3fv(GLContext *context, const GLfloat *v);
void GLWindowPos3i(GLContext *context, GLint x, GLint y, GLint z);
void GLWindowPos3iv(GLContext *context, const GLint *v);
void GLWindowPos3s(GLContext *context, GLshort x, GLshort y, GLshort z);
void GLWindowPos3sv(GLContext *context, const GLshort *v);
void GLAlphaFragmentOp1ATI(GLContext *context, GLenum op, GLuint dst, GLuint dstMod, GLuint arg1, GLuint arg1Rep, GLuint arg1Mod);
void GLAlphaFragmentOp2ATI(GLContext *context, GLenum op, GLuint dst, GLuint dstMod, GLuint arg1, GLuint arg1Rep, GLuint arg1Mod, GLuint arg2, GLuint arg2Rep, GLuint arg2Mod);
void GLAlphaFragmentOp3ATI(GLContext *context, GLenum op, GLuint dst, GLuint dstMod, GLuint arg1, GLuint arg1Rep, GLuint arg1Mod, GLuint arg2, GLuint arg2Rep, GLuint arg2Mod, GLuint arg3, GLuint arg3Rep, GLuint arg3Mod);
void GLBeginFragmentShaderATI(GLContext *context);
void GLBindFragmentShaderATI(GLContext *context, GLuint id);
void GLColorFragmentOp1ATI(GLContext *context, GLenum op, GLuint dst, GLuint dstMask, GLuint dstMod, GLuint arg1, GLuint arg1Rep, GLuint arg1Mod);
void GLColorFragmentOp2ATI(GLContext *context, GLenum op, GLuint dst, GLuint dstMask, GLuint dstMod, GLuint arg1, GLuint arg1Rep, GLuint arg1Mod, GLuint arg2, GLuint arg2Rep, GLuint arg2Mod);
void GLColorFragmentOp3ATI(GLContext *context, GLenum op, GLuint dst, GLuint dstMask, GLuint dstMod, GLuint arg1, GLuint arg1Rep, GLuint arg1Mod, GLuint arg2, GLuint arg2Rep, GLuint arg2Mod, GLuint arg3, GLuint arg3Rep, GLuint arg3Mod);
void GLDeleteFragmentShaderATI(GLContext *context, GLuint id);
void GLEndFragmentShaderATI(GLContext *context);
GLuint GLGenFragmentShadersATI(GLContext *context, GLuint range);
void GLPassTexCoordATI(GLContext *context, GLuint dst, GLuint coord, GLenum swizzle);
void GLSampleMapATI(GLContext *context, GLuint dst, GLuint interp, GLenum swizzle);
void GLSetFragmentShaderConstantATI(GLContext *context, GLuint dst, const GLfloat *value);
void TGLEnableNewExtensions(GLContext *context, unsigned int value);
void *TGLGetProcAddress(GLContext **tglcontextpointer, const char *Name);
void GLClampColor(GLContext *context, GLenum target, GLenum clamp);
void GLClearColorIiEXT(GLContext *context, GLint red, GLint green, GLint blue, GLint alpha);
void GLClearColorIuiEXT(GLContext *context, GLuint red, GLuint green, GLuint blue, GLuint alpha);
void GLGetTexParameterIiv(GLContext *context, GLenum target, GLenum pname, GLint *params);
void GLGetTexParameterIuiv(GLContext *context, GLenum target, GLenum pname, GLuint *params);
void GLTexParameterIiv(GLContext *context, GLenum target, GLenum pname, const GLint *params);
void GLTexParameterIuiv(GLContext *context, GLenum target, GLenum pname, const GLuint *params);
void GLBindFramebufferEXT(GLContext *context, GLenum target, GLuint framebuffer);
void GLBindRenderbufferEXT(GLContext *context, GLenum target, GLuint renderbuffer);
void TGLSetContextVersion(GLContext *context, unsigned int contextversion);
unsigned int TGLGetContextVersion(GLContext *context);

#ifdef __cplusplus
}
#endif /* __cplusplus */

#endif /* CLIB_TINYGL_PROTOS_H */
