;* Assembly includefile generated by RevUp 1.5 *

VERSION		EQU	1
REVISION	EQU	12
DATE	MACRO
		dc.b	'29.4.97'
	ENDM
VERS	MACRO
		dc.b	'protracker.datatype 1.12'
	ENDM
VSTRING	MACRO
		dc.b	'protracker.datatype 1.12 (29.4.97)',13,10,0
	ENDM
VERSTAG	MACRO
		dc.b	0,'$VER: protracker.datatype 1.12 (29.4.97)',0
	ENDM
