/* C headerfile generated by RevUp 1.5 */

#define VERSION		1
#define REVISION	12
#define DATE	"29.4.97"
#define VERS	"protracker.datatype 1.12"
#define VSTRING	"protracker.datatype 1.12 (29.4.97)\r\n"
#define VERSTAG	"\0$VER: protracker.datatype 1.12 (29.4.97)"
