/*
** This file was automatically generated by fdtrans.
** Do not edit it by hand. Instead, edit the sfd file
** that was used to generate this file
*/

#ifdef __USE_INLINE__
#undef __USE_INLINE__
#endif
#ifndef __NOGLOBALIFACE__
#define __NOGLOBALIFACE__
#endif

#include <exec/interfaces.h>
#include <exec/libraries.h>
#include <exec/emulation.h>
#include <interfaces/exec.h>
#include <internal/interfaces/charset.h>
#include <internal/proto/charset.h>



STATIC ULONG stub_OpenPPC(ULONG *regarray)
{
	struct Library *Base = (struct Library *) regarray[REG68K_A6/4];
	struct ExtendedLibrary *ExtLib = (struct ExtendedLibrary *) ((ULONG)Base + Base->lib_PosSize);
	struct LibraryManagerInterface *Self = (struct LibraryManagerInterface *) ExtLib->ILibrary;

	return (ULONG) Self->Open(0);
}
STATIC CONST struct EmuTrap stub_Open = { TRAPINST, TRAPTYPE, stub_OpenPPC };

STATIC ULONG stub_ClosePPC(ULONG *regarray)
{
	struct Library *Base = (struct Library *) regarray[REG68K_A6/4];
	struct ExtendedLibrary *ExtLib = (struct ExtendedLibrary *) ((ULONG)Base + Base->lib_PosSize);
	struct LibraryManagerInterface *Self = (struct LibraryManagerInterface *) ExtLib->ILibrary;

	return (ULONG) Self->Close();
}
STATIC CONST struct EmuTrap stub_Close = { TRAPINST, TRAPTYPE, stub_ClosePPC };

STATIC ULONG stub_ExpungePPC(ULONG *regarray)
{
	return 0UL;
}
STATIC CONST struct EmuTrap stub_Expunge = { TRAPINST, TRAPTYPE, stub_ExpungePPC };

STATIC ULONG stub_ReservedPPC(ULONG *regarray)
{
	return 0UL;
}
STATIC CONST struct EmuTrap stub_Reserved = { TRAPINST, TRAPTYPE, stub_ReservedPPC };

static ULONG stub_CS_GetDriverInfoPPC(ULONG *regarray)
{
	struct Library *Base = (struct Library *) regarray[REG68K_A6/4];
	struct ExtendedLibrary *ExtLib = (struct ExtendedLibrary *) ((ULONG)Base + Base->lib_PosSize);
	struct CharsetIFace *Self = (struct CharsetIFace *) ExtLib->MainIFace;

	return Self->CS_GetDriverInfo(
	);
}
STATIC CONST struct EmuTrap stub_CS_GetDriverInfo = { TRAPINST, TRAPTYPE, (ULONG (*)(ULONG *))stub_CS_GetDriverInfoPPC };

static ULONG stub_CS_ConvToLowerPPC(ULONG *regarray)
{
	struct Library *Base = (struct Library *) regarray[REG68K_A6/4];
	struct ExtendedLibrary *ExtLib = (struct ExtendedLibrary *) ((ULONG)Base + Base->lib_PosSize);
	struct CharsetIFace *Self = (struct CharsetIFace *) ExtLib->MainIFace;

	return Self->CS_ConvToLower(
		(ULONG)regarray[0]
	);
}
STATIC CONST struct EmuTrap stub_CS_ConvToLower = { TRAPINST, TRAPTYPE, (ULONG (*)(ULONG *))stub_CS_ConvToLowerPPC };

static ULONG stub_CS_ConvToUpperPPC(ULONG *regarray)
{
	struct Library *Base = (struct Library *) regarray[REG68K_A6/4];
	struct ExtendedLibrary *ExtLib = (struct ExtendedLibrary *) ((ULONG)Base + Base->lib_PosSize);
	struct CharsetIFace *Self = (struct CharsetIFace *) ExtLib->MainIFace;

	return Self->CS_ConvToUpper(
		(ULONG)regarray[0]
	);
}
STATIC CONST struct EmuTrap stub_CS_ConvToUpper = { TRAPINST, TRAPTYPE, (ULONG (*)(ULONG *))stub_CS_ConvToUpperPPC };

static ULONG stub_CS_NeverCalledGetCodeSetPPC(ULONG *regarray)
{
	struct Library *Base = (struct Library *) regarray[REG68K_A6/4];
	struct ExtendedLibrary *ExtLib = (struct ExtendedLibrary *) ((ULONG)Base + Base->lib_PosSize);
	struct CharsetIFace *Self = (struct CharsetIFace *) ExtLib->MainIFace;

	return Self->CS_NeverCalledGetCodeSet(
	);
}
STATIC CONST struct EmuTrap stub_CS_NeverCalledGetCodeSet = { TRAPINST, TRAPTYPE, (ULONG (*)(ULONG *))stub_CS_NeverCalledGetCodeSetPPC };

static CONST_STRPTR stub_CS_NeverCalledGetLocaleStrPPC(ULONG *regarray)
{
	struct Library *Base = (struct Library *) regarray[REG68K_A6/4];
	struct ExtendedLibrary *ExtLib = (struct ExtendedLibrary *) ((ULONG)Base + Base->lib_PosSize);
	struct CharsetIFace *Self = (struct CharsetIFace *) ExtLib->MainIFace;

	return Self->CS_NeverCalledGetLocaleStr(
		(ULONG)regarray[0]
	);
}
STATIC CONST struct EmuTrap stub_CS_NeverCalledGetLocaleStr = { TRAPINST, TRAPTYPE, (ULONG (*)(ULONG *))stub_CS_NeverCalledGetLocaleStrPPC };

static LONG stub_CS_IsAlNumPPC(ULONG *regarray)
{
	struct Library *Base = (struct Library *) regarray[REG68K_A6/4];
	struct ExtendedLibrary *ExtLib = (struct ExtendedLibrary *) ((ULONG)Base + Base->lib_PosSize);
	struct CharsetIFace *Self = (struct CharsetIFace *) ExtLib->MainIFace;

	return Self->CS_IsAlNum(
		(ULONG)regarray[0]
	);
}
STATIC CONST struct EmuTrap stub_CS_IsAlNum = { TRAPINST, TRAPTYPE, (ULONG (*)(ULONG *))stub_CS_IsAlNumPPC };

static LONG stub_CS_IsAlphaPPC(ULONG *regarray)
{
	struct Library *Base = (struct Library *) regarray[REG68K_A6/4];
	struct ExtendedLibrary *ExtLib = (struct ExtendedLibrary *) ((ULONG)Base + Base->lib_PosSize);
	struct CharsetIFace *Self = (struct CharsetIFace *) ExtLib->MainIFace;

	return Self->CS_IsAlpha(
		(ULONG)regarray[0]
	);
}
STATIC CONST struct EmuTrap stub_CS_IsAlpha = { TRAPINST, TRAPTYPE, (ULONG (*)(ULONG *))stub_CS_IsAlphaPPC };

static LONG stub_CS_IsCntrlPPC(ULONG *regarray)
{
	struct Library *Base = (struct Library *) regarray[REG68K_A6/4];
	struct ExtendedLibrary *ExtLib = (struct ExtendedLibrary *) ((ULONG)Base + Base->lib_PosSize);
	struct CharsetIFace *Self = (struct CharsetIFace *) ExtLib->MainIFace;

	return Self->CS_IsCntrl(
		(ULONG)regarray[0]
	);
}
STATIC CONST struct EmuTrap stub_CS_IsCntrl = { TRAPINST, TRAPTYPE, (ULONG (*)(ULONG *))stub_CS_IsCntrlPPC };

static LONG stub_CS_IsDigitPPC(ULONG *regarray)
{
	struct Library *Base = (struct Library *) regarray[REG68K_A6/4];
	struct ExtendedLibrary *ExtLib = (struct ExtendedLibrary *) ((ULONG)Base + Base->lib_PosSize);
	struct CharsetIFace *Self = (struct CharsetIFace *) ExtLib->MainIFace;

	return Self->CS_IsDigit(
		(ULONG)regarray[0]
	);
}
STATIC CONST struct EmuTrap stub_CS_IsDigit = { TRAPINST, TRAPTYPE, (ULONG (*)(ULONG *))stub_CS_IsDigitPPC };

static LONG stub_CS_IsGraphPPC(ULONG *regarray)
{
	struct Library *Base = (struct Library *) regarray[REG68K_A6/4];
	struct ExtendedLibrary *ExtLib = (struct ExtendedLibrary *) ((ULONG)Base + Base->lib_PosSize);
	struct CharsetIFace *Self = (struct CharsetIFace *) ExtLib->MainIFace;

	return Self->CS_IsGraph(
		(ULONG)regarray[0]
	);
}
STATIC CONST struct EmuTrap stub_CS_IsGraph = { TRAPINST, TRAPTYPE, (ULONG (*)(ULONG *))stub_CS_IsGraphPPC };

static LONG stub_CS_IsLowerPPC(ULONG *regarray)
{
	struct Library *Base = (struct Library *) regarray[REG68K_A6/4];
	struct ExtendedLibrary *ExtLib = (struct ExtendedLibrary *) ((ULONG)Base + Base->lib_PosSize);
	struct CharsetIFace *Self = (struct CharsetIFace *) ExtLib->MainIFace;

	return Self->CS_IsLower(
		(ULONG)regarray[0]
	);
}
STATIC CONST struct EmuTrap stub_CS_IsLower = { TRAPINST, TRAPTYPE, (ULONG (*)(ULONG *))stub_CS_IsLowerPPC };

static LONG stub_CS_IsPrintPPC(ULONG *regarray)
{
	struct Library *Base = (struct Library *) regarray[REG68K_A6/4];
	struct ExtendedLibrary *ExtLib = (struct ExtendedLibrary *) ((ULONG)Base + Base->lib_PosSize);
	struct CharsetIFace *Self = (struct CharsetIFace *) ExtLib->MainIFace;

	return Self->CS_IsPrint(
		(ULONG)regarray[0]
	);
}
STATIC CONST struct EmuTrap stub_CS_IsPrint = { TRAPINST, TRAPTYPE, (ULONG (*)(ULONG *))stub_CS_IsPrintPPC };

static LONG stub_CS_IsPunctPPC(ULONG *regarray)
{
	struct Library *Base = (struct Library *) regarray[REG68K_A6/4];
	struct ExtendedLibrary *ExtLib = (struct ExtendedLibrary *) ((ULONG)Base + Base->lib_PosSize);
	struct CharsetIFace *Self = (struct CharsetIFace *) ExtLib->MainIFace;

	return Self->CS_IsPunct(
		(ULONG)regarray[0]
	);
}
STATIC CONST struct EmuTrap stub_CS_IsPunct = { TRAPINST, TRAPTYPE, (ULONG (*)(ULONG *))stub_CS_IsPunctPPC };

static LONG stub_CS_IsSpacePPC(ULONG *regarray)
{
	struct Library *Base = (struct Library *) regarray[REG68K_A6/4];
	struct ExtendedLibrary *ExtLib = (struct ExtendedLibrary *) ((ULONG)Base + Base->lib_PosSize);
	struct CharsetIFace *Self = (struct CharsetIFace *) ExtLib->MainIFace;

	return Self->CS_IsSpace(
		(ULONG)regarray[0]
	);
}
STATIC CONST struct EmuTrap stub_CS_IsSpace = { TRAPINST, TRAPTYPE, (ULONG (*)(ULONG *))stub_CS_IsSpacePPC };

static LONG stub_CS_IsUpperPPC(ULONG *regarray)
{
	struct Library *Base = (struct Library *) regarray[REG68K_A6/4];
	struct ExtendedLibrary *ExtLib = (struct ExtendedLibrary *) ((ULONG)Base + Base->lib_PosSize);
	struct CharsetIFace *Self = (struct CharsetIFace *) ExtLib->MainIFace;

	return Self->CS_IsUpper(
		(ULONG)regarray[0]
	);
}
STATIC CONST struct EmuTrap stub_CS_IsUpper = { TRAPINST, TRAPTYPE, (ULONG (*)(ULONG *))stub_CS_IsUpperPPC };

static LONG stub_CS_IsXDigitPPC(ULONG *regarray)
{
	struct Library *Base = (struct Library *) regarray[REG68K_A6/4];
	struct ExtendedLibrary *ExtLib = (struct ExtendedLibrary *) ((ULONG)Base + Base->lib_PosSize);
	struct CharsetIFace *Self = (struct CharsetIFace *) ExtLib->MainIFace;

	return Self->CS_IsXDigit(
		(ULONG)regarray[0]
	);
}
STATIC CONST struct EmuTrap stub_CS_IsXDigit = { TRAPINST, TRAPTYPE, (ULONG (*)(ULONG *))stub_CS_IsXDigitPPC };

static ULONG stub_CS_StrConvertPPC(ULONG *regarray)
{
	struct Library *Base = (struct Library *) regarray[REG68K_A6/4];
	struct ExtendedLibrary *ExtLib = (struct ExtendedLibrary *) ((ULONG)Base + Base->lib_PosSize);
	struct CharsetIFace *Self = (struct CharsetIFace *) ExtLib->MainIFace;

	return Self->CS_StrConvert(
		(CONST_STRPTR)regarray[9],
		(APTR)regarray[10],
		(ULONG)regarray[0],
		(ULONG)regarray[1]
	);
}
STATIC CONST struct EmuTrap stub_CS_StrConvert = { TRAPINST, TRAPTYPE, (ULONG (*)(ULONG *))stub_CS_StrConvertPPC };

static LONG stub_CS_StrnCmpPPC(ULONG *regarray)
{
	struct Library *Base = (struct Library *) regarray[REG68K_A6/4];
	struct ExtendedLibrary *ExtLib = (struct ExtendedLibrary *) ((ULONG)Base + Base->lib_PosSize);
	struct CharsetIFace *Self = (struct CharsetIFace *) ExtLib->MainIFace;

	return Self->CS_StrnCmp(
		(CONST_STRPTR)regarray[9],
		(CONST_STRPTR)regarray[10],
		(LONG)regarray[0],
		(ULONG)regarray[1]
	);
}
STATIC CONST struct EmuTrap stub_CS_StrnCmp = { TRAPINST, TRAPTYPE, (ULONG (*)(ULONG *))stub_CS_StrnCmpPPC };

static LONG stub_CS_IsBlankPPC(ULONG *regarray)
{
	struct Library *Base = (struct Library *) regarray[REG68K_A6/4];
	struct ExtendedLibrary *ExtLib = (struct ExtendedLibrary *) ((ULONG)Base + Base->lib_PosSize);
	struct CharsetIFace *Self = (struct CharsetIFace *) ExtLib->MainIFace;

	return Self->CS_IsBlank(
		(ULONG)regarray[0]
	);
}
STATIC CONST struct EmuTrap stub_CS_IsBlank = { TRAPINST, TRAPTYPE, (ULONG (*)(ULONG *))stub_CS_IsBlankPPC };

CONST APTR VecTable68K[] =
{
	&stub_Open,
	&stub_Close,
	&stub_Expunge,
	&stub_Reserved,
	&stub_CS_GetDriverInfo,
	&stub_CS_ConvToLower,
	&stub_CS_ConvToUpper,
	&stub_CS_NeverCalledGetCodeSet,
	&stub_CS_NeverCalledGetLocaleStr,
	&stub_CS_IsAlNum,
	&stub_CS_IsAlpha,
	&stub_CS_IsCntrl,
	&stub_CS_IsDigit,
	&stub_CS_IsGraph,
	&stub_CS_IsLower,
	&stub_CS_IsPrint,
	&stub_CS_IsPunct,
	&stub_CS_IsSpace,
	&stub_CS_IsUpper,
	&stub_CS_IsXDigit,
	&stub_CS_StrConvert,
	&stub_CS_StrnCmp,
	&stub_CS_IsBlank,
	(APTR)-1
};
