#ifndef AMIGAINPUT_INTERFACE_DEF_H
#define AMIGAINPUT_INTERFACE_DEF_H

/*
** This file was machine generated by idltool 53.34.
** Do not edit
*/ 

#ifndef EXEC_TYPES_H
#include <exec/types.h>
#endif
#ifndef EXEC_EXEC_H
#include <exec/exec.h>
#endif
#ifndef EXEC_INTERFACES_H
#include <exec/interfaces.h>
#endif

#ifndef AMIGAINPUT_AMIGAINPUT_H
#include <amigainput/amigainput.h>
#endif
#ifndef UTILITY_TAGITEM_H
#include <utility/tagitem.h>
#endif

#ifdef __cplusplus
#ifdef __USE_AMIGAOS_NAMESPACE__
namespace AmigaOS {
#endif
extern "C" {
#endif

struct AIN_IFace
{
	struct InterfaceData Data;

	uint32 APICALL (*Obtain)(struct AIN_IFace *Self);
	uint32 APICALL (*Release)(struct AIN_IFace *Self);
	APTR Expunge_UNIMPLEMENTED;
	APTR Clone_UNIMPLEMENTED;
	ULONG APICALL (*AIN_GetError)(struct AIN_IFace *Self, APTR ctx);
	STRPTR APICALL (*AIN_GetErrorString)(struct AIN_IFace *Self, ULONG error_code);
	APTR APICALL (*AIN_CreateContext)(struct AIN_IFace *Self, ULONG api_version, struct TagItem * tags);
	VOID APICALL (*AIN_DeleteContext)(struct AIN_IFace *Self, APTR ctx);
	BOOL APICALL (*AIN_EnumDevices)(struct AIN_IFace *Self, APTR ctx, APTR enumfunc, APTR user_data);
	BOOL APICALL (*AIN_Query)(struct AIN_IFace *Self, APTR ctx, AIN_DeviceID device_id, ULONG qParameter, ULONG qArg, APTR result, ULONG result_length);
	AIN_DeviceHandle * APICALL (*AIN_ObtainDevice)(struct AIN_IFace *Self, APTR ctx, AIN_DeviceID device_id);
	VOID APICALL (*AIN_ReleaseDevice)(struct AIN_IFace *Self, APTR ctx, AIN_DeviceHandle * handle);
	BOOL APICALL (*AIN_SetDeviceParameter)(struct AIN_IFace *Self, APTR ctx, AIN_DeviceHandle * handle, ULONG dParameter, ULONG dArg);
	AIN_InputEvent * APICALL (*AIN_GetEvent)(struct AIN_IFace *Self, APTR ctx);
	VOID APICALL (*AIN_FreeEvent)(struct AIN_IFace *Self, APTR ctx, AIN_InputEvent * event);
	BOOL APICALL (*AIN_ReadDevice)(struct AIN_IFace *Self, APTR ctx, AIN_DeviceHandle * handle, APTR * data);
	BOOL APICALL (*AIN_Set)(struct AIN_IFace *Self, APTR ctx, struct TagItem * tags);
	struct _AIN_RequesterResult * APICALL (*AIN_RequestDevice)(struct AIN_IFace *Self, APTR ctx, struct TagItem * tags);
	VOID APICALL (*AIN_FreeRequest)(struct AIN_IFace *Self, APTR ctx, struct _AIN_RequesterResult * result);
};

#ifdef __cplusplus
}
#ifdef __USE_AMIGAOS_NAMESPACE__
}
#endif
#endif

#endif /* AMIGAINPUT_INTERFACE_DEF_H */
