#ifndef AREXX_INTERFACE_DEF_H
#define AREXX_INTERFACE_DEF_H

/*
** This file was machine generated by idltool 52.6.
** Do not edit
*/ 

#ifndef EXEC_TYPES_H
#include <exec/types.h>
#endif
#ifndef EXEC_EXEC_H
#include <exec/exec.h>
#endif
#ifndef EXEC_INTERFACES_H
#include <exec/interfaces.h>
#endif

#ifndef INTUITION_INTUITION_H
#include <intuition/intuition.h>
#endif
#ifndef INTUITION_CLASSES_H
#include <intuition/classes.h>
#endif

#ifdef __cplusplus
#ifdef __USE_AMIGAOS_NAMESPACE__
namespace AmigaOS {
#endif
extern "C" {
#endif

struct ARexxIFace
{
	struct InterfaceData Data;

	ULONG APICALL (*Obtain)(struct ARexxIFace *Self);
	ULONG APICALL (*Release)(struct ARexxIFace *Self);
	void APICALL (*Expunge)(struct ARexxIFace *Self);
	struct Interface * APICALL (*Clone)(struct ARexxIFace *Self);
	Class * APICALL (*AREXX_GetClass)(struct ARexxIFace *Self);
};

#ifdef __cplusplus
}
#ifdef __USE_AMIGAOS_NAMESPACE__
}
#endif
#endif

#endif /* AREXX_INTERFACE_DEF_H */
