#ifndef BATTMEM_INTERFACE_DEF_H
#define BATTMEM_INTERFACE_DEF_H

/*
** This file was machine generated by idltool 52.6.
** Do not edit
*/ 

#ifndef EXEC_TYPES_H
#include <exec/types.h>
#endif
#ifndef EXEC_EXEC_H
#include <exec/exec.h>
#endif
#ifndef EXEC_INTERFACES_H
#include <exec/interfaces.h>
#endif


#ifdef __cplusplus
#ifdef __USE_AMIGAOS_NAMESPACE__
namespace AmigaOS {
#endif
extern "C" {
#endif

struct BattMemIFace
{
	struct InterfaceData Data;

	ULONG APICALL (*Obtain)(struct BattMemIFace *Self);
	ULONG APICALL (*Release)(struct BattMemIFace *Self);
	void APICALL (*Expunge)(struct BattMemIFace *Self);
	struct Interface * APICALL (*Clone)(struct BattMemIFace *Self);
	VOID APICALL (*ObtainBattSemaphore)(struct BattMemIFace *Self);
	VOID APICALL (*ReleaseBattSemaphore)(struct BattMemIFace *Self);
	ULONG APICALL (*ReadBattMem)(struct BattMemIFace *Self, APTR buffer, ULONG offset, ULONG length);
	ULONG APICALL (*WriteBattMem)(struct BattMemIFace *Self, CONST_APTR buffer, ULONG offset, ULONG length);
};

#ifdef __cplusplus
}
#ifdef __USE_AMIGAOS_NAMESPACE__
}
#endif
#endif

#endif /* BATTMEM_INTERFACE_DEF_H */
