#ifndef BOOTSD_INTERFACE_DEF_H
#define BOOTSD_INTERFACE_DEF_H

/*
** This file was machine generated by idltool 53.6.
** Do not edit
*/ 

#ifndef EXEC_TYPES_H
#include <exec/types.h>
#endif
#ifndef EXEC_EXEC_H
#include <exec/exec.h>
#endif
#ifndef EXEC_INTERFACES_H
#include <exec/interfaces.h>
#endif


#ifdef __cplusplus
#ifdef __USE_AMIGAOS_NAMESPACE__
namespace AmigaOS {
#endif
extern "C" {
#endif

struct BootSDIFace
{
	struct InterfaceData Data;

	uint32 APICALL (*Obtain)(struct BootSDIFace *Self);
	uint32 APICALL (*Release)(struct BootSDIFace *Self);
	void APICALL (*Expunge)(struct BootSDIFace *Self);
	struct Interface * APICALL (*Clone)(struct BootSDIFace *Self);
	APTR APICALL (*AllocResource)(struct BootSDIFace *Self, int32 * error);
	BOOL APICALL (*FreeResource)(struct BootSDIFace *Self, APTR unit);
	APTR APICALL (*GetGeometry)(struct BootSDIFace *Self, APTR unit, int32 * error, struct DosEnvec * geom);
	uint32 APICALL (*ReadSDCard)(struct BootSDIFace *Self, APTR unit, int32 * error, APTR buffer, uint32 startBlock, uint32 numBlocks);
	uint32 APICALL (*WriteSDCard)(struct BootSDIFace *Self, APTR unit, int32 * error, APTR buffer, uint32 startBlock, uint32 numBlocks);
};

#ifdef __cplusplus
}
#ifdef __USE_AMIGAOS_NAMESPACE__
}
#endif
#endif

#endif /* BOOTSD_INTERFACE_DEF_H */
