#ifndef CHOOSER_INTERFACE_DEF_H
#define CHOOSER_INTERFACE_DEF_H

/*
** This file was machine generated by idltool 52.6.
** Do not edit
*/ 

#ifndef EXEC_TYPES_H
#include <exec/types.h>
#endif
#ifndef EXEC_EXEC_H
#include <exec/exec.h>
#endif
#ifndef EXEC_INTERFACES_H
#include <exec/interfaces.h>
#endif

#ifndef INTUITION_INTUITION_H
#include <intuition/intuition.h>
#endif
#ifndef INTUITION_CLASSES_H
#include <intuition/classes.h>
#endif

#ifdef __cplusplus
#ifdef __USE_AMIGAOS_NAMESPACE__
namespace AmigaOS {
#endif
extern "C" {
#endif

struct ChooserIFace
{
	struct InterfaceData Data;

	ULONG APICALL (*Obtain)(struct ChooserIFace *Self);
	ULONG APICALL (*Release)(struct ChooserIFace *Self);
	void APICALL (*Expunge)(struct ChooserIFace *Self);
	struct Interface * APICALL (*Clone)(struct ChooserIFace *Self);
	Class * APICALL (*CHOOSER_GetClass)(struct ChooserIFace *Self);
	struct Node * APICALL (*AllocChooserNodeA)(struct ChooserIFace *Self, struct TagItem * tags);
	struct Node * APICALL (*AllocChooserNode)(struct ChooserIFace *Self, ...);
	VOID APICALL (*FreeChooserNode)(struct ChooserIFace *Self, struct Node * node);
	VOID APICALL (*SetChooserNodeAttrsA)(struct ChooserIFace *Self, struct Node * node, struct TagItem * tags);
	VOID APICALL (*SetChooserNodeAttrs)(struct ChooserIFace *Self, struct Node * node, ...);
	VOID APICALL (*GetChooserNodeAttrsA)(struct ChooserIFace *Self, struct Node * node, struct TagItem * tags);
	VOID APICALL (*GetChooserNodeAttrs)(struct ChooserIFace *Self, struct Node * node, ...);
};

#ifdef __cplusplus
}
#ifdef __USE_AMIGAOS_NAMESPACE__
}
#endif
#endif

#endif /* CHOOSER_INTERFACE_DEF_H */
