#ifndef CIA_INTERFACE_DEF_H
#define CIA_INTERFACE_DEF_H

/*
** This file was machine generated by idltool 52.6.
** Do not edit
*/ 

#ifndef EXEC_TYPES_H
#include <exec/types.h>
#endif
#ifndef EXEC_EXEC_H
#include <exec/exec.h>
#endif
#ifndef EXEC_INTERFACES_H
#include <exec/interfaces.h>
#endif

#ifndef EXEC_INTERRUPTS_H
#include <exec/interrupts.h>
#endif
#ifndef EXEC_LIBRARIES_H
#include <exec/libraries.h>
#endif

#ifdef __cplusplus
#ifdef __USE_AMIGAOS_NAMESPACE__
namespace AmigaOS {
#endif
extern "C" {
#endif

struct CIAIFace
{
	struct InterfaceData Data;

	ULONG APICALL (*Obtain)(struct CIAIFace *Self);
	ULONG APICALL (*Release)(struct CIAIFace *Self);
	void APICALL (*Expunge)(struct CIAIFace *Self);
	struct Interface * APICALL (*Clone)(struct CIAIFace *Self);
	struct Interrupt * APICALL (*AddICRVector)(struct CIAIFace *Self, struct Library * resource, WORD iCRBit, struct Interrupt * interrupt);
	VOID APICALL (*RemICRVector)(struct CIAIFace *Self, struct Library * resource, WORD iCRBit, struct Interrupt * interrupt);
	WORD APICALL (*AbleICR)(struct CIAIFace *Self, struct Library * resource, WORD mask);
	WORD APICALL (*SetICR)(struct CIAIFace *Self, struct Library * resource, WORD mask);
};

#ifdef __cplusplus
}
#ifdef __USE_AMIGAOS_NAMESPACE__
}
#endif
#endif

#endif /* CIA_INTERFACE_DEF_H */
