#ifndef DATEBROWSER_INTERFACE_DEF_H
#define DATEBROWSER_INTERFACE_DEF_H

/*
** This file was machine generated by idltool 52.6.
** Do not edit
*/ 

#ifndef EXEC_TYPES_H
#include <exec/types.h>
#endif
#ifndef EXEC_EXEC_H
#include <exec/exec.h>
#endif
#ifndef EXEC_INTERFACES_H
#include <exec/interfaces.h>
#endif

#ifndef INTUITION_INTUITION_H
#include <intuition/intuition.h>
#endif
#ifndef INTUITION_CLASSES_H
#include <intuition/classes.h>
#endif

#ifdef __cplusplus
#ifdef __USE_AMIGAOS_NAMESPACE__
namespace AmigaOS {
#endif
extern "C" {
#endif

struct DateBrowserIFace
{
	struct InterfaceData Data;

	ULONG APICALL (*Obtain)(struct DateBrowserIFace *Self);
	ULONG APICALL (*Release)(struct DateBrowserIFace *Self);
	void APICALL (*Expunge)(struct DateBrowserIFace *Self);
	struct Interface * APICALL (*Clone)(struct DateBrowserIFace *Self);
	Class * APICALL (*DATEBROWSER_GetClass)(struct DateBrowserIFace *Self);
	UWORD APICALL (*JulianWeekDay)(struct DateBrowserIFace *Self, UWORD day, UWORD month, LONG year);
	UWORD APICALL (*JulianMonthDays)(struct DateBrowserIFace *Self, UWORD month, LONG year);
	BOOL APICALL (*JulianLeapYear)(struct DateBrowserIFace *Self, LONG year);
};

#ifdef __cplusplus
}
#ifdef __USE_AMIGAOS_NAMESPACE__
}
#endif
#endif

#endif /* DATEBROWSER_INTERFACE_DEF_H */
