#ifndef GADTOOLS_INTERFACE_DEF_H
#define GADTOOLS_INTERFACE_DEF_H

/*
** This file was machine generated by idltool 52.6.
** Do not edit
*/ 

#ifndef EXEC_TYPES_H
#include <exec/types.h>
#endif
#ifndef EXEC_EXEC_H
#include <exec/exec.h>
#endif
#ifndef EXEC_INTERFACES_H
#include <exec/interfaces.h>
#endif

#ifndef EXEC_LIBRARIES_H
#include <exec/libraries.h>
#endif
#ifndef INTUITION_INTUITION_H
#include <intuition/intuition.h>
#endif
#ifndef UTILITY_TAGITEM_H
#include <utility/tagitem.h>
#endif
#ifndef LIBRARIES_GADTOOLS_H
#include <libraries/gadtools.h>
#endif

#ifdef __cplusplus
#ifdef __USE_AMIGAOS_NAMESPACE__
namespace AmigaOS {
#endif
extern "C" {
#endif

struct GadToolsIFace
{
	struct InterfaceData Data;

	ULONG APICALL (*Obtain)(struct GadToolsIFace *Self);
	ULONG APICALL (*Release)(struct GadToolsIFace *Self);
	void APICALL (*Expunge)(struct GadToolsIFace *Self);
	struct Interface * APICALL (*Clone)(struct GadToolsIFace *Self);
	struct Gadget * APICALL (*CreateGadgetA)(struct GadToolsIFace *Self, ULONG kind, struct Gadget * gad, const struct NewGadget * ng, const struct TagItem * taglist);
	struct Gadget * APICALL (*CreateGadget)(struct GadToolsIFace *Self, ULONG kind, struct Gadget * gad, const struct NewGadget * ng, ...);
	VOID APICALL (*FreeGadgets)(struct GadToolsIFace *Self, struct Gadget * gad);
	VOID APICALL (*GT_SetGadgetAttrsA)(struct GadToolsIFace *Self, struct Gadget * gad, struct Window * win, struct Requester * req, const struct TagItem * taglist);
	VOID APICALL (*GT_SetGadgetAttrs)(struct GadToolsIFace *Self, struct Gadget * gad, struct Window * win, struct Requester * req, ...);
	struct Menu * APICALL (*CreateMenusA)(struct GadToolsIFace *Self, const struct NewMenu * newmenu, const struct TagItem * taglist);
	struct Menu * APICALL (*CreateMenus)(struct GadToolsIFace *Self, const struct NewMenu * newmenu, ...);
	VOID APICALL (*FreeMenus)(struct GadToolsIFace *Self, struct Menu * menu);
	BOOL APICALL (*LayoutMenuItemsA)(struct GadToolsIFace *Self, struct MenuItem * firstitem, APTR vi, const struct TagItem * taglist);
	BOOL APICALL (*LayoutMenuItems)(struct GadToolsIFace *Self, struct MenuItem * firstitem, APTR vi, ...);
	BOOL APICALL (*LayoutMenusA)(struct GadToolsIFace *Self, struct Menu * firstmenu, APTR vi, const struct TagItem * taglist);
	BOOL APICALL (*LayoutMenus)(struct GadToolsIFace *Self, struct Menu * firstmenu, APTR vi, ...);
	struct IntuiMessage * APICALL (*GT_GetIMsg)(struct GadToolsIFace *Self, struct MsgPort * iport);
	VOID APICALL (*GT_ReplyIMsg)(struct GadToolsIFace *Self, struct IntuiMessage * imsg);
	VOID APICALL (*GT_RefreshWindow)(struct GadToolsIFace *Self, struct Window * win, struct Requester * req);
	VOID APICALL (*GT_BeginRefresh)(struct GadToolsIFace *Self, struct Window * win);
	VOID APICALL (*GT_EndRefresh)(struct GadToolsIFace *Self, struct Window * win, BOOL complete);
	struct IntuiMessage * APICALL (*GT_FilterIMsg)(struct GadToolsIFace *Self, const struct IntuiMessage * imsg);
	struct IntuiMessage * APICALL (*GT_PostFilterIMsg)(struct GadToolsIFace *Self, struct IntuiMessage * imsg);
	struct Gadget * APICALL (*CreateContext)(struct GadToolsIFace *Self, struct Gadget ** glistptr);
	VOID APICALL (*DrawBevelBoxA)(struct GadToolsIFace *Self, struct RastPort * rport, WORD left, WORD top, WORD width, WORD height, const struct TagItem * taglist);
	VOID APICALL (*DrawBevelBox)(struct GadToolsIFace *Self, struct RastPort * rport, WORD left, WORD top, WORD width, WORD height, ...);
	APTR APICALL (*GetVisualInfoA)(struct GadToolsIFace *Self, struct Screen * screen, const struct TagItem * taglist);
	APTR APICALL (*GetVisualInfo)(struct GadToolsIFace *Self, struct Screen * screen, ...);
	VOID APICALL (*FreeVisualInfo)(struct GadToolsIFace *Self, APTR vi);
	VOID APICALL (*GTReserved0)(struct GadToolsIFace *Self);
	VOID APICALL (*GTReserved1)(struct GadToolsIFace *Self);
	VOID APICALL (*GTReserved2)(struct GadToolsIFace *Self);
	VOID APICALL (*GTReserved3)(struct GadToolsIFace *Self);
	VOID APICALL (*GTReserved4)(struct GadToolsIFace *Self);
	VOID APICALL (*GTReserved5)(struct GadToolsIFace *Self);
	LONG APICALL (*GT_GetGadgetAttrsA)(struct GadToolsIFace *Self, struct Gadget * gad, struct Window * win, struct Requester * req, const struct TagItem * taglist);
	LONG APICALL (*GT_GetGadgetAttrs)(struct GadToolsIFace *Self, struct Gadget * gad, struct Window * win, struct Requester * req, ...);
};

#ifdef __cplusplus
}
#ifdef __USE_AMIGAOS_NAMESPACE__
}
#endif
#endif

#endif /* GADTOOLS_INTERFACE_DEF_H */
