#ifndef IFFPARSE_INTERFACE_DEF_H
#define IFFPARSE_INTERFACE_DEF_H

/*
** This file was machine generated by idltool 52.6.
** Do not edit
*/ 

#ifndef EXEC_TYPES_H
#include <exec/types.h>
#endif
#ifndef EXEC_EXEC_H
#include <exec/exec.h>
#endif
#ifndef EXEC_INTERFACES_H
#include <exec/interfaces.h>
#endif

#ifndef LIBRARIES_IFFPARSE_H
#include <libraries/iffparse.h>
#endif
#ifndef UTILITY_HOOKS_H
#include <utility/hooks.h>
#endif

#ifdef __cplusplus
#ifdef __USE_AMIGAOS_NAMESPACE__
namespace AmigaOS {
#endif
extern "C" {
#endif

struct IFFParseIFace
{
	struct InterfaceData Data;

	ULONG APICALL (*Obtain)(struct IFFParseIFace *Self);
	ULONG APICALL (*Release)(struct IFFParseIFace *Self);
	void APICALL (*Expunge)(struct IFFParseIFace *Self);
	struct Interface * APICALL (*Clone)(struct IFFParseIFace *Self);
	struct IFFHandle * APICALL (*AllocIFF)(struct IFFParseIFace *Self);
	LONG APICALL (*OpenIFF)(struct IFFParseIFace *Self, struct IFFHandle * iff, LONG rwMode);
	LONG APICALL (*ParseIFF)(struct IFFParseIFace *Self, struct IFFHandle * iff, LONG control);
	VOID APICALL (*CloseIFF)(struct IFFParseIFace *Self, struct IFFHandle * iff);
	VOID APICALL (*FreeIFF)(struct IFFParseIFace *Self, struct IFFHandle * iff);
	LONG APICALL (*ReadChunkBytes)(struct IFFParseIFace *Self, struct IFFHandle * iff, APTR buf, LONG numBytes);
	LONG APICALL (*WriteChunkBytes)(struct IFFParseIFace *Self, struct IFFHandle * iff, CONST_APTR buf, LONG numBytes);
	LONG APICALL (*ReadChunkRecords)(struct IFFParseIFace *Self, struct IFFHandle * iff, APTR buf, LONG bytesPerRecord, LONG numRecords);
	LONG APICALL (*WriteChunkRecords)(struct IFFParseIFace *Self, struct IFFHandle * iff, CONST_APTR buf, LONG bytesPerRecord, LONG numRecords);
	LONG APICALL (*PushChunk)(struct IFFParseIFace *Self, struct IFFHandle * iff, LONG type, LONG id, LONG size);
	LONG APICALL (*PopChunk)(struct IFFParseIFace *Self, struct IFFHandle * iff);
	LONG APICALL (*EntryHandler)(struct IFFParseIFace *Self, struct IFFHandle * iff, LONG type, LONG id, LONG position, struct Hook * handler, APTR object);
	LONG APICALL (*ExitHandler)(struct IFFParseIFace *Self, struct IFFHandle * iff, LONG type, LONG id, LONG position, struct Hook * handler, APTR object);
	LONG APICALL (*PropChunk)(struct IFFParseIFace *Self, struct IFFHandle * iff, LONG type, LONG id);
	LONG APICALL (*PropChunks)(struct IFFParseIFace *Self, struct IFFHandle * iff, const LONG * propArray, LONG numPairs);
	LONG APICALL (*StopChunk)(struct IFFParseIFace *Self, struct IFFHandle * iff, LONG type, LONG id);
	LONG APICALL (*StopChunks)(struct IFFParseIFace *Self, struct IFFHandle * iff, const LONG * propArray, LONG numPairs);
	LONG APICALL (*CollectionChunk)(struct IFFParseIFace *Self, struct IFFHandle * iff, LONG type, LONG id);
	LONG APICALL (*CollectionChunks)(struct IFFParseIFace *Self, struct IFFHandle * iff, const LONG * propArray, LONG numPairs);
	LONG APICALL (*StopOnExit)(struct IFFParseIFace *Self, struct IFFHandle * iff, LONG type, LONG id);
	struct StoredProperty * APICALL (*FindProp)(struct IFFParseIFace *Self, const struct IFFHandle * iff, LONG type, LONG id);
	struct CollectionItem * APICALL (*FindCollection)(struct IFFParseIFace *Self, const struct IFFHandle * iff, LONG type, LONG id);
	struct ContextNode * APICALL (*FindPropContext)(struct IFFParseIFace *Self, const struct IFFHandle * iff);
	struct ContextNode * APICALL (*CurrentChunk)(struct IFFParseIFace *Self, const struct IFFHandle * iff);
	struct ContextNode * APICALL (*ParentChunk)(struct IFFParseIFace *Self, const struct ContextNode * contextNode);
	struct LocalContextItem * APICALL (*AllocLocalItem)(struct IFFParseIFace *Self, LONG type, LONG id, LONG ident, LONG dataSize);
	APTR APICALL (*LocalItemData)(struct IFFParseIFace *Self, const struct LocalContextItem * localItem);
	VOID APICALL (*SetLocalItemPurge)(struct IFFParseIFace *Self, struct LocalContextItem * localItem, const struct Hook * purgeHook);
	VOID APICALL (*FreeLocalItem)(struct IFFParseIFace *Self, struct LocalContextItem * localItem);
	struct LocalContextItem * APICALL (*FindLocalItem)(struct IFFParseIFace *Self, const struct IFFHandle * iff, LONG type, LONG id, LONG ident);
	LONG APICALL (*StoreLocalItem)(struct IFFParseIFace *Self, struct IFFHandle * iff, struct LocalContextItem * localItem, LONG position);
	VOID APICALL (*StoreItemInContext)(struct IFFParseIFace *Self, struct IFFHandle * iff, struct LocalContextItem * localItem, struct ContextNode * contextNode);
	VOID APICALL (*InitIFF)(struct IFFParseIFace *Self, struct IFFHandle * iff, LONG flags, const struct Hook * streamHook);
	VOID APICALL (*InitIFFasDOS)(struct IFFParseIFace *Self, struct IFFHandle * iff);
	VOID APICALL (*InitIFFasClip)(struct IFFParseIFace *Self, struct IFFHandle * iff);
	struct ClipboardHandle * APICALL (*OpenClipboard)(struct IFFParseIFace *Self, LONG unitNumber);
	VOID APICALL (*CloseClipboard)(struct IFFParseIFace *Self, struct ClipboardHandle * clipHandle);
	LONG APICALL (*GoodID)(struct IFFParseIFace *Self, LONG id);
	LONG APICALL (*GoodType)(struct IFFParseIFace *Self, LONG type);
	STRPTR APICALL (*IDtoStr)(struct IFFParseIFace *Self, LONG id, STRPTR buf);
};

#ifdef __cplusplus
}
#ifdef __USE_AMIGAOS_NAMESPACE__
}
#endif
#endif

#endif /* IFFPARSE_INTERFACE_DEF_H */
