#ifndef KEYMAP_INTERFACE_DEF_H
#define KEYMAP_INTERFACE_DEF_H

/*
** This file was machine generated by idltool 53.6.
** Do not edit
*/ 

#ifndef EXEC_TYPES_H
#include <exec/types.h>
#endif
#ifndef EXEC_EXEC_H
#include <exec/exec.h>
#endif
#ifndef EXEC_INTERFACES_H
#include <exec/interfaces.h>
#endif

#ifndef DEVICES_INPUTEVENT_H
#include <devices/inputevent.h>
#endif
#ifndef LIBRARIES_KEYMAP_H
#include <libraries/keymap.h>
#endif

#ifdef __cplusplus
#ifdef __USE_AMIGAOS_NAMESPACE__
namespace AmigaOS {
#endif
extern "C" {
#endif

struct KeymapIFace
{
	struct InterfaceData Data;

	uint32 APICALL (*Obtain)(struct KeymapIFace *Self);
	uint32 APICALL (*Release)(struct KeymapIFace *Self);
	void APICALL (*Expunge)(struct KeymapIFace *Self);
	struct Interface * APICALL (*Clone)(struct KeymapIFace *Self);
	VOID APICALL (*SetKeyMapDefault)(struct KeymapIFace *Self, const struct KeyMap * keyMap);
	struct KeyMap * APICALL (*AskKeyMapDefault)(struct KeymapIFace *Self);
	int16 APICALL (*MapRawKey)(struct KeymapIFace *Self, const struct InputEvent * event, STRPTR buffer, int16 length, const struct KeyMap * keyMap);
	int32 APICALL (*MapANSI)(struct KeymapIFace *Self, CONST_STRPTR string, int32 count, STRPTR buffer, int32 length, const struct KeyMap * keyMap);
	APTR APICALL (*OpenKeyMapHandleA)(struct KeymapIFace *Self, CONST_STRPTR filename, const struct TagItem * taglist);
	APTR APICALL (*OpenKeyMapHandle)(struct KeymapIFace *Self, CONST_STRPTR filename, ...);
	VOID APICALL (*CloseKeyMapHandle)(struct KeymapIFace *Self, APTR handle);
	uint32 APICALL (*ObtainKeyMapInfoA)(struct KeymapIFace *Self, APTR handle, const struct TagItem * taglist);
	uint32 APICALL (*ObtainKeyMapInfo)(struct KeymapIFace *Self, APTR handle, ...);
	VOID APICALL (*ReleaseKeyMapInfoA)(struct KeymapIFace *Self, APTR handle, const struct TagItem * taglist);
	VOID APICALL (*ReleaseKeyMapInfo)(struct KeymapIFace *Self, APTR handle, ...);
	VOID APICALL (*ObtainRawKeyInfoA)(struct KeymapIFace *Self, const struct TagItem * taglist);
	VOID APICALL (*ObtainRawKeyInfo)(struct KeymapIFace *Self, ...);
	uint32 APICALL (*KeyMapControlTagList)(struct KeymapIFace *Self, const struct TagItem * tags);
	uint32 APICALL (*KeyMapControlTags)(struct KeymapIFace *Self, ...);
};

#ifdef __cplusplus
}
#ifdef __USE_AMIGAOS_NAMESPACE__
}
#endif
#endif

#endif /* KEYMAP_INTERFACE_DEF_H */
