#ifndef LAYOUT_INTERFACE_DEF_H
#define LAYOUT_INTERFACE_DEF_H

/*
** This file was machine generated by idltool 52.6.
** Do not edit
*/ 

#ifndef EXEC_TYPES_H
#include <exec/types.h>
#endif
#ifndef EXEC_EXEC_H
#include <exec/exec.h>
#endif
#ifndef EXEC_INTERFACES_H
#include <exec/interfaces.h>
#endif

#ifndef INTUITION_INTUITION_H
#include <intuition/intuition.h>
#endif
#ifndef INTUITION_CLASSES_H
#include <intuition/classes.h>
#endif
#ifndef GADGETS_LAYOUT_H
#include <gadgets/layout.h>
#endif

#ifdef __cplusplus
#ifdef __USE_AMIGAOS_NAMESPACE__
namespace AmigaOS {
#endif
extern "C" {
#endif

struct LayoutIFace
{
	struct InterfaceData Data;

	ULONG APICALL (*Obtain)(struct LayoutIFace *Self);
	ULONG APICALL (*Release)(struct LayoutIFace *Self);
	void APICALL (*Expunge)(struct LayoutIFace *Self);
	struct Interface * APICALL (*Clone)(struct LayoutIFace *Self);
	Class * APICALL (*LAYOUT_GetClass)(struct LayoutIFace *Self);
	BOOL APICALL (*ActivateLayoutGadget)(struct LayoutIFace *Self, struct Gadget * gadget, struct Window * window, struct Requester * requester, ULONG object);
	VOID APICALL (*FlushLayoutDomainCache)(struct LayoutIFace *Self, struct Gadget * gadget);
	BOOL APICALL (*RethinkLayout)(struct LayoutIFace *Self, struct Gadget * gadget, struct Window * window, struct Requester * requester, BOOL refresh);
	VOID APICALL (*LayoutLimits)(struct LayoutIFace *Self, struct Gadget * gadget, struct LayoutLimits * limits, struct TextFont * font, struct Screen * screen);
	Class * APICALL (*PAGE_GetClass)(struct LayoutIFace *Self);
	ULONG APICALL (*SetPageGadgetAttrsA)(struct LayoutIFace *Self, struct Gadget * gadget, Object * object, struct Window * window, struct Requester * requester, struct TagItem * tags);
	ULONG APICALL (*SetPageGadgetAttrs)(struct LayoutIFace *Self, struct Gadget * gadget, Object * object, struct Window * window, struct Requester * requester, ...);
	VOID APICALL (*RefreshPageGadget)(struct LayoutIFace *Self, struct Gadget * gadget, Object * object, struct Window * window, struct Requester * requester);
};

#ifdef __cplusplus
}
#ifdef __USE_AMIGAOS_NAMESPACE__
}
#endif
#endif

#endif /* LAYOUT_INTERFACE_DEF_H */
