#ifndef LOWLEVEL_INTERFACE_DEF_H
#define LOWLEVEL_INTERFACE_DEF_H

/*
** This file was machine generated by idltool 52.6.
** Do not edit
*/ 

#ifndef EXEC_TYPES_H
#include <exec/types.h>
#endif
#ifndef EXEC_EXEC_H
#include <exec/exec.h>
#endif
#ifndef EXEC_INTERFACES_H
#include <exec/interfaces.h>
#endif

#ifndef EXEC_INTERRUPTS_H
#include <exec/interrupts.h>
#endif
#ifndef UTILITY_TAGITEM_H
#include <utility/tagitem.h>
#endif
#ifndef DEVICES_TIMER_H
#include <devices/timer.h>
#endif
#ifndef LIBRARIES_LOWLEVEL_H
#include <libraries/lowlevel.h>
#endif

#ifdef __cplusplus
#ifdef __USE_AMIGAOS_NAMESPACE__
namespace AmigaOS {
#endif
extern "C" {
#endif

struct LowLevelIFace
{
	struct InterfaceData Data;

	ULONG APICALL (*Obtain)(struct LowLevelIFace *Self);
	ULONG APICALL (*Release)(struct LowLevelIFace *Self);
	void APICALL (*Expunge)(struct LowLevelIFace *Self);
	struct Interface * APICALL (*Clone)(struct LowLevelIFace *Self);
	ULONG APICALL (*ReadJoyPort)(struct LowLevelIFace *Self, ULONG port);
	UBYTE APICALL (*GetLanguageSelection)(struct LowLevelIFace *Self);
	APTR Private1;
	ULONG APICALL (*GetKey)(struct LowLevelIFace *Self);
	VOID APICALL (*QueryKeys)(struct LowLevelIFace *Self, struct KeyQuery * queryArray, UBYTE arraySize);
	APTR APICALL (*AddKBInt)(struct LowLevelIFace *Self, const APTR intRoutine, const APTR intData);
	VOID APICALL (*RemKBInt)(struct LowLevelIFace *Self, APTR intHandle);
	ULONG APICALL (*SystemControlA)(struct LowLevelIFace *Self, const struct TagItem * tagList);
	ULONG APICALL (*SystemControl)(struct LowLevelIFace *Self, ...);
	APTR APICALL (*AddTimerInt)(struct LowLevelIFace *Self, const APTR intRoutine, const APTR intData);
	VOID APICALL (*RemTimerInt)(struct LowLevelIFace *Self, APTR intHandle);
	VOID APICALL (*StopTimerInt)(struct LowLevelIFace *Self, APTR intHandle);
	VOID APICALL (*StartTimerInt)(struct LowLevelIFace *Self, APTR intHandle, ULONG timeInterval, BOOL continuous);
	ULONG APICALL (*ElapsedTime)(struct LowLevelIFace *Self, struct EClockVal * context);
	APTR APICALL (*AddVBlankInt)(struct LowLevelIFace *Self, const APTR intRoutine, const APTR intData);
	VOID APICALL (*RemVBlankInt)(struct LowLevelIFace *Self, APTR intHandle);
	APTR Private2;
	APTR Private3;
	BOOL APICALL (*SetJoyPortAttrsA)(struct LowLevelIFace *Self, ULONG portNumber, const struct TagItem * tagList);
	BOOL APICALL (*SetJoyPortAttrs)(struct LowLevelIFace *Self, ULONG portNumber, ...);
};

#ifdef __cplusplus
}
#ifdef __USE_AMIGAOS_NAMESPACE__
}
#endif
#endif

#endif /* LOWLEVEL_INTERFACE_DEF_H */
