#ifndef MOUNTER_INTERFACE_DEF_H
#define MOUNTER_INTERFACE_DEF_H

/*
** This file was machine generated by idltool 53.6.
** Do not edit
*/ 

#ifndef EXEC_TYPES_H
#include <exec/types.h>
#endif
#ifndef EXEC_EXEC_H
#include <exec/exec.h>
#endif
#ifndef EXEC_INTERFACES_H
#include <exec/interfaces.h>
#endif

#ifndef UTILITY_UTILITY_H
#include <utility/utility.h>
#endif
#ifndef LIBRARIES_MOUNTER_H
#include <libraries/mounter.h>
#endif

#ifdef __cplusplus
#ifdef __USE_AMIGAOS_NAMESPACE__
namespace AmigaOS {
#endif
extern "C" {
#endif

struct MounterIFace
{
	struct InterfaceData Data;

	ULONG APICALL (*Obtain)(struct MounterIFace *Self);
	ULONG APICALL (*Release)(struct MounterIFace *Self);
	void APICALL (*Expunge)(struct MounterIFace *Self);
	struct Interface * APICALL (*Clone)(struct MounterIFace *Self);
	BOOL APICALL (*AnnounceDevice)(struct MounterIFace *Self, CONST_STRPTR execDeviceName, uint32 unit, struct TagItem * tags);
	BOOL APICALL (*AnnounceDeviceTags)(struct MounterIFace *Self, CONST_STRPTR execDeviceName, uint32 unit, ...);
	VOID APICALL (*DenounceDevice)(struct MounterIFace *Self, CONST_STRPTR execDeviceName, uint32 unit);
};

struct MounterPrivateIFace
{
	struct InterfaceData Data;

	ULONG APICALL (*Obtain)(struct MounterPrivateIFace *Self);
	ULONG APICALL (*Release)(struct MounterPrivateIFace *Self);
	void APICALL (*Expunge)(struct MounterPrivateIFace *Self);
	struct Interface * APICALL (*Clone)(struct MounterPrivateIFace *Self);
	void APICALL (*FullBooted)(struct MounterPrivateIFace *Self);
};

#ifdef __cplusplus
}
#ifdef __USE_AMIGAOS_NAMESPACE__
}
#endif
#endif

#endif /* MOUNTER_INTERFACE_DEF_H */
