#ifndef OPENFIRMWARE_INTERFACE_DEF_H
#define OPENFIRMWARE_INTERFACE_DEF_H

/*
** This file was machine generated by idltool 53.5.
** Do not edit
*/ 

#ifndef EXEC_TYPES_H
#include <exec/types.h>
#endif
#ifndef EXEC_EXEC_H
#include <exec/exec.h>
#endif
#ifndef EXEC_INTERFACES_H
#include <exec/interfaces.h>
#endif

#ifndef RESOURCES_OPENFIRMWARE_H
#include <resources/openfirmware.h>
#endif

#ifdef __cplusplus
#ifdef __USE_AMIGAOS_NAMESPACE__
namespace AmigaOS {
#endif
extern "C" {
#endif

struct OpenFirmwareIFace
{
	struct InterfaceData Data;

	ULONG APICALL (*Obtain)(struct OpenFirmwareIFace *Self);
	ULONG APICALL (*Release)(struct OpenFirmwareIFace *Self);
	void APICALL (*Expunge)(struct OpenFirmwareIFace *Self);
	struct Interface * APICALL (*Clone)(struct OpenFirmwareIFace *Self);
	uint32 APICALL (*CallRTAS)(struct OpenFirmwareIFace *Self, uint32 * packet);
	uint32 APICALL (*GetRTASService)(struct OpenFirmwareIFace *Self, CONST_STRPTR serviceName);
	OFNode APICALL (*Root)(struct OpenFirmwareIFace *Self);
	OFNode APICALL (*Peer)(struct OpenFirmwareIFace *Self, OFNode node);
	OFNode APICALL (*Child)(struct OpenFirmwareIFace *Self, OFNode node);
	OFNode APICALL (*Parent)(struct OpenFirmwareIFace *Self, OFNode node);
	OFProperty APICALL (*FindProp)(struct OpenFirmwareIFace *Self, OFNode node, CONST_STRPTR propname);
	OFProperty APICALL (*FirstProp)(struct OpenFirmwareIFace *Self, OFNode node);
	OFProperty APICALL (*NextProp)(struct OpenFirmwareIFace *Self, OFNode node, OFProperty property);
	uint32 APICALL (*GetPropName)(struct OpenFirmwareIFace *Self, OFProperty property, STRPTR buffer, uint32 bufSize);
	uint32 APICALL (*PropDataSize)(struct OpenFirmwareIFace *Self, OFProperty property);
	uint32 APICALL (*GetPropData)(struct OpenFirmwareIFace *Self, OFProperty property, APTR buffer, uint32 bufSize);
	uint32 APICALL (*GetNumAddressCells)(struct OpenFirmwareIFace *Self, OFNode node);
	uint32 APICALL (*GetNumSizeCells)(struct OpenFirmwareIFace *Self, OFNode node);
	OFNode APICALL (*FindNodeByStrProp)(struct OpenFirmwareIFace *Self, OFNode searchFrom, CONST_STRPTR propName, CONST_STRPTR propVal, BOOL caseIsSignificant);
	OFNode APICALL (*FindNodeByName)(struct OpenFirmwareIFace *Self, OFNode searchFrom, CONST_STRPTR name);
	OFNode APICALL (*FindNodeByDeviceType)(struct OpenFirmwareIFace *Self, OFNode searchFrom, CONST_STRPTR device);
	OFNode APICALL (*FindCompatibleNode)(struct OpenFirmwareIFace *Self, OFNode searchFrom, CONST_STRPTR compat);
	OFNode APICALL (*FindNodeByPath)(struct OpenFirmwareIFace *Self, CONST_STRPTR path);
	uint32 APICALL (*GetPropDataLong)(struct OpenFirmwareIFace *Self, OFNode node, CONST_STRPTR propName, uint32 index, uint32 defaultVal);
};

#ifdef __cplusplus
}
#ifdef __USE_AMIGAOS_NAMESPACE__
}
#endif
#endif

#endif /* OPENFIRMWARE_INTERFACE_DEF_H */
