#ifndef PASEMI_DMA_INTERFACE_DEF_H
#define PASEMI_DMA_INTERFACE_DEF_H

/*
** This file was machine generated by idltool 53.5.
** Do not edit
*/ 

#ifndef EXEC_TYPES_H
#include <exec/types.h>
#endif
#ifndef EXEC_EXEC_H
#include <exec/exec.h>
#endif
#ifndef EXEC_INTERFACES_H
#include <exec/interfaces.h>
#endif

#ifndef RESOURCES_PASEMI_DMA_H
#include <resources/pasemi_dma.h>
#endif

#ifdef __cplusplus
#ifdef __USE_AMIGAOS_NAMESPACE__
namespace AmigaOS {
#endif
extern "C" {
#endif

struct PASDMAIFace
{
	struct InterfaceData Data;

	uint8 APICALL (*ReadDMARegByte)(struct PASDMAIFace *Self, uint32 reg);
	uint16 APICALL (*ReadDMARegWord)(struct PASDMAIFace *Self, uint32 reg);
	uint32 APICALL (*ReadDMARegLong)(struct PASDMAIFace *Self, uint32 reg);
	void APICALL (*WriteDMARegLong)(struct PASDMAIFace *Self, uint32 reg, uint32 value);
	void APICALL (*WriteIOBRegLong)(struct PASDMAIFace *Self, uint32 reg, uint32 value);
	struct PASDMAChannel * APICALL (*AllocChannel)(struct PASDMAIFace *Self, PASDMAChannelType chanType, uint32 totalSize);
	void APICALL (*FreeChannel)(struct PASDMAIFace *Self, struct PASDMAChannel * dmaChannel);
	void APICALL (*StartChannel)(struct PASDMAIFace *Self, struct PASDMAChannel * dmaChannel, uint32 cmdsta);
	BOOL APICALL (*StopChannel)(struct PASDMAIFace *Self, struct PASDMAChannel * dmaChannel);
	uint32 APICALL (*AllocRing)(struct PASDMAIFace *Self, struct PASDMAChannel * dmaChannel, uint32 numEntries);
	void APICALL (*FreeRing)(struct PASDMAIFace *Self, struct PASDMAChannel * dmaChannel);
	APTR APICALL (*AllocBuffer)(struct PASDMAIFace *Self, uint32 numBytes);
	void APICALL (*FreeBuffer)(struct PASDMAIFace *Self, APTR buffer);
	int8 APICALL (*AllocEvent)(struct PASDMAIFace *Self);
	void APICALL (*FreeEvent)(struct PASDMAIFace *Self, uint8 eventID);
	void APICALL (*SetEvent)(struct PASDMAIFace *Self, uint8 eventID);
	void APICALL (*ClearEvent)(struct PASDMAIFace *Self, uint8 eventID);
	int8 APICALL (*AllocFunction)(struct PASDMAIFace *Self);
	void APICALL (*FreeFunction)(struct PASDMAIFace *Self, uint8 funcID);
};

#ifdef __cplusplus
}
#ifdef __USE_AMIGAOS_NAMESPACE__
}
#endif
#endif

#endif /* PASEMI_DMA_INTERFACE_DEF_H */
