#ifndef POPUPMENU_INTERFACE_DEF_H
#define POPUPMENU_INTERFACE_DEF_H

/*
** This file was machine generated by idltool 52.6.
** Do not edit
*/ 

#ifndef EXEC_TYPES_H
#include <exec/types.h>
#endif
#ifndef EXEC_EXEC_H
#include <exec/exec.h>
#endif
#ifndef EXEC_INTERFACES_H
#include <exec/interfaces.h>
#endif

#ifndef CLASSES_POPUPMENU_H
#include <classes/popupmenu.h>
#endif

#ifdef __cplusplus
#ifdef __USE_AMIGAOS_NAMESPACE__
namespace AmigaOS {
#endif
extern "C" {
#endif

struct PopupMenuIFace
{
	struct InterfaceData Data;

	ULONG APICALL (*Obtain)(struct PopupMenuIFace *Self);
	ULONG APICALL (*Release)(struct PopupMenuIFace *Self);
	void APICALL (*Expunge)(struct PopupMenuIFace *Self);
	struct Interface * APICALL (*Clone)(struct PopupMenuIFace *Self);
	Class * APICALL (*POPUPMENU_GetClass)(struct PopupMenuIFace *Self);
	Class * APICALL (*POPUPMENU_GetItemClass)(struct PopupMenuIFace *Self);
	APTR APICALL (*POPUPMENU_MakeMXListA)(struct PopupMenuIFace *Self, ULONG * ids);
	APTR APICALL (*POPUPMENU_MakeMXList)(struct PopupMenuIFace *Self, ...);
	VOID APICALL (*POPUPMENU_FreeIDList)(struct PopupMenuIFace *Self, APTR idlist);
	APTR APICALL (*POPUPMENU_MakeIDListA)(struct PopupMenuIFace *Self, struct TagItem * tags);
	APTR APICALL (*POPUPMENU_MakeIDList)(struct PopupMenuIFace *Self, ...);
};

#ifdef __cplusplus
}
#ifdef __USE_AMIGAOS_NAMESPACE__
}
#endif
#endif

#endif /* POPUPMENU_INTERFACE_DEF_H */
