#ifndef TIMESYNC_INTERFACE_DEF_H
#define TIMESYNC_INTERFACE_DEF_H

/*
** This file was machine generated by idltool 52.6.
** Do not edit
*/ 

#ifndef EXEC_TYPES_H
#include <exec/types.h>
#endif
#ifndef EXEC_EXEC_H
#include <exec/exec.h>
#endif
#ifndef EXEC_INTERFACES_H
#include <exec/interfaces.h>
#endif

#ifndef LIBRARIES_TIMESYNC_H
#include <libraries/timesync.h>
#endif

#ifdef __cplusplus
#ifdef __USE_AMIGAOS_NAMESPACE__
namespace AmigaOS {
#endif
extern "C" {
#endif

struct TimesyncIFace
{
	struct InterfaceData Data;

	ULONG APICALL (*Obtain)(struct TimesyncIFace *Self);
	ULONG APICALL (*Release)(struct TimesyncIFace *Self);
	void APICALL (*Expunge)(struct TimesyncIFace *Self);
	struct Interface * APICALL (*Clone)(struct TimesyncIFace *Self);
	ULONG APICALL (*RemoteSyncA)(struct TimesyncIFace *Self, const struct TagItem * taglist);
	ULONG APICALL (*RemoteSync)(struct TimesyncIFace *Self, ...);
};

#ifdef __cplusplus
}
#ifdef __USE_AMIGAOS_NAMESPACE__
}
#endif
#endif

#endif /* TIMESYNC_INTERFACE_DEF_H */
